### ISSUE TITLE
How can I force to add notes when I changed status to resolved?

### ISSUE THREAD

**Issue by archonwang** [onozaty/redmine-view-customize-scripts#1]
How can I force users to add notes when the status changed to resolved or refused? Thanks.

**Comment by archonwang** [comment]
OK, I used the following code

> /*
> Path pattern: /issues/
> Type: JavaScript
> */
> $(function() {
>   $('#issue-form input[type="submit"]')
>     .on('click', function(event) {
>       var statusId = $('#issue_status_id').val();
>       var notes = $('#issue_add_notes').val();
> 
> ```
>   if (statusId == '6' && !notes) { // 6:Refused
>     alert('please submit notes！');
>     return false;
>   }
> });
> ```
> 
> });

but I have another question . when I used issue list and right click to change the status to refused, how to raise an alert? Thanks.

**Comment by onozaty** [comment]
Please try the following.

``` javascript
/*
Path pattern: /issues$
Type: JavaScript
*/
$(function() {
  var handler = function() {
    alert('can not change to "Refused" from the context menu');
    return false;
  }

  $(document)
    .on('mouseover', '#context-menu a[href*="status_id%5D=6"]', function(event) {
      $(this)
        .attr('href', '#')
        .off('click', handler)
        .on('click', handler);
    });
});
```

**Comment by archonwang** [comment]
@onozaty ，Thanks so much.
I tried in the issue list when I right click and change the status to "Refused", it's OK.

And there's another question about it, how can I force user to submit some notes when I open some issue, just like when I open the issues #123, I can still modified the issue status to "Refused" without any  notes. 

Thanks so much.

**Comment by onozaty** [comment]
> And there's another question about it, how can I force user to submit some notes when I open some issue, just like when I open the issues #123, I can still modified the issue status to "Refused" without any  notes. 

Sorry, procedure did not understand.
Please tell me a little more in detail.

**Comment by archonwang** [comment]
for example, 
when I open an issue and click 'Edit', then change the status from New to Refused.
How can I alert the user to commit some comments when he change the status to Refused ? Thanks very much.

**Comment by onozaty** [comment]
Description Thank you.
The following code did not work?

> OK, I used the following code
> 
> ``` javascript
> /*
> Path pattern: /issues/
> Type: JavaScript
> */
> $(function() {
>   $('#issue-form input[type="submit"]')
>     .on('click', function(event) {
>       var statusId = $('#issue_status_id').val();
>       var notes = $('#issue_add_notes').val();
>       if (statusId == '6' && !notes) { // 6:Refused
>         alert('please submit notes！');
>         return false;
>       }
>     });
> });
> ```

**Comment by archonwang** [comment]
@onozaty ,
It did but not work very well ,  for I used plugin  named redmine_ckeditor, and it seems it can not directly use the notes.... 

Could you help me?  Thanks so much.

**Comment by onozaty** [comment]
CKEditor is like using a `issue_notes` instead `issue_add_notes`.
Please try the following

``` javascript
var notes = $('#issue_notes').val();
```

**Comment by archonwang** [comment]
Thanks so much. It works!!
when changing to Refuesd status,  installed redmine_ckeditor and in the issue edit page.

```
/*
Path pattern: /issues/
Type: JavaScript
show_alert_if_refused_without_notes.js
*/
$(function() {
  $('#issue-form input[type="submit"]')
    .on('click', function(event) {
      var statusId = $('#issue_status_id').val();
/*
//   if you use standard editor, you should use this;
      var notes = $('#issue_add_notes').val();  
*/


//   if you use redmine_ckeditor, you should use this as follow;
      var notes = $('#issue_notes').val();

      if (statusId == '6' && !notes ) { // 6:Refused
        alert('Alert！Cann't changed status to Refused! \nPlease open the issue detail, change the stutas to Refused and post some NOTES!');
        return false;
      }
    });
});

```
