### ISSUE TITLE
how to realize the scene: The role have "new issue" permission ,but  the issue list page doesn't display the "New Issue" botton when the role  log in Redmine

### ISSUE THREAD

**Issue by lilyroselily** [onozaty/redmine-view-customize-scripts#10]
@onozaty 
hi,Onozaty

firstly,thanks for the view-customize plugin that is very useful for me to resolve some situation.👍  👍  🥇 🥇 
now,there is a new question,but I don't know how to write scripts to do it.
may u give some adivice? thanks a lot.the question is that:
there are two roles ,Pm(Project Manager) and Gm(Group Manager).
but the Gms have the permission that can copy issue and add sub issue but can't  new issue.
I want that the issue list page doesn't display the "New Issue" botton when the role Gms log in Redmine.
but when Gms go to issue detail page , Gms can copy the issue or add sub issue.
are there the scripts to realize this scene?
best regards to you

**Comment by onozaty** [comment]
Hi @lilyroselily 

Since role information can not be acquired with View customize, it can not be controlled.
I plan to implement a way to change script execution of each roles in the near future.
Please wait until then.

Thanks

**Comment by lilyroselily** [comment]
@onozaty 

Thanks for your reply.
Looking forward to your new idea and plugins
