### ISSUE TITLE
Try SLA with View Customize.

### ISSUE THREAD

**Issue by robertotsi** [onozaty/redmine-view-customize-scripts#100]
I need to do a SLA in my project. 
So I thought when an user set in issue_status_id = 'Start' I get the information "updated_on": "2022-01-23T13:56:56Z", from history and put/safe into the disable field automatically this information, filling and disable start_date too. I need hour to start date, but this field haven't this information.

How can I do this. It's possible?

**Comment by onozaty** [comment]
I think it would be difficult to obtain the date and time of the status change.
I can't think of a way to take it out in View customize.

If you want to set the current date in a custom field of date type on the screen when the status is changed, I think it can be done.
But what you need is the date and time, right?

**Comment by robertotsi** [comment]
Yes, I need date and time. 
Is it possible to capture the hour from server or my machine and save a custom field?
I was thinking here when an user set a status Start, if is possible to get the information of date from server or machine and save a custom field type text and blocked or disable.

**Comment by onozaty** [comment]
It is not possible to retrieve server-side information, but it is possible to retrieve and set the date and time on the browser.

I have written an example below for your reference.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0052.set_current_date_when_status_changed/example.md

Thanks.
