### ISSUE TITLE
custom field id

### ISSUE THREAD

**Issue by b4ri5** [onozaty/redmine-view-customize-scripts#103]
hi,
i'm new at redmine and scripts. could you help me about how can i define custom fields id. my redmine is running on ubuntu 
Best regards

**Comment by onozaty** [comment]
You can check the HTML.

With Chrome's Developer Tools, you can check it as follows.

![image](https://user-images.githubusercontent.com/47337/209436149-bbb24190-6eec-4f5e-b0fc-53f81795f15f.png)

**Comment by b4ri5** [comment]
ok i found it. but how can i set my child fields items? my parent field includes 10 items and i want just first one of my parent fields items select and than chose child item of the parents one. instead of first parent items, i don't want child items.
best regards

**Comment by b4ri5** [comment]
i think i should use [0008.change_custom_field_visibility_by_status] for it. but i dont know how can i do it. please help me sir.

br

**Comment by b4ri5** [comment]
here you can see my codes. but when i do it. my child fields never seen

$(function() {

  const targetCustomFieldId = '49';

  const targetCustomFieldInput = $('#issue_custom_field_values_' + targetCustomFieldId);
  const targetCustomFieldDisplay = $('div.cf_' + targetCustomFieldId + '.attribute');

  const visible = $('issue_custom_field_values_7').val() == 'YANGIN';

  if (visible) {
    targetCustomFieldInput.parent().show();
    targetCustomFieldDisplay.show();
  } else {
    targetCustomFieldInput.parent().hide();
    targetCustomFieldDisplay.hide();
  }
});

**Comment by onozaty** [comment]
First of all, i do not know what you want to achieve.
Could you please explain in more detail?
What custom fields do you have and what do you want to do with them?

Thanks.

**Comment by b4ri5** [comment]
i have 2 custom fields. parent(id=7) and child (id=49)
parent have 10 items. a,b,c,d,e,f,g and child have a1,a2,a3,a4,a5
if i select "a", child will be visible and selectable.
if i select instead of "a", child will. be hidden

**Comment by onozaty** [comment]
Hi @b4ri5 

Is this resolved?
If you have not solved the problem, I will write sample code in the near future.

Thanks.

**Comment by b4ri5** [comment]
Hi
Unfortunatelly it did not solved my problem

**Comment by onozaty** [comment]
Hi @b4ri5 

I created an example code.
Please refer to the following.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0054.change_child_custom_field_visibility_by_parent_custom_filed/example.md

Thanks.
