### ISSUE TITLE
新規チケット作成時に特定のカスタムフィールドへユニークIDを自動発行したいです

### ISSUE THREAD

**Issue by barinosuke** [onozaty/redmine-view-customize-scripts#106]
メールでお問い合わせさせていただいていた者です。

条件は
新規チケット作成時で
アルファベット2文字からはじまり、UNIXタイムスタンプで構成されるものを
固有管理IDとして発行したいです

例）ab1234567890

また、一括でCSVインポートする際にも
上記のように固有のIDをそれぞれ払い出すのは難しいでしょうか
UNIXタイムスタンプでなくとも、ランダムでかぶらなければ問題ございません。

よろしくお願いします。

**Comment by onozaty** [comment]
新規チケット作成時にデフォルト値を設定することになりますので、下記が参考になります。

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0055.set_author_as_default_value_for_custom_field/example.md

Unixタイムは `Math.floor(new Date().getTime() / 1000)` のような形で求められるので

```javascript
$('#issue_custom_field_values_1').val('ab' + Math.floor(new Date().getTime() / 1000));
```

といった形で設定できるのではと思います。

> また、一括でCSVインポートする際にも
>上記のように固有のIDをそれぞれ払い出すのは難しいでしょうか

CSVインポートで自動的に何かを払い出すことはできないと思います。
なので、やるならばCSV時点で固有のIDを入れておいて、それをカスタムフィールドにマッピングするしかないのではと思います。

> UNIXタイムスタンプでなくとも、ランダムでかぶらなければ問題ございません。

Redmineで払い出されるチケットのIDでは問題ありますでしょうか。
ランダムでは無いですが、一意なものにはなります。

**Comment by barinosuke** [comment]
ありがとうございます！
チケット新規作成時には無事できました。

やはりそうですよね
あ、確かにチケットIDで代替聞くかもしれません盲点でした。

ありがとうございました
