### ISSUE TITLE
郵便番号に応じて自動反映される住所連動フィールドの作成

### ISSUE THREAD

**Issue by barinosuke** [onozaty/redmine-view-customize-scripts#107]
メールで問い合わせさせていただいた者です。

カスタムフィールドを
・郵便番号
・住所　で用意し

郵便番号に正しい数字が入力された際に
都道府県～市区町村の住所情報が
住所のカスタムフィールドに自動反映されるようにする方法はございますでしょうか

よろしくお願いします。

**Comment by onozaty** [comment]
下記でサンプルを作成してみましたので参考にしていただけますでしょうか。

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0056.get_address_from_zipcode_with_webapi/example.md

**Comment by barinosuke** [comment]
ありがとうございます。
無事いい感じに設定できました。

ちなみに別住所の郵便番号に上書きなどする際は
一旦空欄にしないとできないのでしようか？

**Comment by onozaty** [comment]
サンプルでは空欄であることをチェックしているだけなので、そこの処理を外していただければ上書きできるようになります。
`if (addressField.val() == '')` の部分です。

**Comment by barinosuke** [comment]
ありがとうございます！
無事できました。
終始ご丁寧に助かりました。
とても勉強になりました。
