### ISSUE TITLE
depend in api,can connect in oracle database

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#108]
[](https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0056.get_address_from_zipcode_with_webapi/example.md)

thx for the perfect example
can i in the same way can i fetch data from oracle database ,if im ask the administration for database create web page for search field
to get data for another fields

or if u give another example for fetching data from another database(oracle) ?/

thx for your support and help

**Comment by onozaty** [comment]
I think it is impossible because the database does not provide a Web API.
Thanks.

**Comment by ashrafalzyoud** [comment]
The oracle support web api and can create REST api

**Comment by onozaty** [comment]
Have you ever used its API to make it work?
I think you need to make sure you can use that API before using it in View customize.

I cannot verify that it works with Oracle, so can you be more specific about what you want to know?
I can't provide any support with the information you have right now.
