### ISSUE TITLE
Change projects link to "my projects"

### ISSUE THREAD

**Issue by frankz96** [onozaty/redmine-view-customize-scripts#109]
I have many projects and they look very long in Projects view. So I want to change the projects link to "my projects" which add a fliter project equals to "my project". I read the [0006.change_project_link_url](https://github.com/onozaty/redmine-view-customize-scripts/tree/master/examples/0006.change_project_link_url) but I couldn't revise it to what i want. I would very much appreciate it if anyone can help me!

**Comment by onozaty** [comment]
You can change the project link to my projects by doing the following.

```javascript
$(function() {
  const projectsLink = $('#top-menu a.projects, #main-menu a.projects');
  projectsLink.attr('href', projectsLink.attr('href') + '?query_id=5');
})
```

![projects](https://user-images.githubusercontent.com/47337/220626527-e695a992-77c8-4638-882b-b97fd34bd16a.gif)

Thanks.

**Comment by frankz96** [comment]
> You can change the project link to my projects by doing the following.
> 
> ```js
> $(function() {
>   const projectsLink = $('#top-menu a.projects, #main-menu a.projects');
>   projectsLink.attr('href', projectsLink.attr('href') + '?query_id=5');
> })
> ```
> 
> ![projects](https://user-images.githubusercontent.com/47337/220626527-e695a992-77c8-4638-882b-b97fd34bd16a.gif) [ ![projects](https://user-images.githubusercontent.com/47337/220626527-e695a992-77c8-4638-882b-b97fd34bd16a.gif) ](https://user-images.githubusercontent.com/47337/220626527-e695a992-77c8-4638-882b-b97fd34bd16a.gif) [ ](https://user-images.githubusercontent.com/47337/220626527-e695a992-77c8-4638-882b-b97fd34bd16a.gif)
> 
> Thanks.

Thank you so much! It's more complicated than I thought, but it's working!
