### ISSUE TITLE
How to arrange custom fields in issue form?

### ISSUE THREAD

**Issue by ieseberri** [onozaty/redmine-view-customize-scripts#11]
Hello,

Is there any way to arrange custom fields inside a issue form with 'view customize' plugin?

Thank you!

**Comment by onozaty** [comment]
Hi @ieseberri 

Where is the "inside a issue form"?
Please tell me more in detail.

**Comment by ieseberri** [comment]
Hello Onozaty,

Thanks for answer to my question. I've used your plugin to customize the standard issue view. I want to be able to organize the fields when they are editable. Is it possible? I've defined several custom fields and my idea is group them in some sort of frames or sets. 

Thank you!

**Comment by ieseberri** [comment]
Just to add more information...

![imagen](https://user-images.githubusercontent.com/32834927/32167264-b3b69b0e-bd68-11e7-80e0-1762592e3313.png)

I'm able to arrange custom fields using the following code (as you can see in the picture above)

![imagen](https://user-images.githubusercontent.com/32834927/32167605-aedc3084-bd69-11e7-9fb6-b4e6c18a0458.png)

But  we want to arrange the fields also when we are editing the issue...

![imagen](https://user-images.githubusercontent.com/32834927/32167434-1d7de40c-bd69-11e7-8580-df3c523d04aa.png)
Is it possible?

Can you give an example?

Thank you!!!

**Comment by onozaty** [comment]
Hi @ieseberri

It is possible.
How about changing "div#attributes" in the same way?

**Comment by ieseberri** [comment]
Please I'm very newbie... can you give an example?

**Comment by ieseberri** [comment]
I've seen there two 'attributes' classes in the same form...

**Comment by ieseberri** [comment]
![imagen](https://user-images.githubusercontent.com/32834927/32178848-157fadb0-bd8e-11e7-9cb4-c996e030f371.png)

I can create new H2 tags but how can I move edit fields?

**Comment by ieseberri** [comment]
![imagen](https://user-images.githubusercontent.com/32834927/32178981-727488a6-bd8e-11e7-8e67-5ca432d770ad.png)

How can I arrange the 'label' and the 'select' objects?

**Comment by onozaty** [comment]
Please select parent `p` tag.
Write the code as follows.

```
$('#issue_custom_field_values_9').parent()
```

**Comment by ieseberri** [comment]
![imagen](https://user-images.githubusercontent.com/32834927/32180511-76ea25d6-bd92-11e7-8c59-8f03b7c62995.png)

And if I want to create something like the code above?

Separate the custom fields on right and left, what should be the code?

Thanks!

**Comment by onozaty** [comment]
Hi @ieseberri 

Please refer to the code below.
Change `issue_custom_field_values_x` as appropriate.

```javascript
// content1
var content1left = $('<div class="splitcontentleft">');
var content1right = $('<div class="splitcontentright">');

// append custome fields
content1left.append($('#issue_custom_field_values_1').parent());
content1right.append($('#issue_custom_field_values_2').parent());

var content1 = $('<div class="splitcontent">')
  .append(content1left)
  .append(content1right);

$('div#attributes')
  .append($('<h3>content1</h3>'))
  .append(content1);

// content2
var content2left = $('<div class="splitcontentleft">');
var content2right = $('<div class="splitcontentright">');

// append custome fields
content2left.append($('#issue_custom_field_values_3').parent());
content2right.append($('#issue_custom_field_values_4').parent());

var content2 = $('<div class="splitcontent">')
  .append(content2left)
  .append(content2right);

$('div#attributes')
  .append($('<h3>content2</h3>'))
  .append(content2);
```

**Comment by ieseberri** [comment]
Thank you very much!!!

**Comment by SHNev** [comment]
Hello onozaty,

Hope you are doing well.
I need a script for your plugin "view customize" so that in issue form if I changed status as a 'Complete' Then attachment (redmine features to upload file related to project) is required to attach. And if status is other that complete then it is not necessary to attach the file.
Please can You Help me.

**Comment by onozaty** [comment]
> Hello onozaty,
> 
> Hope you are doing well. I need a script for your plugin "view customize" so that in issue form if I changed status as a 'Complete' Then attachment (redmine features to upload file related to project) is required to attach. And if status is other that complete then it is not necessary to attach the file. Please can You Help me.

Hi @SHNev 

Can you make it as a new Issue?
It would be helpful if you could also include details of what you would like to do.

Thanks.
