### ISSUE TITLE
Change the URL for custom field type file or added button to scanner

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#110]
Hi 
I hope you are fine

The custom field type file it's have ( browse file)
When u click on it by default it's open my computer

How I can change the path for  /D:/new folder/ **or** open the scanner application
because i have the policy in pcs not open the C: directory

![scanner](https://user-images.githubusercontent.com/50211455/221043087-9f4fea47-4658-484a-9343-9c6e5e8fec0d.png)
i hope i can added the button beside choose file and same job
but the deference **choose file** upload files from pc
**scan** open the scan application after scan the files upload in system
im search in different way by using javascripts 
`<button type="button" value="scan" onclick="scanAsPdf();">PDF</button>
`
`<button type="button" value="print" onclick="window.print();">print</button>
`
```
function run(){
var WshShell=new ActiveXOBject(WScript.Shell");
WshShell.run("c:/windows/system32/scanner.exe",1,false)
}
```

but i hope u help me about this issue to added buttom for custom_field type file

**Comment by onozaty** [comment]
ActiveXOBject is an old technology.
Only available in older IE.
Therefore, I think it is not feasible.

Also, from a security standpoint, I believe that launching other applications from within the browser would not be permitted.

Thanks.

**Comment by ashrafalzyoud** [comment]
Thx for your reply and your opinion

Then how I can change the path when I click in ( choose file) from my computer to d:/stoarge

**Comment by onozaty** [comment]
For security reasons, it does not appear to be possible to obtain or rewrite the actual path information.

* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

Thanks.

**Comment by ashrafalzyoud** [comment]
Thx for you
