### ISSUE TITLE
チケットコピー時にコピー元に関連設定された項目の追加、またその項目のCSV出力

### ISSUE THREAD

**Issue by barinosuke** [onozaty/redmine-view-customize-scripts#111]
いつもお世話になっております。

チケットコピー時に関連設定する項目のデフォルトが
・ステータス
・担当者
・期日　等ありますが

そのコピー元に表示される項目を
カスタマイズする方法はございますでしょうか

また、CSVエクスポート時に
表示されている関連チケットの表示項目（例：ステータス）もあわせて
出力することは可能でしょうか？

よろしくお願いします。

**Comment by onozaty** [comment]
> いつもお世話になっております。
> 
> チケットコピー時に関連設定する項目のデフォルトが ・ステータス ・担当者 ・期日　等ありますが
> 
> そのコピー元に表示される項目を カスタマイズする方法はございますでしょうか
> 

コピー時のフォームの情報はサーバ側で作成されるので、View customizeで出来そうなこととしてはクリアするくらいとなります。
もう少し具体的にやりたいことを教えていただけますでしょうか。

> また、CSVエクスポート時に 表示されている関連チケットの表示項目（例：ステータス）もあわせて 出力することは可能でしょうか？
> 

View customizeで出来るか？という質問でしたら、出来ないです。(CSVを作るのはサーバ側であり、View customizeで出来る範囲を超えている)
Redmineの機能でとなると、ここで答えるのも変かもしれませんが、、私が知る限りはできないと思います。

**Comment by barinosuke** [comment]
お忙しいところご返信ありがとうございます。

むずかしい旨承知しました。
指定したカスタムフィールドを追加表示できればと思ってでした。

csvに関しても不適切な場で伺ってしまい失礼しました。
むずかしい旨も承知しました。

また、github Issuesの勝手があまりわかっておらず気軽に何度も質問してしまい大変申し訳ございません。
以後、可能な限り自己解決できるよう努めます。

何度も助けていただき感謝しております。
本当にご対応ありがとうございます、、！

**Comment by onozaty** [comment]
> むずかしい旨承知しました。 指定したカスタムフィールドを追加表示できればと思ってでした。

コピー先の話かと勘違いしていました、、
関連するチケットのコピー元の部分の表示のことでしたね。

View customizeでは、画面にある情報ならば、ある程度簡単に表示内容を変えることができるのですが、画面に無い情報だと難しくなります。
RedmineにはREST APIがあり、これを使えばサーバから追加で情報を取得することも出来ますが、これをView customizeでやるとそれなりに複雑になりますのであまりお勧めできません。

> 
> csvに関しても不適切な場で伺ってしまい失礼しました。 むずかしい旨も承知しました。
> 

あ、不適切ということもありませんので大丈夫です。
単にView customizeでの話しなのか、Redmineの機能的な話なのか読み取れなかったので、このような返信になってしまいました。

> また、github Issuesの勝手があまりわかっておらず気軽に何度も質問してしまい大変申し訳ございません。
> 以後、可能な限り自己解決できるよう努めます。

View customizeに関することでしたら、こちらでIssueあげていただいて大丈夫です。
試していただいて、ここがうまく動かない、わからないなどあれば、引き続きこちらをご利用ください。

Redmineの機能に関するものならば、他のコミニティを使うと良い(私よりもっと詳しい方も多いので)と思います。
参考までに、日本のRedmineコミニティのリンクを貼っておきます。

* [日本のRedmineコミュニティ — Redmine\.JP](https://redmine.jp/community/)

**Comment by barinosuke** [comment]
ご返信ありがとうございます。

項目追加に関して、承知いたしました。
また、Issueに関してもご丁寧にありがとうございます。
どうしても困った際は活用させていただきます！

リンク共有いただいたものに関しても
そんなものがあったのかと無知でお恥ずかしいです。大変助かります。
早速参加させていただきました。

色々と本当にありがとうございました。
