### ISSUE TITLE
examples/0018.add_search_function_to_selectbox/example.md

### ISSUE THREAD

**Issue by formigadiablo** [onozaty/redmine-view-customize-scripts#112]
Can this be applied to issues when log in spent time?

Thanks

**Comment by formigadiablo** [comment]
I tried to replace by time_entry_issue_id

**Comment by onozaty** [comment]
I don't understand what you want to do.
Could you please elaborate a little more?

**Comment by formigadiablo** [comment]
I would like to have also a select box in the spent time tab when picking up the issue
![image](https://user-images.githubusercontent.com/124778067/221169801-9bdc8ae8-dc17-4024-95cf-2731467d2e7d.png)

**Comment by onozaty** [comment]
This is not a selectbox and cannot be done the same way.

There is a search function originally, but is that not enough?

![issue](https://user-images.githubusercontent.com/47337/221172699-58d46af7-f989-4440-bf85-acc4a33bb7ed.gif)

**Comment by formigadiablo** [comment]
Okay thanks! I wanted because I never remmember the issue # but nevermind!

Thanks, and thanks for the plugin, I am using some of your codes and I find them very useful
