### ISSUE TITLE
Do not parse groups in assigne

### ISSUE THREAD

**Issue by qawsed55** [onozaty/redmine-view-customize-scripts#113]
If I put group number to script - script do not work.

```
$(function() {
    switch($('#issue_status_id').val()) {
      case '58':
        $('#issue_assigned_to_id').val('46');
        break;
    }
  });
```
If I put number of project member (not group) - it works ok!
Can you add functionality to work with group assignies?
Thank you!

**Comment by onozaty** [comment]
The code looks fine.
Does the group you specified exist as a candidate for Assignee?

**Comment by qawsed55** [comment]
> Does the group you specified exist as a candidate for Assignee?

I took users and groups numbers from debug console from browser.
Manualy, when editing ussue - I can assign to group (thay are listed in assignees list). But script works just with users, that are listed, not with groups.

**Comment by onozaty** [comment]
After manually assigning the group, could you try executing the following from your browser console?

```
$('#issue_assigned_to_id').val();
```

**Comment by qawsed55** [comment]
```
$('#issue_assigned_to_id').val();
'14'
```

This work ok, thank you, I'm understand way to see what happening )
First time it works.
Then, I try to change one more time and it is do not work.
I refresh page, press EDIT ISSUE, and it is do not work.
Very strange.
But, also, I see errors in console 
`application.js?1678046162:108          GET http://192.168.0.250/plugin_assets/redmine_ckeditor/ckeditor/plugins/wsc/skins/kama/wsc.css?t=KA9B net::ERR_ABORTED 404 (Not Found)`
Now, will try to fix that plugin (or reinstall it) and then I'll try to work with your nice addon.
I will write result.
Thank you!
