### ISSUE TITLE
Writing back a value to a project custom field

### ISSUE THREAD

**Issue by HansSchlumpf** [onozaty/redmine-view-customize-scripts#114]
Hello
first of all thanks for this great plugin for REDMINE!

I'm trying to write back a value to a custom field in the project - in the javascript it works (the second alert() gives the new value back), but the value in the custom field in the project doesn't change to the new value. 
My code:

```
   // test how to write into an project field
        // read original value
          let field = ViewCustomize.context.project.customFields.find(x => x.id == 51);
          let fieldValue = (field == undefined) ? undefined : field.value;
          var PrjTestWritingField = fieldValue;
          alert('Actual ReportingTestWritingField\n\n' + PrjTestWritingField);

        // set new value
          field = ViewCustomize.context.project.customFields.find(x => x.id == 51);
          fieldValue = (field == undefined) ? undefined : field.value;
          field.value = 'New Test Value';

       // read back
          field = ViewCustomize.context.project.customFields.find(x => x.id == 51);
          fieldValue = (field == undefined) ? undefined : field.value;
          PrjTestWritingField = fieldValue;
          alert('Updated ReportingTestWritingField\n\n' + PrjTestWritingField);

```

Can you please tell me, how is the correct code to really write back a value to a project-custom field?

Many thanks and best regards

Hans

**Comment by onozaty** [comment]
`ViewCustomize.context` is read-only and cannot be updated by setting values.
The REST API must be used to update the values.

* https://www.redmine.org/projects/redmine/wiki/Rest_Projects#Updating-a-project

It is not impossible to do this with View customize, but it is quite tedious and not recommended.

Thanks.
