### ISSUE TITLE
I need a tunning a list custom_field with the content of the projects custom list field

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#115]
Hi onozaty,
 I have a problem that I can not resolve.  I wait that you can resolve it.
I have a list custom field in a project level with 7 lines.
I can receive it in a const:
const field = ViewCustomize.context.project.customFields.find(x => x.id == 36);
const ellote = (field == undefined) ? undefined : field.value;

Now, ellote return three values (list wih multiple values) in this format:  Lote 2: Aplicaciones en PHP,Lote 4: Aplicaciones Estadísticas,Lote 3: Portales SGAD
Three  values separates by comma,

Now I have other custom list field in the issue with the same 7 lines.

I need that if in the field of the project I select  1,2, or diferent values, in the issue custom list field only appear the same values that I selected in the proyect custom field and not all the lines. After the user only can select one value of the filter list.
Its possible?
 
If you don't understand (is normal, because I don't explain very well), say me and I can say it with an example.

Thank you  for you support.
Regards

**Comment by onozaty** [comment]
Hi @jlsblasco 

I'm sorry. Could you please explain in more detail?

Thanks.

**Comment by jlsblasco** [comment]
Hi again, sorry for my basd explanation.
I have a list field in the project configuration menu
![image](https://user-images.githubusercontent.com/50949839/234562714-23d99498-c1ad-417a-81cb-6b3b00412e4f.png)
I can select one o variuos lines
When I include a new issue in this project, I need to show another field with the same list, but only with the records selected in the project list field.
Example:
In the project configuration I have 7 lines in the list field (Lote 1, Lote2, Lote 3, Lote 4, Lote 5, Lote 6 & Lote 7) , but in this project I select 3 options (Lote 1, Lote3 and Lote 5).
Now, I have other field list in a issue with the same 7 values., but when I create a issue in this field list only must  to show the 3 values selected in the project list field.
With this method I can select in diferent projects, diferent possibles values.

I'm not sure that I can explain correctly now too.

**Comment by onozaty** [comment]
I understood the following.

* There are custom fields with the same items in the Project and Issue.
* Only the values specified in a custom field in a project can also be selected in an Issue.

I'll think of a way to do it.

**Comment by jlsblasco** [comment]
Yes Onozaty, You now understand my problem.
Thank you.

**Comment by onozaty** [comment]
I have written a example for you to try.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0058.control_issue_custom_field_with_project/example.md

**Comment by jlsblasco** [comment]
Fantastic, as always you are my savior

Thank you again for you suport.
