### ISSUE TITLE
How to take the name of the category of issue

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#116]
Hi again,
 I use the categories in one type of tracker.
I can take the id of the tracker correctly:
const categoria = $('#issue_category_id').val();
but I need to take the name of the category
I can not take it, in the source of the code exist:

![image](https://user-images.githubusercontent.com/50949839/235106506-f25d1644-669a-47ab-8430-ce3c128bc322.png)
![image](https://user-images.githubusercontent.com/50949839/235106795-8b51f835-3703-4f11-abdb-cc161f723d61.png)

I need to take 'LOTE 4: .........'

It's possible to take it in a variable?

Thank you in advance for you support.

**Comment by jlsblasco** [comment]
Sorry , I put the correct line in source code:
![image](https://user-images.githubusercontent.com/50949839/235107552-a8158c6b-aa35-4e46-896d-40160ab573c4.png)
![image](https://user-images.githubusercontent.com/50949839/235107692-81156e5a-f20f-4a85-8849-55cc935efbc5.png)

![image](https://user-images.githubusercontent.com/50949839/235107846-1da5eb1a-d1e9-4acf-8c45-ed0669f12ff4.png)

![image](https://user-images.githubusercontent.com/50949839/235107998-5306a4b5-53eb-4d3e-a63e-46f677a92306.png)

Regards

**Comment by onozaty** [comment]
Can you get it with the following code?

```javascript
$('#issue_category_id > option:selected').text();
```

Please refer to the Tips section as well for information on how to obtain various types of information on Issue.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/tips/tips.md#get-the-value-of-a-issue-field

Thanks.

**Comment by jlsblasco** [comment]
Thank you, the  option run ok.
I have this simpe code:
***************
$(function() {

const categoria=$('#issue_category_id > option:selected').text();

$('#issue_custom_field_values_179').val(categoria);


});
***************
I take the name of cateory and put it in a custom field (179).
The result is not ok because always put the old value before changing it.
Example:
In new issue I select one category (Lote 1) and save the issue. In the custom field 179 not write nothing.
Edit the Issue and now select other category (Lote 2 for example), and now write in custon field 179 the before vale (Lote 1).

????? 
I need to write the selected category and not the before value

Thank you in advance

**Comment by onozaty** [comment]
Please refer to the following for creation and editing judgments.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/tips/tips.md#judge-the-creation-and-editing-of-an-issue

Please refer to the following for how to process category changes.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0047.change_visibility_of_custom_fields_by_categories/example.md

Thanks.

**Comment by jlsblasco** [comment]
thank you for you support..... for me its incredible!!!
