### ISSUE TITLE
Change the link in tracker in overview to querey id=1

### ISSUE THREAD

**Issue by saifabood** [onozaty/redmine-view-customize-scripts#117]
how i can change link in page overview
when im click in tracker 1 its open query_id 1
when im click in tracker 2 its open query_id 2

for all projects

**Comment by onozaty** [comment]
The following example may be helpful in changing the query when going to the issue list.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0039.change_default_query_in_issues_tab/example.md

Thanks.

**Comment by saifabood** [comment]
Thx for replay me
Maybe u not understanding me
In the page overview in project
![Screenshot_20230502-005028](https://user-images.githubusercontent.com/113475410/235538298-404355e1-3f1e-4c8b-b484-8780af28c69b.jpg)

If the user click in tracker (defect) the link open query id 1
As example https://www.redmine.org/projects/redmine/issues?set_filter=1&tracker_id=1-------«query id 1

If the user click in tracker (Future) the link open query id 2
As example https://www.redmine.org/projects/redmine/issues?set_filter=1&tracker_id=2-------«query id 2
I'm try your example
```
``
$(function() {
  const issueMenuLink = $('#main-menu a[href$="/overview"]');
  // Note: Change the query ID accordingly.
  issueMenuLink.attr('href', issueMenuLink.attr('href') + '?query_id=1');
});
``
```
But where I can put tracker id 1

**Comment by onozaty** [comment]
You must specify the link you wish to change.
Check the HTML structure and specify it with a CSS selector.

For example, as follows.

```javascript
const link = $('.issue-report td.name a[href$="tracker_id=1"]');
link.attr('href', link.attr('href') + '&query_id=1');
```

Thanks.

**Comment by saifabood** [comment]
Excellent thanks 🙏
It's very important example
