### ISSUE TITLE
Gantt chart close date

### ISSUE THREAD

**Issue by formigadiablo** [onozaty/redmine-view-customize-scripts#118]
I want to compare the due date of an issue (expected finish) to the close date (real finish)

I think it could appear as an extra bar/line in the Gantt chart displaying this difference

I find some posts that might be helpful
https://www.redmine.org/issues/3946
https://www.redmine.org/issues/2024?tab=history

**Comment by onozaty** [comment]
I think it would be difficult with View customize.
This is because it is not possible to get information on the actual completion date.

Thanks.

**Comment by formigadiablo** [comment]
I thought that could happen and I found a plugin that displays the closing date on the issue. Would this idea be possible through the use of this plugin?
https://github.com/fraoustin/redmine_closed_date

Thanks

**Comment by onozaty** [comment]
Even if you use this, I don't think you can refer to the information in View customize.
Therefore, I think it is difficult to do it in View customize.

Thanks.

**Comment by formigadiablo** [comment]
Okey! Will try to find someone to develop it.

Thanks!
