### ISSUE TITLE
Hide issue_assigned in new issue

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#119]
Hi,
I have a proble that I can't resolve.
I can hide the Assigned field when the issue its create with this code:
$(function() {

    

                // Borramos usuarios sueltos, dejando solo grupos
                $('#issue_assigned_to_id>option:not([value=""])').remove();
                // Ocultamos "Assign to me" link
                $('a.assign-to-me-link').remove();
                // ocultamos el campo completo
                $('#issue_assigned_to_id').parent().hide();

})

but I can't hide when I create a new issue.
I need to hide the field when I create a new issue and after assign depending the tracker, but the code run ok after the issue was created.

Any solution with this problem?

thank you in advance for the suport and for the very good plugin

**Comment by jlsblasco** [comment]
Now I explain the problem in more detail:
I can hide the Assigned field in new task in the default page, but if I select other  tracker in the tracker list, the field is vissible. 
I need to hide always the Assigned field.
I don't know if now its more understandable.
Regards

**Comment by onozaty** [comment]
What is the Insertion position selected?
"Bottom of issue form" would make it run again if the tracker is changed.

> https://github.com/onozaty/redmine-view-customize#add
> "Bottom of issue form"
> Issue input fields are reconstructed when trackers or statuses are changed. If "Bottom of issue form" is specified, it will be executed again when reconstructed.


Thanks.

**Comment by jlsblasco** [comment]
Hi again,
Attach two video files, 
* the code with Head of all pages position, run ok the code but when change the tracker don't hide
* the same code with Botton of issue form, not hide the field.
The code executed:
************************************
$(function() {

const field = ViewCustomize.context.project.customFields.find(x => x.id == 148);
const contrato= (field == undefined) ? undefined : field.value;


$('#content').prepend('<div class="warning">El Lote 2 no admite imputaciones de Presupuesto a   '  + contrato + '. Por favor modifique la selección.</div>');

if ( contrato == "PAD-2023") {
    $('#content').prepend('<div class="warning">Hoy es el último día de entrega prevista.</div>');
 $('#issue_assigned_to_id>option:not([value=""])').remove();
          $('#issue_assigned_to_id').val('415');
          $('#issue_assigned_to_id').parent().hide();
                                                 }
        
                   });
*****************************
Thank you in advance

https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/274194f6-92ce-4349-a8cb-6d8ebab721e0


https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/7f6cecb2-91a1-41a6-a463-a8557cfb453f

**Comment by onozaty** [comment]
Sorry, I don't understand why it doesn't work.
Could you please give me a capture of the View customize configuration screen so I can see the path pattern as well?

**Comment by jlsblasco** [comment]
Hi,
Include a printscreen


![imagen_2023-05-19_144033107](https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/d10d1f3f-4e7d-4322-94a4-ce902a46ce1d)

Regards

**Comment by onozaty** [comment]
If you select Bottom of issue form, could you try leaving the Path pattern blank?
Bottom of issue form is only embedded in the issue screen, so the path pattern is not necessary.

If it still doesn't work, can you try the following code for a test. Insertion Postion is Bottom of issue form.

```javascript
alert('Bottom of issue form');
```

**Comment by jlsblasco** [comment]
Hi,
Dont' work. 
this is a print screen
![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/e958708a-31a5-438c-bdcf-4b9fba543a27)

Only work with Insertion position in 'Head of all pages', but when select other tracker in the issue the message don't refresh. 
It's the same case  of the first video.

**Comment by onozaty** [comment]
Thanks for the information.

Could you please check to see if there is an error on the browser when you use the Bottom of Issue form?
You can check from DevTools in your browser.

I am assuming that there is an error on the way and the process is not being executed.

**Comment by jlsblasco** [comment]
Hi again,
I disabled all view customized and only enabled the test view customized and run ok.
I review other views and the mistake are in this:
![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/e15d347f-78da-47a9-a7e0-454f46afc111)

![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/ccccb9f2-b97d-40eb-9174-96f115c4c911)

The mistake is in other view customized when I take the tracker :
const tipoPeticion= $('div.issue').attr('class').match(/tracker-([0-9][0-9])+/)[1] ;

but If I change the <html>
<body>


Insertion position | Bottom of issue form
-- | --



</body>
</html>

for

<html>
<body>


Insertion position | Bottom of issue detail
-- | --



</body>
</html>

in the mistake view customized , all the process its ok.

Why?

Regards

**Comment by onozaty** [comment]
In the new screen, I think there is an error because there is no corresponding element.
"Bottom of issue detail" will not be embedded in the new screen.

Thanks.

**Comment by jlsblasco** [comment]
thank you very much for your excellent help
Regards
