### ISSUE TITLE
Change Due-Date based on Custom Field

### ISSUE THREAD

**Issue by ieseberri** [onozaty/redmine-view-customize-scripts#12]
Hello !

I have a custom field called frequency (months,  number) and I want to define the issue due-date as function of issue start-date+frequency.

I want issue due-date get instantly updated if you change issue start-date or frequency.

Can you help me? Is there an easy way?

Lot's of thanks!!!!

**Comment by onozaty** [comment]
I think that it can be done with view customize.
I think that date calculation will be done with JavaScript.

**Comment by ieseberri** [comment]
Thank you!

Finally I was able to do what I need...

  $('#issue_custom_field_values_88').change(function(e) {
     var fechainicio = stringToDate($('#issue_custom_field_values_89').val(),"yyyy-MM-dd","-");   
     var fechafin= fechainicio.setMonth(fechainicio.getMonth()+Number($('#issue_custom_field_values_88').val()));
     //alert(formatDate(fechafin));

     $('#issue_custom_field_values_90').val(formatDate(fechafin));
     //$('#issue_start_date').val(formatDate(fechainicio));
     //$('#issue_due_date').val(formatDate(fechafin));
  });
