### ISSUE TITLE
Gantt default start date

### ISSUE THREAD

**Issue by formigadiablo** [onozaty/redmine-view-customize-scripts#122]
Good afternoon,
It will be amazing to set the default Gantt chart date as the start date of the project (earliest issue). I have been looking to do it through the core code of Redmine in /lib/redmine/helpers/gantt without much success. I do not know if it will be possible to do it in javascript but I think it is a feature Redmine requires.

Thanks for your time.

AF

**Comment by onozaty** [comment]
I don't think it is possible to take information from the oldest Issue, so it would be difficult with View customize.

Thanks.
