### ISSUE TITLE
Change the color of the ticket list according to the date of the custom field

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#123]
**thx for your lovely plugin**
depend in examples
https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0032.display_warning_3days_before_due_date/example.md

https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0016.change_font_of_issue_list_by_custom_field/example.md

how i can change color the issue list depend in current-date with cf_1 if cf_1 type date
like if the nowdate > cf_1
color red
if nowdate< cf_1
color orange
```
$(function() {

  const dateCustomField = $('#issue_custom_field_values_1');     // format: date
  const now = new Date();
  const nowDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());

  if (nowDate >= dateCustomField) {

 $('table.issues td.cf_1')
    .filter(function() {
      return $(this).text() == 'A';
    })
    .parent()
    .css({
      'font-weight': 'bold'
   }
});
```

**Comment by onozaty** [comment]
Do you want to change the color of the text in a custom field?

**Comment by ashrafalzyoud** [comment]
i need change in issue list when nowdate > cf_1
color the line red
now date< cf_1
color orange

**Comment by onozaty** [comment]
I wrote a sample that changes the background color according to the value of the date custom field in the issue list.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0059.change_color_of_issue_list_by_date_custom_field/example.md

Please use this code as a reference for your writing.

Thanks.

**Comment by ashrafalzyoud** [comment]
thanx for your quick responce
im try your solution  but not work with me
![date](https://github.com/onozaty/redmine-view-customize-scripts/assets/50211455/b99553c8-5d90-4ccc-aa62-89c82bbe6321)
i think its compare between days not as date

**Comment by onozaty** [comment]
This is only a sample and I was hoping that you could modify it to suit your application.

Modified the sample to change colors in the past and future.
Modify it to suit your application.

**Comment by ashrafalzyoud** [comment]
Look to the pic 
It's background pink the dates not ‹ now date
It's must pink from line3 to end
Thanx

**Comment by onozaty** [comment]
Since the date display format changes depending on the user language, it must be adjusted to match the language used.
If you want to adapt it to your language, I think it will work if you change it as follows

```diff
-const date = new Date(str);
+const date = jQuery.datepicker.parseDate('dd/mm/yy', str);
```

However, this language can be changed on a per-user basis, so if a user is using another language, it will not work.
It is impossible to support all languages.

Thanks.

**Comment by ashrafalzyoud** [comment]
perfect perfect @onozaty 
thats nice feature 
thx for u

**Comment by ashrafalzyoud** [comment]
THX FOR YOUR ANSWERS
but
how i can added if status open changes color if not no change color
thanks @onozaty

**Comment by ashrafalzyoud** [comment]
```
$(function() {

  const now = new Date();
  const nowDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());

  $('table.issues td.cf_398').each(function() {
    const target = $(this);
    const str = target.text();
    if (str === '') {
      return;
    }

    const date = jQuery.datepicker.parseDate('dd/mm/yy', str);
    const statusid = $('#issue_status_id').val();
    if (date > nowDate && (statusid=='41'||statusid=='26'||statusid=='42'||statusid=='78'||statusid=='79'||statusid=='80'||statusid=='71')) {
      target.parent().css({ 'background-color': 'red' });
    } else if (date < nowDate) {
      target.parent().css({ 'background-color': 'yellow' });
    }
  });
});
```
im try this code but not working

**Comment by onozaty** [comment]
You can get the status name below, so please try that.

```javascript
const statusText = target.parent().find('.status').text();
```

You can also do this by experimenting with DevTools in your browser.


Thanks.
