### ISSUE TITLE
View customize script to restrict form submission when status changed.

### ISSUE THREAD

**Issue by SHNev** [onozaty/redmine-view-customize-scripts#124]
Hello onozaty, Thanks for your Support.

While filling a issue form, in Status drop down I have two values (1. in progress, 2. Completed). When I am updating an issue form status to "Completed" from "In progress", form should make Attachment compalsary to attach file related issue. And if user forgot to attach any file, then while submitting form, popup or error msg must be there saying "please attach the file" 
If status is "in progress" then form must get submitted without any error.

**Comment by SHNev** [comment]
I tried today regarding this issue. But I didn't get any positive results. Please Can you help me with a possible javascript.

**Comment by onozaty** [comment]
Hi @SHNev 

I have written a sample code.
Please refer to the following.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0060.require_attachments_when_changing_status_closed/example.md

Thanks.

**Comment by SHNev** [comment]
You are great, 
This will fulfill my requirement.
Thanks Onozaty 😊
