### ISSUE TITLE
Sorting of custom fields

### ISSUE THREAD

**Issue by TiniRED** [onozaty/redmine-view-customize-scripts#125]
Hi onozaty,

first many thanks for your Code examples for "Redmine View Customize Plugin"](https://github.com/onozaty/redmine-view-customize-scripts#code-examples-for-redmine-view-customize-plugin).
Realy wonderful, we are using several of them. :)
Have you ever seen a plugin or script for better overview in the custom fields area? (administration -> custom fields)
In my Redmine database, I have >250 custom fields, using them in different projects and trackers. They are just sortet up and down by drag and drop, but nevertheless it is a long list. I would need a sorting by projects, but I did not get any answer in Redmine forum or with a Redmine ticket (feature request). If you have ever seen an idea or helpful script or plugin, could you please share a link with me?

It would be highly appreciated. 
Many thanks
TiniRED

**Comment by onozaty** [comment]
Hi @TiniRED 

I could not find a plugin that sorts by project.
It is also difficult with the View customize plugin.
Sorry I can't help you.

Thanks.
