### ISSUE TITLE
How to hide New in a project level ?

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#126]
Hi 
I need you support because I need to hide a new issue option in  a general level, not inside a project.
I review the example in https://github.com/onozaty/redmine-view-customize-scripts/issues/41 , but only hide when the user are inside a project, but if the user are in the' projects/issues/new issue' the New issue button don't hide.
attach printscreen 
![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/e3aa8d0b-dd06-4bc8-834e-3440e26b442e)

The New issue button inside the project page must continue to appear.

Thank you in advance.

**Comment by onozaty** [comment]
Hi @jlsblasco 

Sorry, could you be more specific about what you would like to do?
Also, please let me know what code you just tried.

Thanks

**Comment by jlsblasco** [comment]
Hi @onozaty 
thank you for you quick response.
I don't execute code, but I need to hide the 'New issue' button in a general page. 
When I click in Project tab in a menu :
![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/465ee1bf-9579-4c77-a0fe-b4ed6f51a796)

Next I click in Issues
![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/d347e632-60f3-4e31-b6f1-2251647bce5d)

I need to hide the  'New issue' button
![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/af0dc5d6-45d0-4a2e-b942-6b74579b272a)


Do not confuse with 'new issue' when I am within a project.
When I am inside a project the 'New issue' button must be exist.

![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/3b43173b-a6dc-4ab9-8e58-c2d8ca5f5e5c)

In this case, the 'New issue' must be exist, because the user are inside a project.
I review the example in https://github.com/onozaty/redmine-view-customize-scripts/issues/41 , but only hide when the user are in a project, and this case is not correct for me.

Regards and thank you very much.

**Comment by onozaty** [comment]
Hi @jlsblasco 
You can hide the screen by specifying the screen you want to hide in the Path pattern and specifying it in the CSS.

### Path pattern

`^/issues$`

### Insertion position

Head of all pages

### Type

CSS

### Code

```css
a.new-issue {
  display: none;
}
```

![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/47337/7d9611cb-938e-4532-a3cc-b2c31c15b8c6)

## Result

![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/47337/b49527ae-bdf5-49a1-9022-1fe90f0077ce)

![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/47337/ff815528-1061-4841-af4e-34bee6d7c15c)

**Comment by jlsblasco** [comment]
Hi @onozaty,

thank you so much. I test and I can hide now.
You are the best.
Regards
