### ISSUE TITLE
 strange functioning with filters

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#127]
Hi,
 I have a strange case.
I have this code:
$(function() {

        const field2 = ViewCustomize.context.project.customFields.find(x => x.id == 55);
        const area = (field2 == undefined) ? undefined : field2.value;

        var miestado=$('#issue_status_id').val();
        if (miestado == "1" ) {

        $('#issue-form input[type="submit"]').on('click', function(event) {

        var tipoPeticion = $('#issue_tracker_id').val();
        var tipoPeticion = $('#issue_tracker_id').val();
        var medida = $('#issue_custom_field_values_139 > option:selected').text();
        //var presupuesto = $('#issue_custom_field_values_175 > option:selected').text();
        const presupuesto = $('input[name="issue[custom_field_values][175]"]:checked').val();

        switch(tipoPeticion) {
......
                                } // de switch
                        }); // de function(event)

        } // del ef inicial miestado
}); // de function()
-------------------

Path pattern  -> empty
 
Head of all pages -> empty
----
the code run ok , but when I execute the filters in the issues option, the filters not included. Attach printscreen
![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/892c3580-1b3d-43e8-b60f-bfe502c4f48c)

The problem its with the code of the Javascript, and with two lines:
        **_const field2 = ViewCustomize.context.project.customFields.find(x => x.id == 55);
        const area = (field2 == undefined) ? undefined : field2.value;_**

If I eliminate the files, the code don't run but the filters run ok.

I need to receive this field. The field its a custom field of the projects.

Any idea?
If you need more information, tell me.

Thank yoy in advance

**Comment by onozaty** [comment]
Hi @jlsblasco 
Sorry, could you be more specific about what you would like to do?

Thanks

**Comment by jlsblasco** [comment]
Hi @onozaty 
I'm sorry for my bad explanation earlier.
My code:
"
$(function() {


        const field2 = ViewCustomize.context.project.customFields.find(x => x.id == 55);
        const area = (field2 == undefined) ? undefined : field2.value;

        var miestado=$('#issue_status_id').val();
        if (miestado == "1" ) {


        $('#issue-form input[type="submit"]').on('click', function(event) {

        var tipoPeticion = $('#issue_tracker_id').val();
        var tipoPeticion = $('#issue_tracker_id').val();
        var medida = $('#issue_custom_field_values_139 > option:selected').text();
        //var presupuesto = $('#issue_custom_field_values_175 > option:selected').text();
        const presupuesto = $('input[name="issue[custom_field_values][175]"]:checked').val();


        switch(tipoPeticion) {
        case '45':
        case '47':
                if (area == "SERPER" || area == "EXTRAN" ) {
                if (medida == "0. Presupuesto ordinario" || medida == "M. MPT" ) { alert('El Lote 4 en las áreas SERPER y EXTRAN no admite imputación a presupuesto Ordinario ni MPT, seleccione Periferia o Medida Plan Digitalización, por favor, modifique la selección'); return false;}
                        //alert('Tracker:   ' + tipoPeticion + '  Custom field Medida Plan Digitalizacion : ' +  area);
                                                         }
                if (area == "SIGP" || area == "SERHOR" || area == "FUNAUT" || area == "CP"  ) {
                if (medida == "P. Periferia" || medida == "M. MPT" ) { alert('El Lote 4 en las áreas SIGP,SERHOR,CP y FUNAUT no admite imputación a Presupuesto Periferia ni MPT , por favor, modifique la selección'); return false;}
                        //alert('Tracker:   ' + tipoPeticion + '  Custom field Medida Plan Digitalizacion : ' +  area);
                                                         }
          break;

       case '46':
                if (area == "SERPER" || area == "EXTRAN" ) {
                if (presupuesto == "Ordinario" || presupuesto == "MPT" ) { alert('El Lote 4 en las áreas SERPER y EXTRAN no admite imputación a presupuesto Ordinario ni MPT, seleccione Periferia, por favor, modifique la selección'); return false;}
                                                         }
                if (area == "SIGP" || area == "SERHOR" || area == "FUNAUT" || area == "CP"  ) {
                if (presupuesto == "Periferia"  || presupuesto == "MPT" ) { alert('El Lote 4 en las áreas SIGP,SERHOR,CP y FUNAUT no admite imputación a Presupuesto Periferia ni MPT, por favor, modifique la selección'); return false;}

                                                         }
          break;


                                } // de switch
                        }); // de function(event)

        } // del ef inicial miestado
}); // de function()
"
The code run ok, but have an effect in filters. If I enabled the code, when I add filter in the issue tab, filter is not added to selection.
![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/39d81113-e791-48ce-97a3-ec3157c35f05)


The problem is with the two lines in the code:
const field2 = ViewCustomize.context.project.customFields.find(x => x.id == 55);
const area = (field2 == undefined) ? undefined : field2.value;

If I eliminate the files, the code don't run but the filters run ok.

I need to receive this field. The field its a custom field of projects.

If I limit the code to:

Path pattern = /issues/[0-9]+\|/projects/.+/issues/new\|/projects/.+/issues

The problem its solved and the filters run ok becasue the code don't have impact in filters page.
But I don't know where its the problem.
Thank you in advance

**Comment by onozaty** [comment]
Hi @jlsblasco 

If Add Filter is not working, then I think there is some error.
Could you check your browser's DevTools to see if there is an error?

Thanks.

**Comment by jlsblasco** [comment]
Hi @onozaty,
I test again and now the problem don't exist.
Its possible  I that had a conflict with another process.
Sorry for writing to you for no reason.
Regards
