### ISSUE TITLE
Limit values in list custom field with the selected values in a parent custom list field.

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#129]
Hi onozaty,

I have a problem that I don't know how to resolve.
I have resolve the problem that custom values in custom field list in issue depending of the values of custom field in project, with the example
Control custom field choices in issue with custom field in project
Thank you so much for you support.

Now , I have a new custom list field in issue and I need only show the values depending of the values of the parent custom list field.

An example:

Parent custom list field:
![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/fb4ba4fa-de9b-45b5-8388-0f405ce6fa4f)
Categoria field have 6 values

Child list field:
![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/3ce9c50d-353b-47bf-b804-bee298b0eb50)
Subcategoria have some values.

I need that when I select the value 'Modelo de calidad' en parent custom list field, only display in Subcategoria the values:
'Buenas Practicas de Calidad'
'Definicion de Politicas de Calidad'
In other parent values need others diferent child values.
In other parent values I need to hide the Subcategoria child field, because don't have child value por this parent value.

It's possible that I don't explain correctly, if you need more information, tell me.
Your help would be of great value to me.

Thank you in advance.

**Comment by jlsblasco** [comment]
Hi again, 
I have resolve the hide field of child list custom field, but I don't know how to show only the unique values in the child for each parent. My code now:
$(function() {


// 178 = parent custom list field
// 179 = child custom list field

// VEMOS EL VALOR DEL CAMPO CUANDO EDITAMOS UNA TAREA PARA OCULTAR CAMPOS
const medidaActual = $('#issue_custom_field_values_178').val();
if ( medidaActual == "Implementación de Piloto" || medidaActual == "Estrategia para la Implantación Modelo de Calidad" || medidaActual == "Preparación para la implantación del Modelo de Calidad" || medidaActual == "Validación de la Calidad" ) {
        var targetCustomFieldId = '179';
        var targetCustomFieldInput = $('#issue_custom_field_values_' + targetCustomFieldId);
        var targetCustomFieldDisplay = $('div.cf_' + targetCustomFieldId + '.attribute');
        targetCustomFieldInput.parent().hide();
        targetCustomFieldDisplay.hide();

 }



// OCULTAMOS AL VUELO CUANDO SELECCIONAMOS LOS VALORES DE LA LISTA

  $('#issue_custom_field_values_178').on('change', function() {

    switch($('#issue_custom_field_values_178').val()) {
      case 'Implementación de Piloto':
      case 'Estrategia para la Implantación Modelo de Calidad':
      case 'Preparación para la implantación del Modelo de Calidad':
      case 'Validación de la Calidad':
        var targetCustomFieldId = '179';
        var targetCustomFieldInput = $('#issue_custom_field_values_' + targetCustomFieldId);
        var targetCustomFieldDisplay = $('div.cf_' + targetCustomFieldId + '.attribute');
        targetCustomFieldInput.parent().hide();
        targetCustomFieldDisplay.hide();


        break;

      default:
         var targetCustomFieldId = '179';
        var targetCustomFieldInput = $('#issue_custom_field_values_' + targetCustomFieldId);
        var targetCustomFieldDisplay = $('div.cf_' + targetCustomFieldId + '.attribute');
        targetCustomFieldInput.parent().show();
        targetCustomFieldDisplay.show();


    }
  });
});

**Comment by onozaty** [comment]
Hi @jlsblasco 

The following may be helpful.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0007.link_custom_fields/example.md

Try changing the condition of the isTarget function.

Thanks.

**Comment by jlsblasco** [comment]
Hi @onozaty

you are my hero one more time.

I adapt the isTarget function and now is a very,very good solution for me.

Thank you so much for you incredible support.

Regards
