### ISSUE TITLE
Custom Javascript on new issues

### ISSUE THREAD

**Issue by ieseberri** [onozaty/redmine-view-customize-scripts#13]
Hello Mr.Onozaty,

I'm trying to run this code without success... I can create text and labels using

`<h3>1.Identificación333333</h3>`

but I'm not able to move/append objects.

Please, can you help me?

Thank you!

>Path pattern: | /issues/new
>JavaScript
```

$(function() {
$('#all_attributes').change(function(e) {
  if (e.target.id == 'issue_tracker_id') {
    setDefalutValue();
  }
});


// IDENTIFICACION
var ID_UBICACION_FISICA = $('.cf_9.attribute');  
var ID_SECTOR = $('.cf_11.attribute'); 
var ID_UBICACION_TECNICA = $('.cf_12.attribute'); 
var ID_APARATO = $('.cf_13.attribute'); 
var ID_DESCRIPCION = $('.cf_14.attribute'); 
```
```

var ID_UBICACION_FISICA_ED = $('#issue_custom_field_values_9').parent();
var ID_SECTOR_ED = $('#issue_custom_field_values_11').parent();
var ID_UBICACION_TECNICA_ED = $('#issue_custom_field_values_12').parent();
var ID_APARATO_ED = $('#issue_custom_field_values_13').parent();
var ID_DESCRIPCION_ED = $('#issue_custom_field_values_14').parent();
```

```
alert($('#issue_tracker_id').val());
  var setDefalutValue = function() {
    switch($('#issue_tracker_id').val()) {
      case '7': // PSV
			alert('Issue Type PSV');
                        // IDENTIFICACION EDIT
                        //$('#attributes').closest(".splitcontent").after($('<div id="IDER" class="splitcontent">'));
                        $('#attributes').after($('<div id="IDER" class="splitcontent">'));
                        $('#IDER').css("background-color","#B0F2C2");
                        $('#IDER').append($("<p><h3>1.Identificación333333</h3><hr style='background-color: black; height:2px'></p>"));
                        $('#IDER').append($('<div id="IEL" class="splitcontentleft">'));
                        $('#IDER').append($('<div id="IER" class="splitcontentright">'));
                        $('#IEL').append(ID_UBICACION_FISICA_ED);
                        $('#IER').append(ID_SECTOR_ED);
                        $('#IEL').append(ID_UBICACION_TECNICA_ED);
                        $('#IER').append(ID_APARATO_ED);
                        $('#IER').append(ID_DESCRIPCION_ED);
      break;


      case '8': // PSV_TARADO

			alert('Issue Type PSV_Tarado');
                        // IDENTIFICACION EDIT
                        $('#issue_status_id').closest(".splitcontent").after($('<div id="IDER" class="splitcontent">'));
                        $('#IDER').css("background-color","#B0F2C2");
                        $('#IDER').append($("<p><h3>1.Identificación333333</h3><hr style='background-color: black; height:2px'></p>"));
                        $('#IDER').append($('<div id="IEL" class="splitcontentleft">'));
                        $('#IDER').append($('<div id="IER" class="splitcontentright">'));
                        $('#IEL').append(ID_UBICACION_FISICA_ED);
                        $('#IEL').append(ID_SECTOR_ED);
                        $('#IEL').append(ID_UBICACION_TECNICA_ED);
                        $('#IER').append(ID_APARATO_ED);
                        $('#IER').append(ID_DESCRIPCION_ED);
        break;
    }
  }
  setDefalutValue();
});

```

**Comment by onozaty** [comment]
Hi @ieseberri 

What will not be added is only `<h3>1.Identificación333333</h3>`?

**Comment by ieseberri** [comment]
No, sorry. The h3 can be deleted. My idea is sort the custom fields grouping them in different subjects. The problem is when it runs this code the fields are not arranged. If I use this code for editing issues it works without problems.

**Comment by ieseberri** [comment]
In my example h3 is the subject under I want to group the fields.

**Comment by onozaty** [comment]
> The problem is when it runs this code the fields are not arranged.

Could you tell me in a bit more detail what part you want to change?
Can you get screen captures?

**Comment by ieseberri** [comment]
Hello,

I've created two different pieces of code, the first (Edit.txt) is Javascript with Path pattern: /issue, and generates this output:

![imagen](https://user-images.githubusercontent.com/32834927/33563263-b99ec9ea-d917-11e7-8b92-5f2f6cafba26.png)

The second one is called (Edit New.txt) is Javascript with Path pattern: /issues/new, and generates this output:

![imagen](https://user-images.githubusercontent.com/32834927/33563338-f5d38e14-d917-11e7-979b-b0f49d2dbad1.png)

I want to have the same presentation (Edit) for both types of issues Normal Edit or New Issue.

Thank you!!!

[Edit.txt](https://github.com/onozaty/redmine-view-customize-scripts/files/1527874/Edit.txt)
[Edit New.txt](https://github.com/onozaty/redmine-view-customize-scripts/files/1527875/Edit.New.txt)

**Comment by onozaty** [comment]
Sorry.
The code was too big to understand where the problem was.

Is there an error in the browser console?

**Comment by ieseberri** [comment]
## **First of all thank you for your time!!!!**

There is no error in the browser console.  I send you back the **needed** (I've deleted all unnecesary lines) code to understand the problem. 

The problem is that I'm trying to arrange fields in issue forms. I'm able to arrange the field (CF_9) when view **Existing Issue**, 

![imagen](https://user-images.githubusercontent.com/32834927/33725946-f8c569f4-db73-11e7-904a-cb5bc77942a0.png)

or even editing the same **Existing Issue**

![imagen](https://user-images.githubusercontent.com/32834927/33725990-114378c2-db74-11e7-9339-5319346f6eab.png)

but when I try to do the same with a **New Issue** I'm not able to move the CF_9 (custom field 9).

![imagen](https://user-images.githubusercontent.com/32834927/33725903-dcc66dc0-db73-11e7-8861-851103839660.png)

Thank you!

## **Path pattern: /issue**
[Edit.txt](https://github.com/onozaty/redmine-view-customize-scripts/files/1539769/Edit.txt)

## **Path pattern: /issues/new**
[Edit New.txt](https://github.com/onozaty/redmine-view-customize-scripts/files/1539775/Edit.New.txt)

**Comment by onozaty** [comment]
In `Edit New.txt`, is not because the` setDefalutValue` method is never called?

**Comment by ieseberri** [comment]
No, **setDefalutValue** is called everytime the user selects the active tracker.

```
$('#all_attributes').change(function(e) {

        if (e.target.id == 'issue_tracker_id') {

          setDefalutValue();
        }
});
```
The problem is that when it executes the setDefalutValue function it doesn't runs as it does in Edit.txt file.

Thank you.

**Comment by ieseberri** [comment]
It seems there is an issue connected with page load process. Is there any way to execute the javascript after a complete load page?

**Comment by ieseberri** [comment]
I've solved the problem. I have defined the variables inside the switch an arranged the code following one your others examples.

```
$(function() {
var setDefalutValue = function() {

    switch($('#issue_tracker_id').val()) {

      case '7': // PSV
               
                // IDENTIFICACION EDIT

               var ID_UBICACION_FISICA = $('.cf_9.attribute');  
               var ID_UBICACION_FISICA_ED = $('#issue_custom_field_values_9').parent();

                $('#attributes').after($('<div id="IDER" class="splitcontent">'));
                $('#IDER').css("background-color","#B0F2C2");
                $('#IDER').append($("<p><h3>1.Identificación333333</h3><hr style='background-color: black; height:2px'></p>"));
                $('#IDER').append($('<div id="IEL" class="splitcontentleft">'));
                $('#IDER').append($('<div id="IER" class="splitcontentright">'));
                $('#IEL').append(ID_UBICACION_FISICA_ED);

      break;

    }
  }

setDefalutValue();

// catch change on dropdown list

$('#all_attributes').change(function(e) {

        if (e.target.id == 'issue_tracker_id') {

          setDefalutValue();
        }
});

  var _replaceIssueFormWith = replaceIssueFormWith;
  replaceIssueFormWith = function(html){

    _replaceIssueFormWith(html);
setDefalutValue();
    
};
    
});
```
Now I've the result I was looking for:

![imagen](https://user-images.githubusercontent.com/32834927/33809948-d57c027c-ddfe-11e7-9f08-aee83946912e.png)

Thank you!
