### ISSUE TITLE
How can I add a custom menu item in the Redmine top menu bar?

### ISSUE THREAD

**Issue by itnovativetp** [onozaty/redmine-view-customize-scripts#130]
I would like to know if I can use your plugin to create a custom menu item in the redmine top bar (div_id="top-menu").

Thanks in advance.
![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/97330991/ef3e0988-c852-49d3-93e7-776d8a6558be)

**Comment by onozaty** [comment]
Can be done. Please refer to the following.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0005.add_issues_link_on_header/example.md

Thanks.

**Comment by itnovativetp** [comment]
Thank you!
