### ISSUE TITLE
Show popup when spent-time exceeds estimated-hours field for issue

### ISSUE THREAD

**Issue by itnovativetp** [onozaty/redmine-view-customize-scripts#132]
Hi,
Is it possible to show a text popup "Time budget exceeded" when for an issue the spent-time exceeds the estimated-hours?
Both fields are shown in the issue page.

![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/97330991/271b59bf-69f8-4753-97b1-4e3827af2f26)

Many thanks in advance.

**Comment by onozaty** [comment]
When will the text popup appear?
Will it always be displayed on the Issue details screen?

For example

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0032.display_warning_3days_before_due_date/example.md

Thanks.

**Comment by itnovativetp** [comment]
Thanks for your quick response.
Yes a notification like the one in the example would be fine.

**Comment by onozaty** [comment]
Currently, there is no easy way to get total spent-time and total estimated-time, so I am not sure if I should modify the plugin itself.

Please give me a little more time.

**Comment by itnovativetp** [comment]
No problem, love your work take your time!

**Comment by onozaty** [comment]
Please refer to the sample code below.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0061.display_warning_exceeds_estimated_time/example.md

Thanks.

**Comment by itnovativetp** [comment]
Thank you so much, you are the best.
I am going to try it.

**Comment by itnovativetp** [comment]
I just wanted to add that this feature works perfectly! Thank you so much for changing your plugin to allow the use of this function. I am sure many users will like it!

**Comment by itnovativetp** [comment]
I closed the ticket.
