### ISSUE TITLE
カスタムフィールドのグルーピングに関する質問

### ISSUE THREAD

**Issue by yokohama-worker** [onozaty/redmine-view-customize-scripts#133]
onozatyさん年明け早々の質問で申し訳ありません。

当方品質分析を生業としておりbacklogやredmineでBTSを実施しているチケット等の分析を行なっているのですが
イケテナイ チケット項目が多く四苦八苦しており自らredmine&view-costmize pluginとBIツールを使ってBTSを構築しようと試みています。
構想はほぼ出来上がり構築を試みているのですが、java等の経験が一切なくview-costmizeでハマってしまい以下の質問にご回答をお願いします。

当方の環境・試行したソース及び実行結果等は添付のexcelファイルに纏めてします。

【質問したいこと】
(1)説明欄の表示位置を題名の下に常に展開して表示するにはどの様にすればよいでしょうか？
自分の実行結果では表示と編集画面で説明の位置が異なっておりしかも編集画面ではとじられている。説明欄を常に表示されている状態にしたいです。

(2)グルーピングはhttps://qiita.com/sioaji/items/e795ba158856cd84ffefを参考にさせていただいていますが、2017年3月に投稿されたもので、最近のRedmineｖ5では実現できないのでしょうか？

(3)onozatyさんのhttps://github.com/onozaty/redmine-view-customize-scripts/issues/27でjan   22,2020でコメントされている内容で
表示も編集画面も項目のグルーピングがされている認識ですが表示画面のカスタマイズの設定は必要ないのでしょうか
1)挿入位置は全画面のヘッダーで良かったでしょうかそれとも(3)のBottom   of issue formが正しいでしょうか？
2)java上の項目定義の順番はcustom_field_id順にしなければならないなどの制限はありますでしょうか
[質問内容.xlsx](https://github.com/onozaty/redmine-view-customize-scripts/files/13869913/default.xlsx)

**Comment by onozaty** [comment]
> 【質問したいこと】 (1)説明欄の表示位置を題名の下に常に展開して表示するにはどの様にすればよいでしょうか？ 自分の実行結果では表示と編集画面で説明の位置が異なっておりしかも編集画面ではとじられている。説明欄を常に表示されている状態にしたいです。
> 

編集のためのフォームと、表示のための項目は別物なので、表示状態で説明欄だけ編集状態というのは難しいと思います。

> (2)グルーピングは[https://qiita.com/sioaji/items/e795ba158856cd84ffefを参考にさせていただいていますが、2017年3月に投稿されたもので、最近のRedmineｖ5では実現できないのでしょうか？](https://qiita.com/sioaji/items/e795ba158856cd84ffef%E3%82%92%E5%8F%82%E8%80%83%E3%81%AB%E3%81%95%E3%81%9B%E3%81%A6%E3%81%84%E3%81%9F%E3%81%A0%E3%81%84%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%81%8C%E3%80%812017%E5%B9%B43%E6%9C%88%E3%81%AB%E6%8A%95%E7%A8%BF%E3%81%95%E3%82%8C%E3%81%9F%E3%82%82%E3%81%AE%E3%81%A7%E3%80%81%E6%9C%80%E8%BF%91%E3%81%AERedmine%EF%BD%965%E3%81%A7%E3%81%AF%E5%AE%9F%E7%8F%BE%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84%E3%81%AE%E3%81%A7%E3%81%97%E3%82%87%E3%81%86%E3%81%8B%EF%BC%9F)

Redmineのバージョンによって画面構成が変わっている場合は出来ない可能性があると思います。

こちらですぐに確認することができないので、View Customizeのスクリプトとして指定しているものが、HTML上に存在するかなど確認していただけると良いかと思います。(ブラウザのDevToolsなどを利用)

> 
> (3)onozatyさんの[https://github.com/onozaty/redmine-view-customize-scripts/issues/27でjan](https://github.com/onozaty/redmine-view-customize-scripts/issues/27%E3%81%A7jan) 22,2020でコメントされている内容で 表示も編集画面も項目のグルーピングがされている認識ですが表示画面のカスタマイズの設定は必要ないのでしょうか 1)挿入位置は全画面のヘッダーで良かったでしょうかそれとも(3)のBottom of issue formが正しいでしょうか？ 

Bottom of issue form は後から追加されたもので、それ以前はヘッダで、かつ入力フォームが置き換わった際にも動作するように下記のようなコードを入れておく必要がありました。

```js
  /* ステータス変更時など、DOMが差し替えられるたびに実施 */
  var _replaceIssueFormWith = replaceIssueFormWith;
  replaceIssueFormWith = function(html){

    _replaceIssueFormWith(html);

    changeCustomFieldPositon();
  };  
```

Bottom of issue formを使うことで、上記のような考慮が不要になるのですが、ヘッダで上記のようなやり方をしても問題ありません。

> 2)java上の項目定義の順番はcustom_field_id順にしなければならないなどの制限はありますでしょうか [質問内容.xlsx](https://github.com/onozaty/redmine-view-customize-scripts/files/13869913/default.xlsx)

項目定義によって変わるということは無いので、順番は問題ありません。

**Comment by yokohama-worker** [comment]
onozatyさん
　早速の返信ありがとうございます。
　申し訳ありません。
　追加でもう一つ質問させてください。
　編集画面と表示画面のグルーピングを分けた場合の表示画面の挿入位置は”チケット詳細の下”でよろしかったでしょうか。
　度々で申し訳ありませんが、よろしくお願いします。

**Comment by yokohama-worker** [comment]
ご回答ありがとうございました。本件クローズさせていただきます。

**Comment by onozaty** [comment]
もしうまくいかないなどあれば、またご連絡ください。

時間取れたらですが、、、最新のRedmineで表示、編集状態でのカスタムフィールドのグルーピングのサンプルを書けたらと思っています。

**Comment by yokohama-worker** [comment]
いろいろ格闘した結果グルーピング表示と編集設定出来ました。
　質問時に送付したソースがひどかった（聞く以前の問題でした）
　もう少しJavaの知識を蓄えて質問するようにします。

**Comment by yokohama-worker** [comment]
onozatyさん 1件質問させてください。
　カスタムフィールドのグルーピングの表示・編集のカスタマイズを全画面の下に設定する方法で設定しています。
　チケットを選択して表示・編集することは問題ないく出来るのですが、
　新しいチケットをオープン（test1画像）してトラッカーを変更する(test2画像）と変更したトラッカーの入力画面下部に変更前の入力画面が表示されてしまいます。
　変更後のトラッカーのカスタイズに初期化の処理を入れれば良い様に思えるのですが、javaの知見が乏しいため
　どの様にすればよいか分かりませんので、教えていただけないでしょうか
　よろしくお願いいたします。
　
![test1](https://github.com/onozaty/redmine-view-customize-scripts/assets/156047401/a6e8d3e8-4d6a-4120-a2d7-62b3cf8da4a4)

![test2](https://github.com/onozaty/redmine-view-customize-scripts/assets/156047401/75c4d12f-e1f0-445d-b108-4ea4a8869ead)

[UTバグ表示編集_Viewcustomize.txt](https://github.com/onozaty/redmine-view-customize-scripts/files/14400344/UT._Viewcustomize.txt)

**Comment by onozaty** [comment]
トラッカーを変更すると、`#all_attributes`内がトラッカーに応じたものに差し変わります。
これを考慮して、下記のような処理で再度実行するようにしています。

```js
    /* ステータス変更時など、DOMが差し替えられるたびに実施 */
    var _replaceIssueFormWith = replaceIssueFormWith;
    replaceIssueFormWith = function(html){
      _replaceIssueFormWith(html);
      changeCustomFieldPositon();
    }; 
```

ただ、今回の方法だと、`#all_attributes` の外に各項目を移動してしまっているので、`#all_attributes` が差し変わっても、移動先のものはそのまま残ってしまいます。

移動先を `#all_attributes` の中にすれば、消えるようになると思いますので、`$('#all_attributes').after()`としているところを、`$('#all_attributes').append()`に変えてみていただけないでしょうか。

**Comment by yokohama-worker** [comment]
早速のご回答ありがとうございました。
　ご指摘の修正で問題なく表示できました。
　　もう少し小文字の言語の理解を深めたいと思います。

**Comment by yokohama-worker** [comment]
クローズさせていただきます。
