### ISSUE TITLE
Don't work if I change tracker

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#134]
Hi @onozaty , I hope that you are very well.
In the task https://github.com/onozaty/redmine-view-customize-scripts/issues/129 you resolve my problem. but the problem don't work when I chage the tracker in the form.
The code:
(function() {

  // Note: Change the ID according to the custom field you want to target.
  var parentFieldId = 'issue_custom_field_values_214';
  var childFieldId = 'issue_custom_field_values_215';

  var isTarget = function(child, parent) {
    var parent2 = parent.val().substring(0,3);
    var child2 = child.val().substring(0,3);
    if (child2 === parent2) {
      // Unselect is always target
      return true;
    }

    // forward match
    return child.text().indexOf(parent.text()) == 0;
  }

  var narrowChildField = function() {

      var parentSelected = $('#' + parentFieldId + ' > option:selected');

    $('#' + childFieldId + ' > option').each(function() {

      var child = $(this);

      // Narrow down by match.
      // (In IE, option is not hidden by "display:none", so "disabled" it to make it unselectable.)

      if (isTarget(child, parentSelected)) {
        child.show();
        child.prop('disabled', false);
      } else {
        child.hide();
        this.selected = false;
        child.prop('disabled', true);
      }
    });
  }

  $('#' + parentFieldId).on('change', narrowChildField);

  narrowChildField();

});
-----------------------
Position: Head of all pages.

The code show the values in the field 215 with the three first position of the selected in field 214.
the values in the field 214 are:
001 Modelo de calidad
002 Catálogo de Servicios y Aplicaciones
110 Consultoría
...
and in the 215:
00101 Diseño del Modelo de calidad
00102  Políticas de calidad
00103 Buenas prácticas de calidad
00104 Procesos, procedimientos y flujos
00105 Implementación  herramientas
00201 Modelo de datos
00202 Construcción
11000 Preparación

This code run ok when I put 'New issue'  in the default tracker  in the form.
When I select other tracker, the code don't run  and show all the values in field 215 not only the filtered in the 214.
I think that its correct because the position is 'Head of all pages', but if I select 'Botton of issue form' or the other values the code never run. 
What's happen?
I don't know how to solve it.

Regards and thank you in advance

**Comment by jlsblasco** [comment]
Hi again,
I test to disable all view customize jobs and only enable this job and run in 'Botton on issue form' mode.
I'm sure that i have a conflict with other job.... I'm going to revise it.

**Comment by jlsblasco** [comment]
I resolve it the problem, there are a conflict with other job.
I close the ticket.
Sorry for the inconvenience.
Regards

**Comment by ebergu78** [comment]
@jlsblasco por qué no funciona (no se ocultan las opciones) cuando el campo personalizado tiene Display: checkboxes?
