### ISSUE TITLE
How to setup new html view for issue detail page for particular tracker 

### ISSUE THREAD

**Issue by pravindodia** [onozaty/redmine-view-customize-scripts#135]
I have a distinct project called "portfolio," and I've set up a dedicated tracker named "profile" for it. I'm looking to customize the Detail View of this profile tracker to make it function as a personalized profile. I successfully modified the CSS to achieve the desired look, but I'm unsure about how to provide an HTML template for the page. Any guidance would be appreciated.

**Comment by onozaty** [comment]
Is it correct that you want to apply the CSS you have prepared for a specific tracker?

**Comment by pravindodia** [comment]
> Is it correct that you want to apply the CSS you have prepared for a specific tracker?

Yes and No , Yes because I want to apply the css on specific tracker , but at the same time I want to change the HTML View as well for that particular tracker. For example, I want to give standard Issue detail view a different look (UI).  I hope I am able to explain the issue, please let me know if you need more info.

**Comment by onozaty** [comment]
First, CSS can be applied to a specific tracker by specifying the tracker ID as the class name in the following manner.

![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/47337/324ab48c-51e8-45ae-a52e-f926f6cf548e)

However, if this is not possible with CSS alone, it must be written in JavaScript.
In that case, Type would be set to JavaScript, and the class of the tracker ID would be checked to see if it exists and applied.

Thanks.

**Comment by pravindodia** [comment]
How about the html I asked for ?

**Comment by onozaty** [comment]
View customize customizes the screen by embedding CSS and JavaScript into the screen.
Therefore, it cannot do more than that.

If you want to change the HTML, you have to try your best with JavaScript, but I don't even know if what you expect is something that can be achieved with JavaScript.

Thanks.

**Comment by pravindodia** [comment]
I understand that I need to create JS and CSS but there is an option in type selection of view customize 
<img width="823" alt="image" src="https://github.com/onozaty/redmine-view-customize-scripts/assets/12298932/b0e28792-4485-4fe9-83b0-11db12aa06cf">

I am not sure how to use that and what its for if not the case I am looking for.
Please help if possible, 
Thanks
Pravin Dodia

**Comment by onozaty** [comment]
View customize allows you to insert CSS, JavaScript, and HTML.
If you choose HTML, HTML is only added, **not replaced**.

HTML is intended for use when it is difficult to write in CSS or JavaScript.
For example, if you want to load external JavaScript, it is easier to just apply the script tag as HTML.

Thanks.
