### ISSUE TITLE
Done ratio field float

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#136]
Hi thx for your lovely plugin
If I can asking u?!

1_ I'm changing the type of column done_ratio to float
2_ setting the done ratio calculation from issue Field
3_ setting to calculate done ratio from subtask

4_ I using formula
@issue.done_ratio = @ issue.custom.field.value(1).to_f.round(2)

5_ every things in child issue okay with float numbers done ratio 

6_ the problem in parent task
The done ratio appear 61%
I need look to 60.69%
   
      Example 
      child1 (:done_ratio => 10.12)
      child2 (:done_ratio => 20.23)
      child3(:done_ratio => 90.45)
      (10.12 + 20.33 + 90.44) / 3 = 12
       parent.issue.done_ratio=60.69
If u can help where  in core redmine code how calculate parent done ratio to be round(2)

Or by using your plugin?!

**Comment by onozaty** [comment]
I think it may be a problem with the floating point calculations, but I am not sure where that occurs.
I'm sorry I can't help you.

**Comment by ashrafalzyoud** [comment]
I found in
App/models/assue.rb
Line 1853

`if p.done_ratio_derived?
        # done ratio = average ratio of children weighted with their total estimated hours
        unless Issue.use_status_for_done_ratio? && p.status && p.status.default_done_ratio
          children = p.children.to_a
          if children.any?
            child_with_total_estimated_hours = children.select {|c| c.total_estimated_hours.to_f > 0.0}
            if child_with_total_estimated_hours.any?
              average = Rational(
                child_with_total_estimated_hours.sum(&:total_estimated_hours).to_s,
                child_with_total_estimated_hours.count
              )
            else
              average = Rational(1)
            end
            done = children.sum do |c|
              estimated = Rational(c.total_estimated_hours.to_f.to_s)
              estimated = average unless estimated > 0.0
              ratio = c.closed? ? 100 : (c.done_ratio || 0)
              estimated * ratio
            end
            progress = Rational(done, average * children.count)
            p.done_ratio = progress.floor
          end
        end
      end`
