### ISSUE TITLE
disabled checkbox option

### ISSUE THREAD

**Issue by ebergu78** [onozaty/redmine-view-customize-scripts#137]
hola! espero no te moleste que escriba en español
Cada vez que cambio el Proyecto en el formulario, necesito mostrar diferentes opciones en mi campo personalizado (con display=checkboxes)

Parte del código:

$(function() {

  const hideOption = function(option) {

      option.hide();
      option.prop('disabled', true);
      option.prop('checked', false);
  }

Cuando ejecuto: 
hideOption($('#issue_custom_field_values_168 > option[value="1639"]'));

Resultado:
Si mi campo personalizado es una lista, funciona OK y me oculta la opción.
Si mi campo personalizado es un checkbox, no funciona y me muestra la opción

Podrías ayudarme? Gracias!

**Comment by onozaty** [comment]
If checkbox, the HTML structure is different.
Please try it while checking the structure with DevTools of your browser.

```js
const hideCheckbox = function(checkbox) {

  checkbox.parent().hide();
  checkbox.prop('checked', false);
}

hideCheckbox($('.cf_168 input[value="1639"]'));
```
