### ISSUE TITLE
Not hide customized fields when modify the task

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#138]
Hi @onozaty,
I hipe that you are very well.
I take you example [0047.change_visibility_of_custom_fields_by_categories](https://github.com/onozaty/redmine-view-customize-scripts/tree/master/examples/0047.change_visibility_of_custom_fields_by_categories)
I custom with my values for hide customized fields with the id of categories.
The javascript run ok when I create a new issue, but If I modify a exist issue and modify the values of category field, the customized fields don't hide.
The code:
*****************************
$(function() {

   const changeVisible = function() {
    switch($('#issue_category_id').val()) {
      case '1':
        $('#issue_custom_field_values_234').parent().hide();
        $('#issue_custom_field_values_235').parent().hide();
        $('#issue_custom_field_values_236').parent().hide();
        $('#issue_custom_field_values_237').parent().hide();
        $('#issue_custom_field_values_238').parent().hide();
        $('#issue_custom_field_values_239').parent().hide();
        $('#issue_custom_field_values_240').parent().hide();
        break;

      case '2':
        $('#issue_custom_field_values_227').parent().hide();
        $('#issue_custom_field_values_228').parent().hide();
        $('#issue_custom_field_values_229').parent().hide();
        $('#issue_custom_field_values_230').parent().hide();
        $('#issue_custom_field_values_231').parent().hide();
        $('#issue_custom_field_values_232').parent().hide();
        $('#issue_custom_field_values_233').parent().hide();
        break;

    }
  }

  changeVisible();
  $('#issue_category_id').on('change', changeVisible());
});

*************
<html>
<body>

Path pattern |  
-- | --
 
Bottom of issue form
JavaScript

</body>
</html>

******************************************
Any idea  for hide when modify the task ?

Regards, and thank you for you incredible support.

**Comment by onozaty** [comment]
Sorry, the sample code was incorrect.

Could you please remove the `()` as follows.

```diff
-    $('#issue_category_id').on('change', changeVisible());
+    $('#issue_category_id').on('change', changeVisible);
```

Thanks.

**Comment by jlsblasco** [comment]
Hi again,
thank you for the support.
I change it, now WHen I modify the issue, the customs fields don't hide with the select categories, as the same format with in a new issue.
Now I select other category and save the issue and edit after and now show the new fields corrresponding with a new category selected, but the changes not show in a fly.
Any idea?
Regards

**Comment by jlsblasco** [comment]
Hi, I include two files, one when I include a new issue and other when I modify a issue.
Regards

https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/54b70189-dc05-43ae-a6c9-7345add64889


https://github.com/onozaty/redmine-view-customize-scripts/assets/50949839/218e806f-d5f4-4526-978e-f7a969d12276

**Comment by onozaty** [comment]
Can you tell me again what code you are currently registered with?

**Comment by jlsblasco** [comment]
Hi again,
I review the code and include the show fields in options and now run ok.
Thank you and congratulation for this fantastic plugin.
Regards
