### ISSUE TITLE
hot to take a date custom field value in a form

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#139]
Hi @onozaty,

I have aproblem when I want to validate a date customfield.

I need to generate a alert message when the date was wrong.

When use:
 var fin_prorroga  = $('.cf_245 .value').text();

I take the old date value in the form, but If I change on the fly dont take the new value.

I test with other posibilities:
var fin_prorroga = $('#issue_custom_field_values_244 > option:selected').text();
var fin_prorroga = $('#issue_custom_field_values_243').val(); 
and all are failed.

I read your page https://github.com/onozaty/redmine-view-customize-scripts/blob/master/tips/tips.md#get-the-value-of-a-issue-field
but there aren't references to a date fields.

Any idea?
regards and thankyou in advance.

**Comment by onozaty** [comment]
I think you can get it with the following code.

```
$('#issue_custom_field_values_243').val();
```

Since you will be specifying the id assigned to the form, could you please check if the id is correct in the Browser's DevTools?

Thanks.

**Comment by jlsblasco** [comment]
Hi @onozaty 
I test again and with the code
$('#issue_custom_field_values_243').val();
the process run ok.

Sorry for the inconvenience.
Thank you !!!
