### ISSUE TITLE
redmine view custimue scripts

### ISSUE THREAD

**Issue by TiniRED** [onozaty/redmine-view-customize-scripts#140]
Dear @onozaty ,

many thanks for your Costum View plugin to Redmine.
I've tested several of them and came up with an issue, which I could not resolve up to now. I hope, that you have any idea?

I want to use the script "Set the default value by tracker", "When the parent custom field is selected, the child custom fields will be enabled" together with "When creating a child issue, the information from the parent issue is used".
1: https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0003.set_default_value_by_tracker/example.md
2: https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0031.enable_child_when_parent_selected/example.md
3: https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0023.when_create_child_use_parent_infomation/example.md

They all working great alone, but I cannot activate all of them. I have several scripts 1 and 2 for different projects and trackers. But soon I activate no. 3, it crashes somehow my other scripts. Even though, they address different projects, trackers or custom fields.
Do you have any idea on that?
Many thanks in advance! I'm sorry for any inconvenience.

Kind regards
TiniRED

**Comment by onozaty** [comment]
Can I see the error in my browser's DevTools Console?
If there are errors, please let me know what they are.

Thanks.

**Comment by TiniRED** [comment]
Hi @onozaty ,
you can see the following in the DevTool in MS Edge.
![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/146327839/41ca0a44-2ead-4121-8d32-7b1af4a96a62)

**Comment by onozaty** [comment]
Hi @TiniRED 

Thank you very much.

Do you see this error with the third script alone?

> 3: https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0023.when_create_child_use_parent_infomation/example.md

**Comment by TiniRED** [comment]
Hi @onozaty,
if I enable only the third script, I do not see any error.
The third script is also working.

But I'm not sure, why the third script, which I would like to use within Redmine project B is interacting negatively with script 1 and 2, which I would like to use within project A.
If I enable them individually, they are all functional.

**Comment by onozaty** [comment]
@TiniRED 

Does Project A allow for additional child tickets?

This script will error if there is no link to add subtasks.
Could you please provide a screen capture of the Issue in Project A?

Thanks.

**Comment by TiniRED** [comment]
Hi @onozaty 

great idea. 
Project A does not allow child tickets. For this project, child tickets are not necessary, the role A does not allow child ticket creation.
But Project B has child tickets and role B also allows child ticket creation.
For testing, I activated for role A also the child ticket creation and finally the script in project A is also working.

Nevertheless, I'm confused about that. I would like to separete the projects and roles (and scripts) from each other and I have more roles and projects than A and B in produtive database. But now it seems, that I have to allow child ticket creation to all of my roles. Is this true? 
The link to add subtaks is allowed for role B and project B. Why is this a general prerequisite?

**Comment by onozaty** [comment]
Changed to skip processing if there is no link to add subtasks.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0023.when_create_child_use_parent_infomation/example.md

Can you please try this one?

Thanks.

**Comment by TiniRED** [comment]
Hi @onozaty ,

fantastic, thank you so much. 
Works :)
