### ISSUE TITLE
show/hide a custom field type=radio

### ISSUE THREAD

**Issue by cbmarchetti** [onozaty/redmine-view-customize-scripts#142]
Hi,
Thank you for this plugin!!

How I can to show/hide a custom field type=radio?

Thank you!.
Regards

Example:

$(function() {
  const changeVisible = function() {
    switch($('#issue_custom_field_values_186 > option:selected').val() ) {
      case "1003":
        **$('#input[name="issue[custom_field_values][189]"]:checked').parent().show();
		$('.input[name="issue[custom_field_values][189]"]:checked.attribute').show();**
        break;
		default:
        **$('#input[name="issue[custom_field_values][189]"]:checked').parent().hide();
		$('.input[name="issue[custom_field_values][189]"]:checked.attribute').hide();**
		break;
    }
  }
  changeVisible();
  $('#issue_custom_field_values_186').on('change', changeVisible);
});

**Comment by onozaty** [comment]
Hi @cbmarchetti 

Please try the following.

```js
$('.cf_189.check_box_group').parent().show();

$('.cf_189.check_box_group').parent().hide();
```

You may find out what to specify by checking with DevTools in your browser.

![image](https://github.com/onozaty/redmine-view-customize-scripts/assets/47337/1dafe67b-d67b-4e5b-9ea0-bbccaf720197)

Thanks.

**Comment by cbmarchetti** [comment]
thank you so much!!
