### ISSUE TITLE
Change the name of bar (Issue) depends in project id

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#143]
Thx for your stronger plugin 

How u can change name (issue) depend in project

**Comment by onozaty** [comment]
Can you tell me more about what you would like to do?

**Comment by ashrafalzyoud** [comment]
Sorry for late reply 

My question is in bar 
(Overview activity issue....)

How I can change the lable name for as example overview depends in project id

Project id 1 name (overview )
Project id 2 name edit( goals)
Project id 3 name edit (KPI)

**Comment by onozaty** [comment]
I don't know where “in bar” refers to.
Could you please provide a screen capture or something?
