### ISSUE TITLE
Need to change possition of watchers_form_container

### ISSUE THREAD

**Issue by serden85** [onozaty/redmine-view-customize-scripts#146]
Hello @onozaty !!

Is it possible to change the position of the watchers field?
Need to put watchers after some custom field.

I tried to do this based on examples for "custom field" and "long text", but failed.

**Comment by onozaty** [comment]
I believe that the Watcher originally exists behind the custom field.
Could you be more specific about the location of the move?
A screen capture would be helpful.

Thanks.
