### ISSUE TITLE
プロジェクトパターン決定にて複数プロジェクトを指定したい場合の正規表現

### ISSUE THREAD

**Issue by HirokiNakatani** [onozaty/redmine-view-customize-scripts#147]
プロジェクトパターン決定にて複数プロジェクトを指定したい場合の正規表現のサンプルをいただけないでしょうか。

**Comment by onozaty** [comment]
`project1|project2` みたいな形で、`|`によって結合することで複数指定できます。

**Comment by HirokiNakatani** [comment]
有難うございます。いただいた内容で実装するようにします。
