### ISSUE TITLE
チケット編集画面で、Redmine標準の必須項目に対し、必須項目未入力のアラート発生時に、本プラグインのフィールド表示非表示制御が機能しなくなります

### ISSUE THREAD

**Issue by HirokiNakatani** [onozaty/redmine-view-customize-scripts#148]
原因と対処について教えてください

**Comment by onozaty** [comment]
どういったスクリプトを利用し、どういったときに問題となりますでしょうか。
もう少し詳しく教えていただければ何かサポートできるかもしれません。

**Comment by HirokiNakatani** [comment]
例えば以下の表示のカスタマイズに対し、標準の必須項目を未入力でチケット保存しようとすると、エラー画面では制御が効かなくなっております。

■表示のカスタマイズ
パスのパターン	/issues/
プロジェクトのパターン	c284523344
挿入位置	チケット入力欄の下
種別	JavaScript
コード	
$(function() {
  // カスタムフィールドのID定義
  const field250Id = '#issue_custom_field_values_250';         // 申請種別
  const issueTrackerId = '#issue_tracker_id';                  // トラッカーID
  const fileFieldId = '#issue_custom_field_values_251_blank';  // 処置記録ファイル

  // 制御対象のカスタムフィールドID
  const controlledFieldIds1 = ['#issue_custom_field_values_248', '#issue_custom_field_values_242'];  // オブジェクト、オブジェクト操作
  const controlledFieldIds2 = ['#issue_custom_field_values_249'];                                    // 手動実行
  const allControlledFieldIds = [...controlledFieldIds1, ...controlledFieldIds2];                    // すべての制御対象フィールドをまとめる
  
  // 必須マークのHTML
  const requiredMark = '<span class="required"> *</span>';
  
  // フィールドの表示/非表示を切り替える関数
  function toggleField(id, show) {
    const fieldInput = $(id);
    const fieldDisplay = $('div.cf_' + id.split('_').pop() + '.attribute');
    const labelElement = fieldInput.closest('.cf_' + id.split('_').pop()).prev('label');

    fieldInput.parent().toggle(show);
    fieldDisplay.toggle(show);
    labelElement.toggle(show);

    if (show) {
      fieldInput.attr('required', 'required');
      if (!labelElement.find('.required').length) {
        labelElement.append(requiredMark);
      }
    } else {
      fieldInput.removeAttr('required');
      labelElement.find('.required').remove();
    }
  }

  // 処置記録ファイルフィールドの表示/非表示を切り替える関数
  function toggleFileField(show) {
    const fileFieldContainer = $(fileFieldId).closest('p');
    const labelElement = fileFieldContainer.find('label');
    
    fileFieldContainer.toggle(show);
    
    if (show) {
      fileFieldContainer.find('input[type="file"]').attr('required', 'required');
      if (!labelElement.find('.required').length) {
        labelElement.append(requiredMark);
      }
    } else {
      fileFieldContainer.find('input[type="file"]').removeAttr('required');
      labelElement.find('.required').remove();
    }
  }

  // リストのオプションをフィルタリングする関数
  function filterOptions(fieldId, filterValue) {
    let field = $(fieldId);
    field.find('option').each(function() {
      let optionValue = $(this).val();
      $(this).toggle(optionValue.startsWith(filterValue));
    });
  }

  // トラッカー名称から先頭3文字を取得する関数
  function getTrackerPrefix() {
    const selectedOption = $(issueTrackerId + ' option:selected');
    const trackerName = selectedOption.text().trim();
    return trackerName.substring(0, 3);
  }

  // フィールドの表示状態を更新する関数
  function updateFieldVisibility() {
    const value250 = $(field250Id).val();  // 申請種別の値を取得
    const trackerPrefix = getTrackerPrefix();  // トラッカー名称の先頭3文字を取得
    
    // すべての制御対象フィールドを一旦非表示に
    allControlledFieldIds.forEach(id => toggleField(id, false));
    toggleFileField(false);
  
    // 申請種別に基づいてフィールドを表示
    switch (value250) {
      case 'オブジェクト変更':
        toggleField(controlledFieldIds1[0], true); // オブジェクトを表示
        toggleField(controlledFieldIds1[1], true); // オブジェクト操作を表示
        break;
      case '手動実行':
        toggleField(controlledFieldIds2[0], true); // 手動実行を表示 
        break;
      case '移送':
        toggleFileField(true); // 処置記録ファイルを表示 
        break;
    }
    
    // トラッカー名称の先頭3文字でリストをフィルタリング
    if (trackerPrefix) {
      filterOptions(controlledFieldIds1[0], trackerPrefix); // オブジェクトフィールド値をフィルタリング
      filterOptions(controlledFieldIds2[0], trackerPrefix); // 手動実行フィールド値をフィルタリング
    }
  }

  // イベントリスナーの設定
  $(field250Id).on('change', updateFieldVisibility);
  $(issueTrackerId).on('change', updateFieldVisibility);
  
  // ページ読み込み時に初期実行
  updateFieldVisibility();
});


■チケット登録時の初期画面
![{9D4094E3-7464-47C0-BEC4-0EF740463529}](https://github.com/user-attachments/assets/a3f46e69-62b5-4de5-be09-3dfb69a8333c)

■標準フィールド未入力状態での保存を押下した結果の画面
一部のカスタムフィールドを表示させないように制御したいが、表示されてしまっています
![{76853F8C-4207-4997-8DB2-82F0C2BFB5E3}](https://github.com/user-attachments/assets/9f9ef129-7e51-4ec6-b8c1-e82745de0212)

**Comment by onozaty** [comment]
パスのパターンの `/issues/`だと、入力エラーの画面のパスと一致しなくてこの現象になってしまっているのではと想定しています。
挿入位置の指定でチケットの入力欄というのは限定されるので、パスのパターンの方は空にしてみていただけますでしょうか。

**Comment by HirokiNakatani** [comment]
ご指摘いただいた内容で解消しました。ありがとうございました。
(チケット登録時、URL末尾が/issuesとなっていたので、/issues/→/issuesに変更した結果、動作するようになりました)
