### ISSUE TITLE
Redmine view customize couldn't solve conditional custom fields task

### ISSUE THREAD

**Issue by kireyn** [onozaty/redmine-view-customize-scripts#15]
I found you solution for conditional custom fields task.
https://www.redmine.org/issues/22026
Doing step by step from http://blog.enjoyxstudy.com/entry/2016/04/03/000000 
still get broken result at the end.
Can you help me? I ll be very grateful.
![redmine 1 1](https://user-images.githubusercontent.com/14308843/37684467-ca1ae54a-2c98-11e8-9980-32d61fde5bd3.png)
![redmine 1 2](https://user-images.githubusercontent.com/14308843/37684468-ca4366dc-2c98-11e8-8a79-99a07415d3ef.png)
![redmine 1 3](https://user-images.githubusercontent.com/14308843/37684469-ca663a54-2c98-11e8-9ae1-6f18fe44d562.png)

**Comment by onozaty** [comment]
Hi @kireyn 

It is possible that `parentFieldId` and `childFieldId` do not match with your environment.
You should change these IDs according to your environment.

**Comment by lublasco** [comment]
Hi, @onozaty 

I'm trying to make this script work but just can't make it. I suppose I'm doing anything wrong.

Case is following:
parent custom field ID= 13 (list: A, B, C)
child custom field ID= 14  (list D, E, F, G, H)

When A is selected, then options D and E have to be shown in child custom field.
When B is selected, then options F, G, and H have to be shown in child custom field.
When C is selected, then nothing has to be shown in child custom field.

Could you please indicate the right script?

Thank you very much in advance.

**Comment by onozaty** [comment]
Hi @lublasco 

The value must have a parent-child relationship.

> When A is selected, then options D and E have to be shown in child custom field.
> When B is selected, then options F, G, and H have to be shown in child custom field.
> When C is selected, then nothing has to be shown in child custom field.

If you want to do like the above, you need to change the child's value as follows
* A-D
* A-E
* B-F
* B-G
* B-H

It is judged by forward match.

Thanks

**Comment by lublasco** [comment]
Hi, @onozaty Thanks a lot for your reply but still with these indications I'm not able to make it work. It would be great if you could paste here the code that would make the conditional field work. Sorry for my insistence.

**Comment by onozaty** [comment]
Hi @lublasco 

Can the following code be helpful?
https://github.com/onozaty/redmine-view-customize-scripts/blob/master/link_custom_field.js

**Comment by lublasco** [comment]
@onozaty No, I tried using this formula but didn't succeed. Maybe I'm doing anything wrong. That's why I posted the real data so that you could exactly give the right output, if possible.

**Comment by onozaty** [comment]
Hi, @lublasco 

Would you please let me know the code actually executed and the value of the custom field again?
I might be able to advise something.

**Comment by lublasco** [comment]
Parent field name/id: List 1 / id 13
Chield field name/id: List 1.1 / id 14 

parent custom field values= A, B, C
child custom values= D, E, F, G, H

When A is selected, then options D and E have to be shown in child custom field.
When B is selected, then options F, G, and H have to be shown in child custom field.
When C is selected, then nothing has to be shown in child custom field.

Path pattern: /issues/
Insertion position: Head of all pages (tried also with the other two options)
Type: Javascript

Code:

 $(function() {

  var 13 = 'A,B,C';
  var 14 = 'A-D,A-E,B-F,B-G,B-H';

  var isTarget = function(child, parent) {
    return child.text().indexOf(parent.text()) == 0;
  }

  var narrowChildField = function() {

   var parentSelected = $('#' + 13 + ' > option:selected');

   $('#' + 14 + ' > option').each(function() {

   var child = $(this);
    if (isTarget(child, parentSelected)) {
        child.show();
        child.prop('disabled', false);
      } else {
        child.hide();
        child.prop('disabled', true);
      }
    });
  }

  narrowChildField();

  $('#all_attributes').change(function(e) {
    if (e.target.id == 13) {
      narrowChildField();
    }
  });

  var _replaceIssueFormWith = replaceIssueFormWith;
  replaceIssueFormWith = function(html){
    _replaceIssueFormWith(html);
    narrowChildField();
  };
});

-------
Thanks again for your patience and help. I really appreciate it.

**Comment by onozaty** [comment]
Hi @lublasco 

Your code is code that does not work as JavaScript.

Please change it as follows.

```javascript
$(function() {

  var parentFieldId = 'issue_custom_field_values_13';
  var childFieldId = 'issue_custom_field_values_14';

  var isTarget = function(child, parent) {
    return child.text().indexOf(parent.text()) == 0;
  }

  var narrowChildField = function() {

    var parentSelected = $('#' + parentFieldId + ' > option:selected');

    $('#' + childFieldId + ' > option').each(function() {

      var child = $(this);

      if (isTarget(child, parentSelected)) {
        child.show();
        child.prop('disabled', false);
      } else {
        child.hide();
        child.prop('disabled', true);
      }
    });
  }

  narrowChildField();

  $('#all_attributes').change(function(e) {
    if (e.target.id == parentFieldId) {
      narrowChildField();
    }
  });

  var _replaceIssueFormWith = replaceIssueFormWith;
  replaceIssueFormWith = function(html){

    _replaceIssueFormWith(html);

    narrowChildField();
  };
});
```

From the setting screen of Redmine, change the value of the custom field as follows.

* Chield field name/id: List 1.1 / id 14
  * A-D
  * A-E
  * B-F
  * B-G
  * B-H

The value of the child custom field itself must include the parent's information.

**Comment by lublasco** [comment]
Yesss, that did work! Thank you very much again for your help, @onozaty !!

**Comment by onozaty** [comment]
You are welcome!
