### ISSUE TITLE
the user visibility

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#150]
i note if the user have only view tracker and he not have permission
he not see any code the admin put it in (css or java)
im correct?

**Comment by onozaty** [comment]
Sorry, I did not understand what you are referring to in what case.
Could you please describe it in more detail?

Thanks.

**Comment by ashrafalzyoud** [comment]
if i have tow rols 
role(a) have persmission view and edit
role(b) have permission view

i note the users in role (b) its cant see any css code i made it only if i give him role edit

**Comment by onozaty** [comment]
Are you talking about on the View customize configuration screen?
Only the administrator can see the configuration screen.

**Comment by ashrafalzyoud** [comment]
Any examples from your page its execution for users have rules (edit)

**Comment by onozaty** [comment]
For control by roles, please refer to the following.

- https://github.com/onozaty/redmine-view-customize-scripts/blob/master/tips/tips.md#check-the-roles
