### ISSUE TITLE
Spent time fields on new issue page

### ISSUE THREAD

**Issue by lublasco** [onozaty/redmine-view-customize-scripts#16]
Hi, would it be possible to use your plugin to insert the spent time form at the bottom of the "new issue" form? That would be very useful for tickets that are created after the task has been executed.

Thanks in advance for your help!

**Comment by onozaty** [comment]
Hi @lublasco 

On the server side, spent time is not accepted when issue is created.
So it is difficult.

I'm sorry I can't help you.

**Comment by lublasco** [comment]
Understood, onozaty. Thank you for the explanation and the plugin!
