### ISSUE TITLE
view-customize script max lenght

### ISSUE THREAD

**Issue by daviddawei86** [onozaty/redmine-view-customize-scripts#17]
Greetings! 

When I try to save a code of more than 65,535 lenght redmine give me internal error. Is there any way to increase the maximum size?
If I can not increase the size, is there any way to chain multiple scripts?
I mean at the end of the first script call the second script by path.

Thank you

**Comment by onozaty** [comment]
Hi @daviddawei86 

I'm sorry for the late reply.

I am planning to increase the maximum size in the next version of View customize.
Could you tell me the version of Redmine you currently use?

**Comment by daviddawei86** [comment]
hello!
I'm using 1.1.4 version . By the way you know an easy way to add a button to export an unique issue to csv format , at the current version allows export all issue but i just need the selected one.

Thank you

**Comment by onozaty** [comment]
Could you please tell me the version of Redmine, not the plugin?
I do not know how to export only the selected ones. I think that it can not be done with View customize plugin.

Thanks

**Comment by daviddawei86** [comment]
I'm using Redmine 3.3.0.stable version. 
Using view customize in script with path pattern /issues/[0-9]+ i can dowload in csv format the information of the issue using save or modified buttons but i need a independent button. My idea is use this library [https://www.npmjs.com/package/exceljs#interface](url) in a button associated to the specific isssue , 
You say i can do it in redmine 4.0 , right? or you know another plugin to do it.

Thank you  xD

**Comment by onozaty** [comment]
I think that it is impossible to do with View customize. Even Redmine 4.0.
And i tried looking for other plugins, but I could not find it.

I confirmed the version of Redmine because the latest version of View customize only supports Redmine 3.1 and later.
Changing the maximum size of the script will be released soon.

Thanks

**Comment by daviddawei86** [comment]
Finally i associated copy button   /issues/[0-9]+/copy to 
https://code-maven.com/create-and-download-csv-with-javascript
and it works , but the problem is i need xslx format to do cells with format , i installed libraries like this https://github.com/SheetJS/js-xlsx
 but in view customize the script tag 
<script lang="javascript" src="dist/xlsx.full.min.js"></script>
it doesn't work
You know the way to make it work?

Thanks! 
![photo](https://user-images.githubusercontent.com/43613875/51822889-f250a900-22dd-11e9-9469-6f55dbc1888d.PNG)

**Comment by onozaty** [comment]
To load the script, please try the following.

```javascript
$("head").append($('<script lang="javascript" src="dist/xlsx.full.min.js"></script>'));
```

Also, changing the maximum size of the script was done in version 2.0.1
* https://github.com/onozaty/redmine-view-customize/releases/tag/v2.0.1

**Comment by daviddawei86** [comment]
Thank you!

now i'm trying to send custom field values to php ;D . There is no way to make view_customize php compatible, right?

**Comment by onozaty** [comment]
> There is no way to make view_customize php compatible, right?

Unfortunately there is no way.
