### ISSUE TITLE
Show value of custom field as alert on top of issue list or project overview page

### ISSUE THREAD

**Issue by itnovative** [onozaty/redmine-view-customize-scripts#18]
Hi,
Using your plugin I would like to do the following;

Display an alert on top of the issue list, showing the contents of my custom project field. In this way I want to communicate important project messages to the users.

What javascript code would I need to do this?

I started with your example:
Path pattern: /issues$
Script:

```
$(function() {
$('#content').prepend(
$('<div class="flash warning">Default notice</div>'));
});
```

This gives a nice visible alert above the issue list, exactly what I want.
But instead of this text it should show the value of my custom field.

If this is difficult to do, I would also be happy if the alert could show the latest news entry for the project.
Many thanks in advance!

**Comment by onozaty** [comment]
Hi @itnovative 

Custom project field can be retrieved using Ajax.

The following is sample code.
Please change the part of `customField.id == 1` according to the setting of the project

```javascript
$(function() {

  $.ajax({
      type: 'GET',
      url: '/projects/' + ViewCustomize.context.project.identifier + '.json',
      dataType: 'json'
  })
  .done(function(data) {
     var customField = data.project.custom_fields.filter(function(customField) {
       return customField.id == 1;
     })[0];

     $('#content').prepend(
       $('<div class="flash warning"></div>').text(customField.value));
  })
  .fail(function(data) {
    alert('failed');
  });
});
```

**Comment by itnovative** [comment]
Hi,
Sorry for the very late reply...
When this script is run Redmine asks me to enter my login credentials. After I do the correct custom field value is shown.

How can I avoid this login request?
Many thanks in advance!

**Comment by onozaty** [comment]
Hi @itnovative 

API key must be used.
To set the API key when sending a request, do the following.

```javascript
$(function() {

  $.ajax({
      type: 'GET',
      url: '/projects/' + ViewCustomize.context.project.identifier + '.json',
      headers: {
        'X-Redmine-API-Key': ViewCustomize.context.user.apiKey
      },
      dataType: 'json'
  })
  .done(function(data) {
     var customField = data.project.custom_fields.filter(function(customField) {
       return customField.id == 1;
     })[0];

     $('#content').prepend(
       $('<div class="flash warning"></div>').text(customField.value));
  })
  .fail(function(data) {
    alert('failed');
  });
});
```

You will use REST API, so we need to "Enable REST web service" via REST in Redmine settings.
Also, an API key must have been created. For details on creating an API key, please refer to the following.

* https://github.com/onozaty/redmine-view-customize#api-access-key

Thanks.

**Comment by itnovative** [comment]
Thank you for this code, it works without any issues!
I must say I am really pleased with your support on this plugin, it has allowed me to make further optimizations in how we use Redmine. Big respect.

I am sure others will also find this code very helpfull.

So a very big thanks and all the best for 2023!

**Comment by onozaty** [comment]
Hi @itnovative 

If you are using ViewCustomize v2.3.0 or later, you can get the project's custom fields from ViewCustomize.context.project.customFields, so no REST API calls are required.

```javascript
$(function() {

  var customField = ViewCustomize.context.project.customFields.filter(function(customField) {
    return customField.id == 1;
  })[0];

  $('#content').prepend(
    $('<div class="flash warning"></div>').text(customField.value));
});
```

* https://github.com/onozaty/redmine-view-customize#viewcustomizecontext-javascript

Thanks.
