### ISSUE TITLE
How can I define to show issue_custom_field_values_1 field,  when the issue_status_id is 6( Refused)

### ISSUE THREAD

**Issue by archonwang** [onozaty/redmine-view-customize-scripts#2]
@onozaty ，
How can I define to show issue_custom_field_values_1 field (list field ),  when the issue_status_id changed to  Refused(statusID is 6)?

Thanks a lot.

**Comment by onozaty** [comment]
Hi @archonwang 
I'm sorry for the late reply.

Please try the following.

``` javascript
/*
Path pattern: /issues
Type: JavaScript
*/
$(function() {

  var changeVisibility = function() {

    var visible = $('#issue_status_id').val() == '6'; //  Refused

    if (visible) {
      $('#issue_custom_field_values_1').parent().show();
      $('.cf_1').show();
    } else {
      $('#issue_custom_field_values_1').parent().hide();
      $('.cf_1').hide();
    }
  };

  changeVisibility();

  $('#all_attributes').on('change', '#issue_status_id', function(e) {
    changeVisibility();
  });

  var _replaceIssueFormWith = replaceIssueFormWith;
  replaceIssueFormWith = function(html){

    _replaceIssueFormWith(html);

    changeVisibility();
  };
})
```

**Comment by archonwang** [comment]
thanks. these days i have to be in hospital, i will test it later.

**Comment by archonwang** [comment]
@onozaty ， 
it worked. well, Thanks so much. 
Maybe you can add it into you scripts libary.

**Comment by onozaty** [comment]
Thanks,
Already added to the scripts libary.

https://github.com/onozaty/redmine-view-customize-scripts/blob/master/change_custom_field_visibility_when_change_status.js
