### ISSUE TITLE
Сравнение дат и выделение поля с датой

### ISSUE THREAD

**Issue by maksnet2** [onozaty/redmine-view-customize-scripts#20]
Добрый день.
Мне нужно проверить определенное поле с датой и если дата в нем меньше текущей, то выделить его цветом. Я сделал скрипт (указал ниже), но мне кажется, что он не оптимален.
Скажите пожалуйста, можно ли его сделать проще, оптимальнее?
Redmine 3.4.6

```
/*
Path pattern:	/issues$
Insertion position:	Head of all pages
Type:	JavaScript
*/

  var now = new Date();
  
  $('.due_date').each(function()
   {
     var datex = $(this).text();
     if (datex.indexOf(".") > 0) { datex = datex.replace(".", "-").replace(".", "-") + ' 00:00:00'; }
     var date = datex.substr(6, 4) + datex.substr(2, 4) + datex.substr(0, 2) + datex.substr(10);
     var date2 = new Date(date);
     if  (now - date2 >= 0)
      { 
         $(this).css({'backgroundColor': 'bisque'})         

      }
   });
})
```

**Comment by onozaty** [comment]
Hi @maksnet2 

The format of the date depends on the locale.
Could you give me an example of display in your locale?

**Comment by maksnet2** [comment]
Используется формат: "DD.MM.YYYY".  На скриншоте пример.
![2019-04-03_210432](https://user-images.githubusercontent.com/19895894/55498665-3735ea80-5655-11e9-807c-8363b9d18f43.png)

**Comment by onozaty** [comment]
The string in DD.YY.MMMM format can not be converted to Date as it is, so it is not a very simple code.

```javascript
$(function() {
  var now = new Date();
  
  $('.due_date').each(function()
  {
    var splitted = $(this).text().split('.');
    if (splitted.length != 3) {
      return;
    }

    var dueDate = new Date(splitted[2], splitted[1] - 1, splitted[0]);
    if  (dueDate <= now) { 
      $(this).css({'backgroundColor': 'bisque'});
    }
  });
})
```

**Comment by maksnet2** [comment]
Привет @onozaty !
Спасибо, все работает. Ваш "не очень простой код" все равно красивее и проще моего :)). Еще раз спасибо за помощь.

**Comment by onozaty** [comment]
You are welcome!
