### ISSUE TITLE
can't change highlight color of select2

### ISSUE THREAD

**Issue by crosspoints** [onozaty/redmine-view-customize-scripts#21]
日本語ですみません。

rmplusが提供しているusability pluginのa_common_libにあるselect2 を使って担当者などをview customizeで補完可能にしたまではいいのですが、highlightのカラーの調整がどうにもうまくいきません。
他のプラグイン(RedmineUP)から読まれている select2.css が優先されているように見えます。

view customizeでは以下の設定です
```
.select2-container--default .select2-results__option--highlighted[aria-selected] {

    background-color: #5897fb;
    color: white;

}
```

この設定をしているのですが、デバッガで開くと select2.cssがどうしても優先されてしまいます。

![2019-04-12_15h54_33](https://user-images.githubusercontent.com/32406258/56018278-9e7e2980-5d3c-11e9-88c9-f4c1eda78c7c.png)

なにか対処方法あるのでしょうか？

**Comment by onozaty** [comment]
@crosspoints 
CSSの優先度として、まったく同じセレクタだと、後から書かれたもので上書きされるので、View customizeでの埋め込みの後に、select2.cssの読み込みが行われているものと思われます。

CSSのセレクタとしてもっと詳細に指定できれば、そちらが優先されるようになるのですが、今回の`.select2-container--default` `.select2-results__option--highlighted[aria-selected]` で実際に対象となる要素はどういったものになりますでしょうか。
たとえば、`div`要素ならば、`div.select2-container--default` のように指定することによって、こちらのほうが優先されることになります。

**Comment by crosspoints** [comment]
@onozaty 
そうなんですよね...

今回の対象はその通りなんです。
チケットの担当者をselect2 にした場合にマウスオーバーすると色が変わるんですが、その部分になるので対象は .select2-container--default... が対象になります。

いろいろ見ていると、gem に redmine_crm があるのですがこれのtestの下にあるselect2.css がどういうわけかplugin_assetsに入ってしまっていたので強制削除させました。。。
view customizeで色変更はできなかったですが、本来？の色になって見にくくなくなったので一旦はこれでよいかなとは思っています。

**Comment by onozaty** [comment]
@crosspoints 

了解しました。
いったん閉じますので、もしも何かあったら、次はView customizeのスクリプトも一緒に教えてもらえると、こちらでもローカルで試して見ます。

**Comment by crosspoints** [comment]
ありがとうございます。
お言葉に甘えて

プラグインは https://www.redmineup.com/pages/ja/plugins/crm を入れています。
これにselect2が入っているので、view customizeで issuesとcontact(redmine_crm)の担当者にselect2を割当、あとselect2のハイライトの色を変更しようとしています。

select2の適用は以下です。

```
パスのパターン: | (/issues\|/contacts)
全てのページのヘッダ
JavaScript

// select2 適用

$(function() {

  var change_select2 = function() {
    $("#issue_assigned_to_id").select2({ width: '60%' });
    $("#contact_assigned_to_id").select2({ width: '25%' });
  }

  change_select2();

  // ステータス変更時などにDOMが差し替えられるので
  // フォームの内容が書き変わるたびに絞り込みを反映
  var _replaceIssueFormWith = replaceIssueFormWith;
  replaceIssueFormWith = function(html){
    _replaceIssueFormWith(html);
    change_select2();
  };
});

```

色変更は以下で行っています

```

パスのパターン: | .*
全てのページのヘッダ
CSS

.select2-container--default .select2-results__option--highlighted[aria-selected] {

    background-color: #29333A;
    color: white;

}
```

担当者のところはソースコードでは以下のようになっています。

```
<li class="select2-results__option" role="treeitem" aria-selected="false">&nbsp;</li>
<li class="select2-results__option" id="select2-issue_assigned_to_id-result-272b-1113" role="treeitem" aria-selected="false">&lt;&lt; 自分 &gt;&gt;</li>
<li class="select2-results__option select2-results__option--highlighted" id="select2-issue_assigned_to_id-result-x6tk-1" role="treeitem" aria-selected="true">Admin Redmine</li>

```
この場合は、"Admin Redmine"がハイライトしている状態でこれの色を変えようとしていますが
view customize の後ろに呼び出されているselect2.cssに邪魔されて適用できていないです。

ヘッダーを見ると

```
<head>
redmineup以外のプラグインのcss
view customizeのcss, javavscript
redmineup, rmplus, wiki_extensionsのプラグインのjavascript, css
</head>

```

となっているようです。。。
なんとかなるもんでしょうか。。。

**Comment by onozaty** [comment]
@crosspoints 
ちょっとバタバタしていてまだ見れていないのですが、、GWに時間が取れるので、こちらでも確認してみます。

**Comment by onozaty** [comment]
@crosspoints 

CSSですが、下記のように設定すればOKだと思います。
```css
.select2-container--default li.select2-results__option--highlighted[aria-selected] {
    background-color: #29333A;
    color: white;
}
```

CSSのセレクタは、詳細な指定のほうが優先されるので、単に要素名である`li`を追加するだけで、こちらが優先されます。

手元では背景色がちゃんと変わりました。
![image](https://user-images.githubusercontent.com/47337/56857751-3f5f1c80-69ac-11e9-96c1-33dc51c0638e.png)

**Comment by crosspoints** [comment]
ありがとうございます！
こちらでも確認できました！
自分でやったときは
.select2-container--default
を省いてしまっていてできないなぁと。。。

ありがとうございました
