### ISSUE TITLE
Project and default assignee relation

### ISSUE THREAD

**Issue by tanertas** [onozaty/redmine-view-customize-scripts#22]
Can we auto adjust "Assigne" to the default assigne of selected project dynamically? I checked the html code but it seems there's no any specific tag for default assignee in drop down menu items.

**Comment by onozaty** [comment]
Is it the same function as the following?

* http://www.redmine.org/issues/482

This feature is implemented in Redmine 3.4.

Thanks.

**Comment by tanertas** [comment]
Redmine has this feature but it works when issue has no any assignee assigned. If issue has an assignee, changing project of an issue has no any affect on assignee.

**Comment by onozaty** [comment]
Do you mean forcibly change the assignee when changing a project?

**Comment by tanertas** [comment]
Yes but if both project and assignee changed, assignee should remain as what selected.

**Comment by onozaty** [comment]
The following code can be used to forcibly change the assignee when changing the project.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/change_assignee_when_change_project.js

But If both the project and the assignee have changed, no way has been found to leave the assignee selected.
