### ISSUE TITLE
インストールできません。

### ISSUE THREAD

**Issue by j-yakkung** [onozaty/redmine-view-customize-scripts#23]
●現象
view_customize をインストールすると redmine が起動しなくなる。
（view_customize がインストールできていない。）
以下エラーページが表示される。

> Internal error
An error occurred on the page you were trying to access.
 If you continue to experience problems please contact your Redmine administrator for assistance.
If you are the Redmine administrator, check your log files for details about the error.
Back

●環境
Windows7 Pro(64bit)
bitnami-redmine-4.0.4-5-windows-x64-installer.exe でredmineインストール
下記プラグインインストール済み
・redmine_absolute_dates
・redmine_issue_templates
・redmine_work_time

●やったこと
１．redmine-view-customize-2.4.0 をダウンロード
２．view-customize にフォルダリネーム
３．上記フォルダを C:\Bitnami\redmine-4.0.4-5\apps\redmine\htdocs\plugins\ に配置
４．activerecord-compatible_legacy_migration 0.1.1.gem ダウンロード
５．上記 gem ファイルを C:\Bitnami\redmine-4.0.4-5\apps\redmine\htdocs\vendor\cache\ に配置
６．コマンドプロンプト（管理者）で以下実施
　①C:\Bitnami\redmine-4.0.4-5\apps\redmine\htdocs に移動
　②bundle install --without development test
　③bundle exec rake redmine:plugins:migrate RAILS_ENV=production

---以下コマンドプロンプトの内容---

> Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
C:\Bitnami\redmine-4.0.4-5>cd apps\redmine\htdocs　　←６．①
C:\Bitnami\redmine-4.0.4-5\apps\redmine\htdocs>bundle install --without development test　　←６．②
Using rake 12.3.2
Using concurrent-ruby 1.1.5
Using i18n 0.7.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.3
Using builder 3.2.3
Using erubi 1.8.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.3 (x64-mingw32)
Using rails-dom-testing 2.0.3
Using crass 1.0.4
Using loofah 2.2.3
Using rails-html-sanitizer 1.0.4
Using actionview 5.2.3
Using rack 2.0.7
Using rack-test 1.1.0
Using actionpack 5.2.3
Using nio4r 2.3.1 (x64-mingw32)
Using websocket-extensions 0.1.4
Using websocket-driver 0.7.1 (x64-mingw32)
Using actioncable 5.2.3
Using globalid 0.4.2
Using activejob 5.2.3
Using mini_mime 1.0.1
Using mail 2.7.1
Using actionmailer 5.2.3
Using method_source 0.9.2
Using thor 0.20.3
Using railties 5.2.3
Using actionpack-xml_parser 2.0.1
Using activemodel 5.2.3
Using arel 9.0.0
Using activerecord 5.2.3
Using activerecord-compatible_legacy_migration 0.1.1
Using mimemagic 0.3.3
Using marcel 0.3.3
Using activestorage 5.2.3
Using public_suffix 3.1.0
Using addressable 2.6.0
Using bundler 1.16.6
Using css_parser 1.7.0
Using csv 3.0.9
Using daemons 1.3.1
Using eventmachine 1.2.7 (x64-mingw32)
Using htmlentities 4.3.4
Using mysql2 0.5.2 (x64-mingw32)
Using net-ldap 0.16.1
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using sprockets 3.7.2
Using sprockets-rails 3.2.1
Using rails 5.2.3
Using rbpdf-font 1.19.1
Using rbpdf 1.19.8
Using redcarpet 3.4.0 (x64-mingw32)
Using request_store 1.0.5
Using rmagick 2.15.4 (x64-mingw32)
Using roadie 3.5.0
Using roadie-rails 1.3.0
Using rouge 3.3.0
Using thin 1.7.2 (x64-mingw32)
Using tzinfo-data 1.2019.1
Updating files in vendor/cache
Bundle complete! 29 Gemfile dependencies, 64 gems now installed.
Gems in the groups development, test, rmagick and sqlite were not installed.
Bundled gems are installed into `./vendor/bundle`

>C:\Bitnami\redmine-4.0.4-5\apps\redmine\htdocs>bundle exec rake redmine:plugins:migrate RAILS_ENV=production　　←６．③
★本来ならここにmigrate処理がずらずら出力されるとのことですが、何も出ませんでした。
C:\Bitnami\redmine-4.0.4-5\apps\redmine\htdocs>

---以上コマンドプロンプトの内容---

７．サービス再起動
manager-windows.exe で Running の以下サービスを Restart All で再起動
・MySQL Database
・Apache Web Server
・Thin_redmine
・Thin_redmine2

●production.log
・コマンド実施後
>Creating scope :system. Overwriting existing method Enumeration.system.
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at C:/Bitnami/redmine-4.0.4-5/apps/redmine/htdocs/config/routes.rb:364)
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at C:/Bitnami/redmine-4.0.4-5/apps/redmine/htdocs/config/routes.rb:364)

・redmineページ（エラーページ）表示後
>Started GET "/redmine/" for 127.0.0.1 at 2019-10-11 09:20:08 +0900
Processing by WelcomeController#index as HTML
  Current user: anonymous
Redirected to http://localhost:ポート番号/redmine/login?back_url=http%3A%2F%2Flocalhost%3Aポート番号%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 18ms (ActiveRecord: 9.5ms)
Started GET "/redmine/login?back_url=http%3A%2F%2Flocalhost%3Aポート番号%2Fredmine%2F" for 127.0.0.1 at 2019-10-11 09:20:08 +0900
Processing by AccountController#login as HTML
  Parameters: {"back_url"=>"http://localhost:ポート番号/redmine/"}
  Current user: anonymous
  Rendering account/login.html.erb within layouts/base
  Rendered account/login.html.erb within layouts/base (1.1ms)
Completed 500 Internal Server Error in 133ms (ActiveRecord: 10.9ms)
  
>ActionView::Template::Error (uninitialized constant RedmineViewCustomize::ViewHook::ViewCustomize):
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
    15: <%= heads_for_theme %>
    16: <%= call_hook :view_layouts_base_html_head %>
    17: 
    18: <%= yield :header_tags -%>
    19: </head>
  
>plugins/view-customize/lib/view_customize/view_hook.rb:13:in `view_layouts_base_html_head'
lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:61:in `each'
lib/redmine/hook.rb:61:in `block in call_hook'
lib/redmine/hook.rb:58:in `tap'
lib/redmine/hook.rb:58:in `call_hook'
lib/redmine/hook.rb:96:in `call_hook'
app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb__723152202_88487060'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

よろしくお願いします。

**Comment by onozaty** [comment]
プラグインのフォルダ名が間違えているようです。
`view-customize`ではなく`view_customize`としていただけますでしょうか。
