### ISSUE TITLE
Change position of issue custom field to top position in new issue form

### ISSUE THREAD

**Issue by lublasco** [onozaty/redmine-view-customize-scripts#24]
Hi, 

I want to position two custom fields (no. 23 & 24) on top of the new issue form, just after selecting the tracker type.

How could I achieve this with your plugin?

Thanks in advance for your help. I really appreciate it and consider your plugin very useful!

**Comment by onozaty** [comment]
Does that mean moving the position of the custom field?
If so, I think the following will be helpful.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/move_custom_filed_after_description.js

**Comment by lublasco** [comment]
Thanks a lot for your answer. Yes, I need to move a custom field (no. 23) not after description, but just right after tracker field. And I need this on the "new issue form". Is this possible?

**Comment by onozaty** [comment]
OK, can you try the following?

```javascript
$(function() {

  var customField = $('p:has(#issue_custom_field_values_23)');

  $('p:has(#issue_tracker_id)')
    .after(
      $('<div class="splitcontent">')
        .append(
          $('<div class="splitcontentleft">').append(customField)));
})
```

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/move_custom_filed_input_after_tracker.js

**Comment by lublasco** [comment]
This makes it! Thank you very much, onozaty! Great plugin!
