### ISSUE TITLE
Set today as due date when task status set to resolved

### ISSUE THREAD

**Issue by lublasco** [onozaty/redmine-view-customize-scripts#25]
Hi, onozaty

I'd need to set today as due date when task status is set to resolved (status id no. 6), but only for the case the due date hasn't got any value. Is this possible with your plugin?

Thanks again for your help! I think we all really appreciate your work and your plugin.

**Comment by onozaty** [comment]
Yes. Is possible.
I wrote a script, so please try it.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/set_today_to_due_date_when_resolved.js

**Comment by lublasco** [comment]
It's perfect, @onozaty !! Thank you very much!

**Comment by ashrafalzyoud** [comment]
not work
