### ISSUE TITLE
How change position and length view custome fields in issue form detail

### ISSUE THREAD

**Issue by pkokosak** [onozaty/redmine-view-customize-scripts#27]
Hello, please help me.  Sorry, but I have no experience with java script or css. Still, I'd like to use your plugin. I see no other option. I think your plugin is an elegant solution.

My environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.7.0-p0 (2019-12-25) [x86_64-darwin18]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2

My test setting custome fields in redmine: 
<img width="465" alt="image" src="https://user-images.githubusercontent.com/45127378/71718601-fd7c5500-2e1b-11ea-86d4-073ec8d6427b.png">

My screen new detail issues:
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/45127378/71719107-8c3da180-2e1d-11ea-9139-8bf997cf0a52.png">

How can I solve the following samples ?

<img width="764" alt="image" src="https://user-images.githubusercontent.com/45127378/71720187-1e937480-2e21-11ea-8c2b-eb1cedb3a37a.png">

<img width="754" alt="image" src="https://user-images.githubusercontent.com/45127378/71720397-e3de0c00-2e21-11ea-88dd-9497fa87a39f.png">

<img width="393" alt="image" src="https://user-images.githubusercontent.com/45127378/71720437-08d27f00-2e22-11ea-8844-cfcac7041dcf.png">

Thank you so much
Petr

**Comment by onozaty** [comment]
Hi @pkokosak 

Sorry for the late reply.
The first sample is below.

> How can I solve the following samples ?
> 
> <img alt="image" width="764" src="https://user-images.githubusercontent.com/45127378/71720187-1e937480-2e21-11ea-8c2b-eb1cedb3a37a.png">
> 

```javascript
/*
Path pattern: .*
Insertion position: Bottom of issue form
Type: JavaScript
*/
$(function() {

  const field1 = $('#issue_custom_field_values_1');
  const field2 = $('#issue_custom_field_values_2');
  const field3 = $('#issue_custom_field_values_3');

  // Change layout
  const content = $('<div class="splitcontent">')
    .append($('<div class="splitcontentleft">').append(field1.parent()))
    .append($('<div class="splitcontentleft">').append(field2.parent()))
    .append($('<div class="splitcontentright">').append(field3.parent()));

  $('#attributes').append(content);

  field1.css({
    'text-align': 'right',
    'width': '50px'
  });
  field2.css({
    'text-align': 'right',
    'width': '150px'
  });
  field3.css({
    'width': '250px'
  });
})
```

![image](https://user-images.githubusercontent.com/47337/72680441-3e9f8500-3afd-11ea-8a3b-1a19dfd96cbd.png)

**Comment by onozaty** [comment]
The second sample is below.

> <img alt="image" width="754" src="https://user-images.githubusercontent.com/45127378/71720397-e3de0c00-2e21-11ea-88dd-9497fa87a39f.png">
> 

```javascript
/*
Path pattern: .*
Insertion position: Bottom of issue form
Type: JavaScript
*/
$(function() {

  const field1 = $('#issue_custom_field_values_1');
  const field2 = $('#issue_custom_field_values_2');
  const field3 = $('#issue_custom_field_values_3');

  // Change layout
  const content1 = $('<div class="splitcontent">')
    .append($('<div class="splitcontentleft">').append(field1.parent()));
  const content2 = $('<div class="splitcontent">')
    .append($('<div class="splitcontentleft">').append(field2.parent()))
    .append($('<div class="splitcontentright">').append(field3.parent()));

  $('#attributes').append(content1);
  $('#attributes').append(content2);

  field1.css({
    'color': 'red'
  });
  field1.prev().css({
    'color': 'red'
  });
})
```

![image](https://user-images.githubusercontent.com/47337/72681734-c55a5f00-3b09-11ea-9c6a-d3948aaacdf0.png)

**Comment by onozaty** [comment]
The third sample is below.

> <img alt="image" width="393" src="https://user-images.githubusercontent.com/45127378/71720437-08d27f00-2e22-11ea-8844-cfcac7041dcf.png">
> 

```javascript
/*
Path pattern: .*
Insertion position: Bottom of issue form
Type: JavaScript
*/
$(function() {

  const field1 = $('#issue_custom_field_values_1');
  const field2 = $('#issue_custom_field_values_2');
  const field3 = $('#issue_custom_field_values_3');

  // Change layout
  const content1 = $('<div class="splitcontent">')
    .append($('<div class="splitcontentleft">').append(field1.parent()));
  const content2 = $('<div class="splitcontent">')
    .append($('<div class="splitcontentleft">').append(field2.parent()));
  const content3 = $('<div class="splitcontent">')
    .append($('<div class="splitcontentleft">').append(field3.parent()));

  $('#attributes').append(content1);
  $('#attributes').append(content2);
  $('#attributes').append(content3);

  field1.css({
    'text-align': 'right',
    'width': '50px'
  });
  field2.css({
    'text-align': 'right',
    'width': '150px'
  });
  field3.css({
    'width': '250px',
    'color': 'red'
  });
})
```

![image](https://user-images.githubusercontent.com/47337/72681777-3dc12000-3b0a-11ea-9079-1ccd0dacecb7.png)

Thanks.

**Comment by pkokosak** [comment]
Hello, thank you very much for you answer.

Please help me. How to change also in view for second example.

If you create new issue or edit I understand now how to do it.

Thank you very much
Petr

**Comment by onozaty** [comment]
> Please help me. How to change also in view for second example.

OK, Try the following.

```javascript
/*
Path pattern: .*
Insertion position: Bottom of issue detail
Type: JavaScript
*/
$(function() {

  const field1 = $('.cf_1.attribute');
  const field2 = $('.cf_2.attribute');
  const field3 = $('.cf_3.attribute');

  // Change layout
  const content1 = $('<div class="splitcontent">')
    .append($('<div class="splitcontentleft">').append(field1));
  const content2 = $('<div class="splitcontent">')
    .append($('<div class="splitcontentleft">').append(field2))
    .append($('<div class="splitcontentright">').append(field3));

  $('.issue.details .attributes').append(content1);
  $('.issue.details .attributes').append(content2);

  field1.css({
    'color': 'red'
  });
})
```

![image](https://user-images.githubusercontent.com/47337/72816186-1e152d80-3cab-11ea-9353-84ffdc30dbd1.png)

Thanks.

**Comment by pkokosak** [comment]
Hello, thank you very much for you answer. I understand all. The proposed solution is line by line. 
Please help me with my question. 

1. How to correctly add a border within individual items in a defined column. 

 For example :
<img width="669" alt="image" src="https://user-images.githubusercontent.com/45127378/72886228-b3dfa580-3d09-11ea-87fd-96c97b9074f1.png">


2. How can use fields without label ?
 For example (without label field A2):

<img width="564" alt="image" src="https://user-images.githubusercontent.com/45127378/72886650-7a5b6a00-3d0a-11ea-9c6a-60d387a1ec55.png">

Thank you very much
Petr

**Comment by onozaty** [comment]
> 1. How to correctly add a border within individual items in a defined column.
> 
> For example :
> <img alt="image" width="669" src="https://user-images.githubusercontent.com/45127378/72886228-b3dfa580-3d09-11ea-87fd-96c97b9074f1.png">
> 

Add Caption was not easy.

```javascript
/*
Path pattern: .*
Insertion position: Bottom of issue form
Type: JavaScript
*/
$(function() {

  const field1 = $('#issue_custom_field_values_1');
  const field2 = $('#issue_custom_field_values_2');
  const field3 = $('#issue_custom_field_values_3');

  // Change layout
  const leftContent = $('<div class="splitcontentleft">')
    .append(field1.parent())
    .append(field2.parent());
  const rightContent = $('<div class="splitcontentright">')
    .append(field3.parent());

  const content = $('<div class="splitcontent">')
    .append(leftContent)
    .append(rightContent);
    
  $('#attributes').append(content);

  leftContent.css({
    'border': '1px solid gray',
    'padding-left': '5px'
  });
  rightContent.css({
    'border': '1px solid gray',
    'padding-left': '5px'
  });
})
```

![image](https://user-images.githubusercontent.com/47337/73123022-719aba80-3fce-11ea-8d7f-ba1c6445a45d.png)

> 1. How can use fields without label ?
>    For example (without label field A2):
> 
> <img alt="image" width="564" src="https://user-images.githubusercontent.com/45127378/72886650-7a5b6a00-3d0a-11ea-9c6a-60d387a1ec55.png">
> 

```javascript
/*
Path pattern: .*
Insertion position: Bottom of issue form
Type: JavaScript
*/
$(function() {

  const field1 = $('#issue_custom_field_values_1');
  const field2 = $('#issue_custom_field_values_2');
  const field3 = $('#issue_custom_field_values_3');

  // Change layout
  const content1 = $('<div class="splitcontent">')
    .append($('<div class="splitcontentleft">').append(field1.parent()))
    .append($('<div class="splitcontentleft">').append(field2.parent()));

  const content2 = $('<div class="splitcontent">')
    .append($('<div class="splitcontentright">').append(field3.parent()));

  $('#attributes').append(content1);
  $('#attributes').append(content2);

  field2.prev().hide();
  field2.parent().css({
    'padding-left': '0px'
  });
})
```

![image](https://user-images.githubusercontent.com/47337/73123266-8462be80-3fd1-11ea-80dd-ecc48e6e423f.png)

Thanks

**Comment by pkokosak** [comment]
Thank you very much for all.

**Comment by onozaty** [comment]
You are welcome 😉
