### ISSUE TITLE
copy_image_from_clipboard.js + Redmine3.4.6

### ISSUE THREAD

**Issue by ryoji-takeuchi** [onozaty/redmine-view-customize-scripts#28]
With View customize 1.1.4 and Redmine3.4.6, copy_image_from_clipboard.js function not work. Only file is created from clipboard. Could you advice how to modify script to work with Redmine3.4.6?

**Comment by ryoji-takeuchi** [comment]
This behavior is different between Chrome and IE
Chrome 73.0.3683.86（Official Build） （64 bit）: Only file name is exist. link of picture is not created in form
IE11 (64bit) : Link of picture is not created and also file name is not exist.

**Comment by onozaty** [comment]
I tried it in the environment below.

* View customize 1.1.4
* Redmine3.4.5

Works fine at Chrome 79.0.3945.117.
This code does not support IE. IE could not implement it.

Thanks
