### ISSUE TITLE
Change custom fields view

### ISSUE THREAD

**Issue by msslava** [onozaty/redmine-view-customize-scripts#29]
Hello, could you please explain how to do the following:
1) Link 4 custom fields (I use the example from here - _https://github.com/onozaty/redmine-view-customize-scripts/blob/master/link_custom_field.js_ ,but there are only 2 custom fields. Can I combine 4 custom fields or more?)
2) if custom_field_1 is filled, then custom_field_2 becomes available for filling.

Is it possible?
Thanks!

**Comment by onozaty** [comment]
Hi @msslava 

What is the type of the custom field?
Is it a list box?

Thanks

**Comment by msslava** [comment]
Hi, **onozaty**! 
1) list with dropdown + number + number + text (for example)
2) if list with dropdown is filled (from first question) then custom field 2 (same as in the first question) ready to filling

**Comment by onozaty** [comment]
Hi @msslava 

Please try it because I wrote sample code.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/enable_when_custom_field_selected.js

![enabled](https://user-images.githubusercontent.com/47337/74104587-7304df00-4b99-11ea-83f9-fd4f3b8fab79.gif)

Thanks.

**Comment by msslava** [comment]
Sorry for the late reply.
This is a bit not what I wanted, but I seem to understand! Thanks!
Maybe you can tell me something else?
I am using the plugin https://github.com/frywer/custom_tables
to create tables with data. Custom fields are also used there.
I need to write (copy) data from custom fields to a table.
It seems that this is possible with your plugin.
Please tell me how to copy data from one custom field to another?

**Comment by msslava** [comment]
Sorry sir onozaty, I have one more question:
Is it possible to add a custom field to the context menu for editing (as text, not a list)?
You have the following script in your examples: 
https://github.com/onozaty/redmine-view-customize-scripts/blob/master/add_command_to_issues_context_menu.js
But I don’t quite understand how to add a custom text field to change there.
Thank you very much for your help!

**Comment by onozaty** [comment]
> Sorry for the late reply.
> This is a bit not what I wanted, but I seem to understand! Thanks!
> Maybe you can tell me something else?
> I am using the plugin https://github.com/frywer/custom_tables
> to create tables with data. Custom fields are also used there.
> I need to write (copy) data from custom fields to a table.
> It seems that this is possible with your plugin.
> Please tell me how to copy data from one custom field to another?

I looked at the plugin demo site.
What is the timing for copying?

Thanks.

**Comment by onozaty** [comment]
> Sorry sir onozaty, I have one more question:
> Is it possible to add a custom field to the context menu for editing (as text, not a list)?
> You have the following script in your examples:
> https://github.com/onozaty/redmine-view-customize-scripts/blob/master/add_command_to_issues_context_menu.js
> But I don’t quite understand how to add a custom text field to change there.
> Thank you very much for your help!

Where is the context menu displayed?
Displaying additional context menus and trying to modify custom fields is likely to be extensive code.

**Comment by msslava** [comment]
> > Sorry sir onozaty, I have one more question:
> > Is it possible to add a custom field to the context menu for editing (as text, not a list)?
> > You have the following script in your examples:
> > https://github.com/onozaty/redmine-view-customize-scripts/blob/master/add_command_to_issues_context_menu.js
> > But I don’t quite understand how to add a custom text field to change there.
> > Thank you very much for your help!
> 
> Where is the context menu displayed?
> Displaying additional context menus and trying to modify custom fields is likely to be extensive code.

I mean the context menu on the main page with issues.  Now all the custom fields (such as a list) appear there.  I would like to insert a custom field like text and the ability to change it.

**Comment by msslava** [comment]
> > Sorry for the late reply.
> > This is a bit not what I wanted, but I seem to understand! Thanks!
> > Maybe you can tell me something else?
> > I am using the plugin https://github.com/frywer/custom_tables
> > to create tables with data. Custom fields are also used there.
> > I need to write (copy) data from custom fields to a table.
> > It seems that this is possible with your plugin.
> > Please tell me how to copy data from one custom field to another?
> 
> I looked at the plugin demo site.
> What is the timing for copying?
> 
> Thanks.

1) I create a issue and fill a custom field.  
2) I open the created issue and in one of the plugin field with tables the value from the custom field should appear

**Comment by onozaty** [comment]
> > > Sorry sir onozaty, I have one more question:
> > > Is it possible to add a custom field to the context menu for editing (as text, not a list)?
> > > You have the following script in your examples:
> > > https://github.com/onozaty/redmine-view-customize-scripts/blob/master/add_command_to_issues_context_menu.js
> > > But I don’t quite understand how to add a custom text field to change there.
> > > Thank you very much for your help!
> > 
> > 
> > Where is the context menu displayed?
> > Displaying additional context menus and trying to modify custom fields is likely to be extensive code.
> 
> I mean the context menu on the main page with issues. Now all the custom fields (such as a list) appear there. I would like to insert a custom field like text and the ability to change it.

You can use Redmine REST API to update custom fields, but it seems difficult to do that from the context menu.

* https://www.redmine.org/projects/redmine/wiki/Rest_Issues

There are problem such as how to display input forms.

**Comment by onozaty** [comment]
> * I create a issue and fill a custom field.
> * I open the created issue and in one of the plugin field with tables the value from the custom field should appear

Thank you for the explanation.
I looked at the behavior of the plugin on the demo site, but couldn't think of a way to do this.

How about suggesting to the plugin creator?

I'm sorry I couldn't help you.

**Comment by msslava** [comment]
> > > > Sorry sir onozaty, I have one more question:
> > > > Is it possible to add a custom field to the context menu for editing (as text, not a list)?
> > > > You have the following script in your examples:
> > > > https://github.com/onozaty/redmine-view-customize-scripts/blob/master/add_command_to_issues_context_menu.js
> > > > But I don’t quite understand how to add a custom text field to change there.
> > > > Thank you very much for your help!
> > > 
> > > 
> > > Where is the context menu displayed?
> > > Displaying additional context menus and trying to modify custom fields is likely to be extensive code.
> > 
> > 
> > I mean the context menu on the main page with issues. Now all the custom fields (such as a list) appear there. I would like to insert a custom field like text and the ability to change it.
> 
> You can use Redmine REST API to update custom fields, but it seems difficult to do that from the context menu.
> 
> * https://www.redmine.org/projects/redmine/wiki/Rest_Issues
> 
> There are problem such as how to display input forms.

Thanks for the help mister Onozaty.  I am using the plugin tags now for it (https://www.redmineup.com/pages/plugins/tags). It works like a text box similar to a custom field text and integrates into the context menu as I need.. But it is limited in customization.  I thought to implement something similar through your plugin.  But if there are no options, well, thanks for explaining!

**Comment by onozaty** [comment]
View customize is a plug-in for customizing the display contents, so customizing such editing is not easy.

By combining REST API, it is possible to realize a function that can be edited even with View customize plugin. However, if it is a big function, it is recommended to implement it as a Redmine plugin.

Thanks.

**Comment by msslava** [comment]
Thanks for the help!
