### ISSUE TITLE
Popup window message

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#31]
can u help me to create popup alert msg when due date come
for all issue

**Comment by onozaty** [comment]
Please tell me when to display the popup.
Is it when the Issue page is displayed?

If the popup is displayed, the operation will be deprived, so isn't it inconvenient?
I think that changing the color is also effective.

**Comment by ashrafalzyoud** [comment]
no need colour ineed like alaram msg when due date come in 4 days as example

**Comment by onozaty** [comment]
Sorry, I still don't understand what you want to do.
On which Redmine page do you want to display alerts?

**Comment by ashrafalzyoud** [comment]
issues page, when cfs(10) its colser
i need alaram msg tell me remain 3 or 4 days

**Comment by onozaty** [comment]
Try the following, Try the following, This is a sample that displays alert three days before the due date.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/show_alert_on_due_date.js

![image](https://user-images.githubusercontent.com/47337/77765435-9a4c3880-7081-11ea-9a89-192679bd3ae7.png)

**Comment by ashrafalzyoud** [comment]
thx brother
1-but i need it depend in cfs custom field(date) not in due date
2- can i change the form for alarm msg

**Comment by onozaty** [comment]
> thx brother
> 1-but i need it depend in cfs custom field(date) not in due date

Specify a custom field as shown below.

`const dueDateArray = $('#issue_custom_field_values_1').val().split('-');`

Please change the number part of `issue_custom_field_values_1` according to the ID of the custom field.

> 2- can i change the form for alarm msg

Please change the following.

`$('#content').prepend('<div class="warning">It is only ' + daysLeft + ' days until the due date.</div>');`

Thanks.

**Comment by ashrafalzyoud** [comment]
days lift  its calcualted
time.now -cfs[1]
in your formula the msg its fixed 3 days
i need the msg reaming day

**Comment by ashrafalzyoud** [comment]
@onozaty  if u can help me

**Comment by ashrafalzyoud** [comment]
cfs10 =  $('#issue_custom_field_values_47').val().split('-');
datenow= $ . Datepicker . formatDate ( 'Yy-Mm-Dd' ,  New  Date ( ) ) ;
days _remaining = datenow-cfs10 ----> days
if  days_remaing > .....error
                          < ......error

**Comment by onozaty** [comment]
I think you can calculate the number of days with the following.

```javascript
const cfDate = new Date($('#issue_custom_field_values_47').val());
const now = new Date();
const nowDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
const daysRemaining = (cfDate - nowDate) / 86400000;
if (daysRemaining <= daysLeft) {
  $('#content').prepend('<div class="warning">There are only ' + daysRemaining + ' days left until the deadline.</div>');
}
```

**Comment by ashrafalzyoud** [comment]
@onozaty  no output come

$(function() {

const daysLeft = 3;
const cfDate = new Date($('#issue_custom_field_values_47').val());
const now = new Date();
const nowDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
const daysRemaining = (cfDate - nowDate) / 86400000;
if (daysRemaining <= daysLeft) {
  $('#content').prepend('<div class="warning">There are only ' + daysRemaining + ' days left until the deadline.</div>');
}

})

**Comment by ashrafalzyoud** [comment]
the msg give not number of days
There are only 1.875 days left until the deadline.
i think its take hours or something like that

**Comment by ashrafalzyoud** [comment]
![time](https://user-images.githubusercontent.com/50211455/90315690-0989d280-df26-11ea-99ce-ab25f1bc0bf2.png)
first line = nowDate
secound line = cfs[47]
third line = daysRemaining
i think its calculate the hours or +GMT

**Comment by onozaty** [comment]
TimeZone couldn't be considered.
Please try the following.

```javascript
$(function() {

  const daysLeft = 3;

  const cfDateArray = $('#issue_custom_field_values_47').val().split('-');
  const cfDate = new Date(cfDateArray [0], cfDateArray [1] - 1, cfDateArray [2]);
  const now = new Date();
  const nowDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const daysRemaining = (cfDate - nowDate) / 86400000;

  if (daysRemaining <= daysLeft) {
    $('#content').prepend('<div class="warning">There are only ' + daysRemaining + ' days left until the deadline.</div>');
  }

})
```

![image](https://user-images.githubusercontent.com/47337/90315765-f6442a80-df58-11ea-933e-7ed5a56fd01f.png)

**Comment by ashrafalzyoud** [comment]
thx man for your support
but i want edit this formula like that
`$(function() {

  const daysLeft = 3;
  const daysleft1 = 7;

  const cfDateArray = $('#issue_custom_field_values_47').val().split('-');
  const cfDate = new Date(cfDateArray [0], cfDateArray [1] - 1, cfDateArray [2]);
  const now = new Date();
  const nowDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const daysRemaining = (nowDate- cfDate) / 86400000;

  if (daysRemaining <= daysLeft) {
    $('#content').prepend('<div class="warning">aaaaaa ' + daysRemaining + ' days left until the deadline.</div>');
  }
  if (daysRemaining <= daysLeft1) {
    $('#content').prepend('<div class="warning">bbbbbb ' + daysRemaining + ' days left until the deadline.</div>');
  }
if (daysRemaining => daysLeft1) {
    $('#content').prepend('<div class="warning">ccccc' + daysRemaining + ' days left until the deadline.</div>');
  }

})

`
1 - if u can edit this formula like i want plz
2- how i can give color for every warning ( red,orange,green)
 daysRemaining < 3  red
daysRemaining  3<7  orange
daysRemaining  > 7 green

**Comment by ashrafalzyoud** [comment]
@onozaty 
![12121212](https://user-images.githubusercontent.com/50211455/90317491-a0f52280-df32-11ea-9036-f2f990161438.png)
but no any output come
and i need color for every condition

**Comment by ashrafalzyoud** [comment]
when i put date cfs [47] =06/09/2020
its give message  " 752 days left until the deadline."    TRUE
when i put date cfs [47] =28/03/2020
its give message  " -140 days left until the deadline"    TRUE
when i put date cfs [47] =27/03/2020
its give message  " -140.95833333333334 days left until the deadline"    FALSE
when i put date cfs [47] =01/01/2020
its give message  " -226.95833333333334 days left until the deadline."    FALSE
-------------------------------
before 28/3/2020 its work good
after this date its false
strange

**Comment by ashrafalzyoud** [comment]
im answer it
thx @onozaty 
 const daysRemaining = Math.ceil((cfDate- nowDate) / 86400000);

**Comment by ashrafalzyoud** [comment]
im try to put this condition WHEN issue close


  if ($('#issue_status_id').val() == '20' ) {
     $('#content').prepend('<div class="warning">  TASK FINISH</div>');
 else(daysRemaining <= daysLeft) {
    $('#content').prepend('<div class="warning">There are only ' + daysRemaining + ' days left until the deadline.</div>');
  }
---------------------------
its not working i think no value get from status_id
im work like #25 buts not working also

**Comment by onozaty** [comment]
How to get the status seems correct.
Is `20` the status you want to finish?

**Comment by ashrafalzyoud** [comment]
yes but no any result

**Comment by onozaty** [comment]
Does `$('#issue_status_id').val()` return empty?

**Comment by ashrafalzyoud** [comment]
undefind no any output

**Comment by onozaty** [comment]
that's strange.
If the screen being executed is the issue display screen, this code should be able to get the value.

**Comment by ashrafalzyoud** [comment]
Can u try it ?

**Comment by onozaty** [comment]
The "else" part may be wrong.
You must write it with "else if" instead of "else".

```js
  if ($('#issue_status_id').val() == '5') {
    $('#content').prepend('TASK FINISH');
  } else if (daysRemaining <= daysLeft) {
    $('#content').prepend('<div class="warning">There are only ' + daysRemaining + ' days left until the deadline.</div>');
  }
```

**Comment by ashrafalzyoud** [comment]
U test it?!

**Comment by onozaty** [comment]
> U test it?!

Yes.
The ID matches my environment.

```js
$(function() {

  const daysLeft = 3;

  const cfDateArray = $('#issue_custom_field_values_1').val().split('-');
  const cfDate = new Date(cfDateArray [0], cfDateArray [1] - 1, cfDateArray [2]);
  const now = new Date();
  const nowDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const daysRemaining = (cfDate - nowDate) / 86400000;

  if ($('#issue_status_id').val() == '5') {
    $('#content').prepend('TASK FINISH');
  } else if (daysRemaining <= daysLeft) {
    $('#content').prepend('<div class="warning">There are only ' + daysRemaining + ' days left until the deadline.</div>');
  }

})
```

![image](https://user-images.githubusercontent.com/47337/90384126-07f21300-e0bc-11ea-9948-a7b70f894a4b.png)

![image](https://user-images.githubusercontent.com/47337/90384352-5f907e80-e0bc-11ea-8779-bda8cab00664.png)

![image](https://user-images.githubusercontent.com/47337/90384399-6f0fc780-e0bc-11ea-8798-59d1673ed44b.png)

**Comment by ashrafalzyoud** [comment]
perfect perfect
i close the ticket
