### ISSUE TITLE
hide custom field when i click check box

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#34]
can u help me like this
if u see the pics
![w](https://user-images.githubusercontent.com/50211455/90445948-2c181900-e0e9-11ea-9a65-2bab89b5d0bf.png)
![ww](https://user-images.githubusercontent.com/50211455/90445952-2d494600-e0e9-11ea-9e08-06cacb05f350.png)
 the first name,second name ,... hide when i click company

**Comment by onozaty** [comment]
Please refer to the following.

https://github.com/onozaty/redmine-view-customize-scripts/blob/master/disable_text_depending_on_checked.js

**Comment by ashrafalzyoud** [comment]
checkbox i can create in boolean??

**Comment by ashrafalzyoud** [comment]
IM TRY this code but not work
im create custom field boolean display check box
but not working

**Comment by onozaty** [comment]
![チェックボックス](https://user-images.githubusercontent.com/47337/90991695-2a1cf100-e5e6-11ea-890e-9382d2a8a04d.gif)

If you want to switch between show and hide, please use the 'hide' and 'show' methods.

```js
$(function() {

  const checkbox = $('#issue_custom_field_values_2');
  const text = $('#issue_custom_field_values_3');

  function changeEnableText() {
    if (checkbox.prop('checked')) {
      text.parent().hide();
    } else {
      text.parent().show();
    }
  }

  checkbox.on('change', changeEnableText);

  changeEnableText();
});```

**Comment by ashrafalzyoud** [comment]
i need curom_field _3 hide not value
not appear when i click like picture up
when click company all custom field( firstname,secound name,,) hide

**Comment by onozaty** [comment]
With the code above, you can switch between show and hide as shown below.
Is it different from what you want to do?

![チェックボックス2](https://user-images.githubusercontent.com/47337/91007263-754ef800-e616-11ea-9935-818ab594962e.gif)

Please change the custom field ID accordingly.

**Comment by ashrafalzyoud** [comment]
give me code for above for hide custom field all not value like the pic above

**Comment by onozaty** [comment]
I don't know what is present for all custom fields.

For something you want to erase, try adding code like the one below.

```js
  function changeEnableText() {
    if (checkbox.prop('checked')) {
      $('#issue_custom_field_values_3').parent().hide();
      $('#issue_custom_field_values_4').parent().hide();
      $('#issue_custom_field_values_5').parent().hide();
    } else {
      $('#issue_custom_field_values_3').parent().show();
      $('#issue_custom_field_values_4').parent().show();
      $('#issue_custom_field_values_5').parent().show();
    }
  }

```

**Comment by ashrafalzyoud** [comment]
perfect brother thx for you
