### ISSUE TITLE
INNER HTML

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#35]
how i can use your pluginto copy/paste using inner html
from
(( 
<   td class="contacts"><span class="contact"><a id="avatar" href="/contacts/7?project_id=tttttttttt"><img class=" gravatar" src="/attachments/contacts_thumbnail/876/16x16" width="16" height="16"></a> <a href="/contacts/7?project_id=tttttttttt">@company 1</a></span></td>
))
TO
((
<td class="cf_396 company">   @company 1</td>
))

![1](https://user-images.githubusercontent.com/50211455/90959249-8676f800-e4a2-11ea-9e13-e1f1f429afdc.png)

![2222](https://user-images.githubusercontent.com/50211455/90959252-8840bb80-e4a2-11ea-818d-f53e8f2b88e7.png)

im try it manualy its work by using copy/paste inner html
![44444](https://user-images.githubusercontent.com/50211455/90959322-0309d680-e4a3-11ea-9ea5-0f32249e2b5e.png)

i need  be like that
(( <      td class="cf_396 company"><a id="avatar" href="/contacts/7?project_id=tttttttttt"><img class=" gravatar" src="/attachments/contacts_thumbnail/876/16x16" width="16" height="16"></a> <a href="/contacts/7?project_id=tttttttttt">@company 1</a></td>))

**Comment by ashrafalzyoud** [comment]
im try this code but not working
 $(function() {   
var x = document.getElementById("contacts").innertext; 
document.getElementById("cf_396 company").innertext = x;
 });

**Comment by onozaty** [comment]
Does it mean copying the contents of "Contacts" to "Name-company"?

Must be processed row by row.

**Comment by ashrafalzyoud** [comment]
how i can do it??

**Comment by onozaty** [comment]
I think the code looks like this.

```js
$(function() {

  $('.cf_396').each(function(index, elm) {
    const from = $(elm);
    const to = from.parent().find('.subject');

    to.html(from.html());
  })
});
```

You need knowledge about JavaScript and DOM, not knowledge about View customize.
If customization becomes complicated, it would be nice to have an engineer from the same team with such knowledge follow you.
