### ISSUE TITLE
Administrator

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#36]
thx for your perfect plugin
i need your help about Administrators
1- i dont need any administraor delete the super admin ( user_id=1) i want hide ( lock and delete buttom ) in main page users
2- can i hide some from the menu admin for (user_id=10)
 ( workflow,Enumerations,Settings) and allow him for another menu

**Comment by onozaty** [comment]
I'm sorry, I may not understand the first mission.
Does that mean you want to hide the lock and delete button for all users?

**Comment by ashrafalzyoud** [comment]
hide the lock and delete button for super admin (user_id=1) for all another administrators
this mean if  another admin  (user_id=2) he cant delete the super admin (user_id=1)

**Comment by onozaty** [comment]
Thank you for your explanation.

I think you can, but it takes time to think.
I'm busy with other things, so I can't afford to spend much time. Therefore, it may take time to reply.

Thanks.

**Comment by onozaty** [comment]
> hide the lock and delete button for super admin (user_id=1) for all another administrators
this mean if another admin (user_id=2) he cant delete the super admin (user_id=1)

Try the following.
* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/hide_lock_button_and_delete_button.css

For the No.2, please wait a little longer.

**Comment by onozaty** [comment]
> For the No.2, please wait a little longer.

Try the following.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/hide_part_of_admin_menu.js

**Comment by robertotsi** [comment]
Onozaty, 

Can i do this based on roles?

**Comment by robertotsi** [comment]
> Onozaty,
> 
> Can i do this based on roles?

I've done it! 
I put that: if (ViewCustomize.context.project.roles.id != 3)

Thanks!!!

**Comment by robertotsi** [comment]
> > Onozaty,
> > Can i do this based on roles?
> 
> I've done it!
> I put that: if (ViewCustomize.context.project.roles.id != 3)
> 
> Thanks!!!

@onozaty I think, I was wrong.
Can you help me with this situation?

I need to disabled a field when a role is different from number 3.

**Comment by onozaty** [comment]
Hi @robertotsi 

The code will look like the following.
```javascript
if (!ViewCustomize.context.project.roles.some(function(role) { return role.id == 3 })) {
  // disabled a field
}
```

**Comment by robertotsi** [comment]
> Hi @robertotsi
> 
> The code will look like the following.
> 
> ```js
> if (!ViewCustomize.context.project.roles.some(function(role) { return role.id == 3 })) {
>   // disabled a field
> }
> ```

Worked! Tks @onozaty
