### ISSUE TITLE
Option to configure which trackers can be set as subtasks for each tracker 

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#37]
Thanks for your cooperation, good deal, and great effort
I WANNA ask if your plugin help to do this function or no?

how i can configure when i added subtask
if Tracker 1 just only available subtask Tracker 10 and Tracker 11( hide all trackers)
if Tracker 2 just only available subtask Tracker 12 and Tracker 13 (hide all trackers)

**Comment by onozaty** [comment]
I think it's difficult.
This is because the REST API must be used to get the tracker information of the parent task when adding a subtask.

Also, the ID of the parent task can be changed, so it is difficult to maintain consistency.

Thanks.

**Comment by ashrafalzyoud** [comment]
ok thx brother
