### ISSUE TITLE
При изменении родительского поля зависимое поле сохраняет предыдущее значение.

### ISSUE THREAD

**Issue by maksnet2** [onozaty/redmine-view-customize-scripts#38]
Добрый день.
Создал зависимые настраиваемые поля с скриптом https://github.com/onozaty/redmine-view-customize-scripts/blob/master/link_custom_field.js.
Но есть проблема: при повторном редактировании задачи, при смене значения в родительском поле, если при этом не трогать подчиненное поле, то там сохраняется предыдущее значение. 
Необходимо при смене значения в родительском поле не только очищать подчиненное поле (это есть), но и заполнять каким-то значением по умолчанию (которое можно задать в списке подчиненного поля, общее для всех). Было бы неплохо сделать так: если список зависимых значений пуст - подставлять значение по умолчанию, если не пуст - запрещать сохранение задачи без выбора зависимого значения. 
Ну или хотя бы просто запрещать сохранение задачи, если значение не выбрано.
Помогите пожалуйста, сам не силен.

Скрипт, используемый мной:
```
// カスタムフィールドを連動させる(親の値に応じて、子を絞り込む)
// 
// Path pattern: /issues/
// Type: JavaScript
$(function() {

  var parentFieldId = 'issue_custom_field_values_2';
  var childFieldId = 'issue_custom_field_values_63';

  // 表示条件
  var isTarget = function(child, parent) {
    // 前方一致のものを対象に
    return child.text().indexOf(parent.text()) == 0;
  }

  // 子フィールドの絞り込み
  var narrowChildField = function() {

    // 親で選択している項目
    var parentSelected = $('#' + parentFieldId + ' > option:selected');

    $('#' + childFieldId + ' > option').each(function() {

      var child = $(this);

      // 一致したものだけに絞り込む
      // (IEの場合はoptionがdisplay:noneで非表示にならないのでdisabledで選択不可に)
      if (isTarget(child, parentSelected)) {
        child.show();
        child.prop('disabled', false);
      } else {
        child.hide();
        child.prop('disabled', true);
      }
    });
  }

  // 現時点のもので子を絞り込み
  narrowChildField();

  // 親フィールドが変わった際に子フィールドを絞り込み
  $('#all_attributes').change(function(e) {
    if (e.target.id == parentFieldId) {
      $('#' + childFieldId).val(''); // moved here
      narrowChildField();
    }
  });

  // ステータス変更時などにDOMが差し替えられるので
  // フォームの内容が書き変わるたびに絞り込みを反映
  var _replaceIssueFormWith = replaceIssueFormWith;
  replaceIssueFormWith = function(html){

    _replaceIssueFormWith(html);

    narrowChildField();
  };
});
```

**Comment by onozaty** [comment]
hi @maksnet2 

What will be the default value?
Is it the first value?

Thanks.

**Comment by maksnet2** [comment]
> What will be the default value?
'--'
> Is it the first value?
Да, это самое первое значение в общем списке

**Comment by onozaty** [comment]
Is it correct that '--' means it is always selectable?

For example, if a parent has
* A
* B

child has

* --
* A-1
* A-2
* B-1
* B-2

If the parent chooses A, the child can choose

* --
* A-1
* A-2

**Comment by maksnet2** [comment]
Да, именно так. У некоторых значений родительского поля нет связанных значений в подчиненном поле, но подчинённые поле должно быть обязательным, поэтому нужно какое-то нейтральное значение. Подошла бы и просто очистка, но тогда не заменяется предыдущее значение при повторном выборе, что и послужило причиной моего обращения.

**Comment by onozaty** [comment]
Can you please try the following?

```javascript
$(function() {

  var parentFieldId = 'issue_custom_field_values_2';
  var childFieldId = 'issue_custom_field_values_63';

  // 表示条件
  var isTarget = function(child, parent) {
    // 前方一致のものを対象に
    return child.val() == "" || child.text().indexOf(parent.text()) == 0;  // change
  }

  // 子フィールドの絞り込み
  var narrowChildField = function() {

    // 親で選択している項目
    var parentSelected = $('#' + parentFieldId + ' > option:selected');

    $('#' + childFieldId + ' > option').each(function() {

      var child = $(this);

      // 一致したものだけに絞り込む
      // (IEの場合はoptionがdisplay:noneで非表示にならないのでdisabledで選択不可に)
      if (isTarget(child, parentSelected)) {
        child.show();
        child.prop('disabled', false);
      } else {
        child.hide();
        child.prop('disabled', true);
        child.removeAttr('selected'); // add
      }
    });
  }

  // 現時点のもので子を絞り込み
  narrowChildField();

  // 親フィールドが変わった際に子フィールドを絞り込み
  $('#all_attributes').change(function(e) {
    if (e.target.id == parentFieldId) {
      narrowChildField();
    }
  });

  // ステータス変更時などにDOMが差し替えられるので
  // フォームの内容が書き変わるたびに絞り込みを反映
  var _replaceIssueFormWith = replaceIssueFormWith;
  replaceIssueFormWith = function(html){

    _replaceIssueFormWith(html);

    narrowChildField();
  };
});
```

**Comment by maksnet2** [comment]
Иногда автоматически подставляет первое из значений дочернего поля, иногда не подставляет (поле остается пустым) и тогда все по прежнему

**Comment by onozaty** [comment]
I do not know what kind of action you are expecting.
Could you please try it based on the code I provided?

**Comment by onozaty** [comment]
I thought the following behavior was what you were expecting.
![issue-38](https://user-images.githubusercontent.com/47337/107375055-acb15280-6b2b-11eb-9173-1bb9cbf73123.gif)

**Comment by maksnet2** [comment]
Я заметил, что у меня версия плагина вашего 2,5, а есть 2,8. Обновлю, попробую еще.

**Comment by onozaty** [comment]
Okay.
If it doesn't seem to work, please explain with a screen captures, so we can figure out what's going on.

Thanks.

**Comment by maksnet2** [comment]
Обновил плагин - не помогло. Видео прикладываю. Может в настройках полей что-то? Версия Redmine важен? У меня 3.4.13. И строки с "--" нет в списке.
https://user-images.githubusercontent.com/19895894/107557367-90281f80-6bea-11eb-95bd-5fed933469af.mp4

**Comment by onozaty** [comment]
Thank you for the information.
The version of Redmine may have something to do with it.

Could you please tell me the following?

* What is the browser you are using?
* What was the code you used to take this video?

**Comment by maksnet2** [comment]
> * Какой браузер вы используете?

Основной - Cent (на хромиуме), проверял на chrome и firefox

> * Какой код вы использовали для этого видео?

Код из комментария https://github.com/onozaty/redmine-view-customize-scripts/issues/38#issuecomment-775928034

Может быть настройки полей еще влияют?

**Comment by onozaty** [comment]
I tried the same conditions, and it works fine here.

![image](https://user-images.githubusercontent.com/47337/107625749-223e2f80-6ca0-11eb-9ea3-fb84af48b124.png)

There was no problem with both Chrome and Firefox.

Please let me know the field settings as well.

**Comment by maksnet2** [comment]
![image](https://user-images.githubusercontent.com/19895894/107633299-33c40f00-6c81-11eb-9128-955d985b39d1.png)

Для самообучения: где в вашем коде разрешается показ "--"?

**Comment by maksnet2** [comment]
Немного отвлеченный вопрос: с помощью вашего плагине же нельзя вытащить и отобразить информацию из поля справочников? например в задаче вытащить содержимое одного из полей проекта, в котором задача создана.

**Comment by onozaty** [comment]
> Для самообучения: где в вашем коде разрешается показ "--"?

`child.val() == ""`  is the relevant part.

```js
  // 表示条件
  var isTarget = function(child, parent) {
    // 前方一致のものを対象に
    return child.val() == "" || child.text().indexOf(parent.text()) == 0;  // change
  }
```

If you disable View customize, will the "--" still show up?

**Comment by onozaty** [comment]
> Немного отвлеченный вопрос: с помощью вашего плагине же нельзя вытащить и отобразить информацию из поля справочников? например в задаче вытащить содержимое одного из полей проекта, в котором задача создана.

You may be able to use Redmine's REST API to do what you want.
However, it requires programming knowledge, so it is not recommended.

If you have someone close to you who can program, it would be a good idea to ask them to support you.

**Comment by maksnet2** [comment]
> > Немного отвлеченный вопрос: с помощью вашего плагине же нельзя вытащить и отобразить информацию из поля справочников? например в задаче вытащить содержимое одного из полей проекта, в котором задача создана.
> 
> You may be able to use Redmine's REST API to do what you want.
> However, it requires programming knowledge, so it is not recommended.
> 
> If you have someone close to you who can program, it would be a good idea to ask them to support you.

ОК. хорошо.

**Comment by maksnet2** [comment]
> > Для самообучения: где в вашем коде разрешается показ "--"?
> 
> `child.val() == ""` is the relevant part.
> 
> ```js
>   // 表示条件
>   var isTarget = function(child, parent) {
>     // 前方一致のものを対象に
>     return child.val() == "" || child.text().indexOf(parent.text()) == 0;  // change
>   }
> ```

Так и думал.  А там разве не `child.val() == "--"` должно быть? Ну правда я так тоже пробовал - не помогло.

> If you disable View customize, will the "--" still show up?

А как отключить? А, понял

**Comment by maksnet2** [comment]
> If you disable View customize, will the "--" still show up?

![image](https://user-images.githubusercontent.com/19895894/107636319-e4341200-6c85-11eb-9641-e8b416207bbc.png)

**Comment by maksnet2** [comment]
Получилось!!
Изменил на `child.text() == '--'` и все заработало.
```js
  var isTarget = function(child, parent) {
    // 前方一致のものを対象に
    return child.text() == '--' || child.text().indexOf(parent.text()) == 0;  // change
  }
```

**Comment by onozaty** [comment]
I see, I thought it was the default "--", but there was a "--" option.

I looked at it in Russian, and it was definitely different.

![image](https://user-images.githubusercontent.com/47337/107637146-02633780-6cb1-11eb-844f-74b48f63467f.png)

I'm glad you solved it.

**Comment by maksnet2** [comment]
> Понятно, я думал, что это по умолчанию «-», но был вариант «-».
> 
> Я посмотрел на него по-русски, и он определенно был другим.
> 

Я понял Вас, Ваш вариант намного лучше, это я пытался сделать сначала сам, потом переделал и забыл.
Вот только вопрос: если в родительском поле выбрать "С", в дочернем поле нет значений для этого родительского значения, как сохранить какое-то нейтральное значение?

**Comment by maksnet2** [comment]
Вернул назад:
```js
  var isTarget = function(child, parent) {
    // 前方一致のものを対象に
    return child.val() == "" || child.text().indexOf(parent.text()) == 0;  // change
  }
```

Изменил немного:
```js
  var narrowChildField = function() {

    // 親で選択している項目
    var parentSelected = $('#' + parentFieldId + ' > option:selected');

    $('#' + childFieldId + ' > option').each(function() {

      var child = $(this);

      // 一致したものだけに絞り込む
      // (IEの場合はoptionがdisplay:noneで非表示にならないのでdisabledで選択不可に)
      if (child.text() == '-----') {
        child.show();
        child.prop('disabled', false);
        child.removeAttr('selected');
      } else if (isTarget(child, parentSelected)) {
        child.show();
        child.prop('disabled', false);
      } else {
        child.hide();
        child.prop('disabled', true);
        child.removeAttr('selected'); // add
      }
    });
  }
```

Отлично работает

**Comment by maksnet2** [comment]
@onozaty , Спасибо за помощь и терпение.  Удачи во всем :)


https://user-images.githubusercontent.com/19895894/107641486-20b73c00-6c8d-11eb-9fc1-d3c7480a915b.mp4

**Comment by onozaty** [comment]
😄
