### ISSUE TITLE
Работа скрипта с полями от плагина CRM

### ISSUE THREAD

**Issue by maksnet2** [onozaty/redmine-view-customize-scripts#39]
Добрый день.
Есть еще один вопрос по скрипту https://github.com/onozaty/redmine-view-customize-scripts/blob/master/link_custom_field.js, не могу понять в чем дело, был бы очень благодарен за помощь.
Мы используем плагин https://www.redmineup.com/pages/plugins/crm. Он добавляет типы полей "Компания" и "Контакт". Родительскому полю ставлю тип "Компания", а подчиненному тип "список" - с этим все хорошо. Если подчиненному полю ставлю тип "Контакт", то скрипт перестает работать.  Вероятно дело в реализации типа "Контакт". 
Можете ли Вы посмотреть и подсказать, как изменить скрипт для работы с типом "Контакт"?

Если нужна еще информация, предоставлю.

**Comment by maksnet2** [comment]
![image](https://user-images.githubusercontent.com/19895894/107368872-81fad600-6afa-11eb-89c1-b5c15cb498aa.png)

**Comment by onozaty** [comment]
I think it is due to the different types, but I am not sure what other plugins do.
If I specify "Контакт", what will it look like on the Issue screen?

**Comment by maksnet2** [comment]
> I think it is due to the different types, but I am not sure what other plugins do.
> If I specify "Контакт", what will it look like on the Issue screen?

![image](https://user-images.githubusercontent.com/19895894/107371743-0f8bf500-6afe-11eb-9cdd-1f8f4345f219.png)

**Comment by maksnet2** [comment]
> I think it is due to the different types, but I am not sure what other plugins do.
> If I specify "Контакт", what will it look like on the Issue screen?

У них можно скачать бесплатную версию плагина. Можете ли Вы попробовать?
Может вам дать скриншот из панели разработчика в браузере?

**Comment by onozaty** [comment]
I'm sorry.
We do not have enough time to support the combination with other plugins.

**Comment by maksnet2** [comment]
Понял. Все равно спасибо за ваш плагин и помощь.

**Comment by onozaty** [comment]
I had a demo, so I checked the screen.

* http://demo.redmineup.com/projects/contacts-plugin/contacts

Since it was loaded dynamically, it seemed that it could not be controlled by view customize.

I'm sorry I can't help you.

**Comment by maksnet2** [comment]
Жаль. Спасибо, что пытались помочь :)
