### ISSUE TITLE
How can I set default value when I change the status_id to refused in the issue list context menu?

### ISSUE THREAD

**Issue by archonwang** [onozaty/redmine-view-customize-scripts#4]
Hi, @onozaty

Could you tell me how to set default value  when I change the status_id to refused in the issue list context menu? 

for example, I want to set the fixed_version_id to null(""), when I set the status to refused (status_id = 6)  with context menu on the issue list.

Thanks so much.

**Comment by onozaty** [comment]
Hi @archonwang

Please try the following.

``` javascript
/*
Path pattern: /issues$
Type: JavaScript
*/
$(function() {

  jQuery.fn._show = jQuery.fn.show;

  jQuery.fn.show = function() {
    if (this.attr('id') == 'context-menu') {
      var a = $('#context-menu a[href*="status_id%5D=6"]');
      a.attr('href',a.attr('href') + '&issue%5Bfixed_version_id%5D=none');
    }

    return jQuery.fn._show.apply(this, arguments);
  };
});
```

**Comment by archonwang** [comment]
@onozaty, it worked. Thanks.

I tested it on Redmine 3.3.1, mysql.
