### ISSUE TITLE
How can i do to decrease a label type text with view customize.

### ISSUE THREAD

**Issue by onozaty** [onozaty/redmine-view-customize-scripts#40]
* https://blog.enjoyxstudy.com/entry/2016/10/23/000000#comment-26006613695198818

ROBERTO S MENDES

Hi Master!
How can i do to decrease a label type text with view customize.

For Example:
I have in my form that line, but the input is very large, then i`d like to decrease that input. How can i do this?

```html
<label for="issue_custom_field_values_4">Short Subject</label><input type="text" name="issue[custom_field_values][4]" id="issue_custom_field_values_4" value="" class="string_cf" />
</p>
```

**Comment by onozaty** [comment]
Select CSS in Type.
Then it will be embedded in the style tag.

You can use the following CSS to decrease that input.

```css
#issue_custom_field_values_4 {
  width: 40%;
}
```

Thanks

**Comment by robertotsi** [comment]
Thanks Onozaty!
