### ISSUE TITLE
New Issue - How to hide 

### ISSUE THREAD

**Issue by robertotsi** [onozaty/redmine-view-customize-scripts#41]
Hi @onozaty.

Is it possible to hide the link "New Issue" based on date?
`<a class="icon icon-add new-issue" href="/redmine/projects/infrastructure/issues/new">New Issue</a>`

For example:

**If current_date >= '2021-03-01 23:59:59' //(yyyy-mm-dd hh:mm:ss)
     New Issue = hide**

Something like that.

Thanks for your help.

**Comment by onozaty** [comment]
Please refer to the following.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/hide_new_issue_link_after_date.js

**Comment by robertotsi** [comment]
> Please refer to the following.
> 
> * https://github.com/onozaty/redmine-view-customize-scripts/blob/master/hide_new_issue_link_after_date.js

Hey @onozaty you are the man!

Worked perfectly! 
Thank you so much!
