### ISSUE TITLE
Change fields from related issues - is it possible?

### ISSUE THREAD

**Issue by robertotsi** [onozaty/redmine-view-customize-scripts#42]
![Captura de tela 2021-03-01 144412](https://user-images.githubusercontent.com/79494144/109536569-a6fcbc00-7a9c-11eb-89b1-e1d1e0f5b9dc.png)

Hi @onozaty! 

I have two projects, and i need related some issues each other.
But, the fields related aren't good.
So, I'd like to know if is possible to create a controller on view customize that bring in my form another fields when i related, like a custom field.

i attached an example from my form if can help you.

My code:

`<tr id="relation-14" class="issue hascontextmenu issue tracker-1 status-1 priority-24 priority-high5 created-by-me"><td class="checkbox"><input type="checkbox" name="ids[]" value="41"></td><td class="subject">Related to Issues SEOPI - <a class="issue tracker-1 status-1 priority-24 priority-high5 created-by-me" href="/redmine/issues/41">Necessidade #41</a>: Testing related issues</td><td class="status">In Progress</td><td class="assigned_to"></td><td class="start_date">11/12/2020</td><td class="due_date"></td><td class="done_ratio"><table class="progress progress-100"><tbody><tr><td style="width: 100%;" class="closed" title="100%"></td></tr></tbody></table><p class="percent"></p></td><td class="buttons"><a data-confirm="Are you sure?" title="Delete relation" class="icon-only icon-link-break" data-remote="true" rel="nofollow" data-method="delete" href="/redmine/relations/14">Delete relation</a><a title="Actions" class="icon-only icon-actions js-contextmenu" href="#">Actions</a></td></tr>`

Thanks!

**Comment by onozaty** [comment]
I'm sorry, I don't understand what you want to do.
Can you please tell me more about what you want to display?

**Comment by robertotsi** [comment]
I want to change the original fields from related issues for another custom fields. Can you understand-me?

For example. In Related Issues, I have issue number tracker, status, start date and %done. So I'd like to change this fields for some that i created.

**Comment by onozaty** [comment]
I understood.

However, to get the related ticket fields, I need to do it using Redmine's REST API.

* https://www.redmine.org/projects/redmine/wiki/Rest_Issues

You need to write the code to call the REST API in JavaScript, so you will need to have knowledge of JavaScript coding.

Thanks.

**Comment by robertotsi** [comment]
Thanks @onozaty I'll work that!
