### ISSUE TITLE
Take value from a custom field of the parent when creating a subtask

### ISSUE THREAD

**Issue by lcasanova78** [onozaty/redmine-view-customize-scripts#43]
I have a tracker type Document which has a field called category, so when I create a child task I need to know the value of that field to enable some trackers or others in the child task, depending on the value it has. how can I do it?

**Comment by onozaty** [comment]
To get the information of the custom fields of the parent issue, you need to use Redmine's REST API.

* https://www.redmine.org/projects/redmine/wiki/Rest_Issues

You need to write the code to call the REST API in JavaScript, so you will need to have knowledge of JavaScript coding.

Thanks.

**Comment by lcasanova78** [comment]
Thank you very much for your help, I can now realize it.
