### ISSUE TITLE
How to hide link Report/Summary

### ISSUE THREAD

**Issue by robertotsi** [onozaty/redmine-view-customize-scripts#44]
Hi @onozaty,

I'd like to hide the link Summary on sidebar, but i can't. 
 When I open the page, with my issues, in the right side, i have the sidebar with this link:
![summary](https://user-images.githubusercontent.com/79494144/110417659-bf5c7000-8074-11eb-9534-75fef5c9a2ea.png)
```
<a href="localhost/redmine/projects/students/issues/report">Summary</a>
```
I tried 
```
$(function() {

    $("a.report").hide()
    .next('li').hide();
});
```

Tks my friend!

**Comment by onozaty** [comment]
Hi @robertotsi 

Try the following.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/hide_issue_summary_link.css

Thanks.

**Comment by robertotsi** [comment]
Awesome! 🤩
Tks man!
