### ISSUE TITLE
Responsive Layout Redmine

### ISSUE THREAD

**Issue by robertotsi** [onozaty/redmine-view-customize-scripts#45]
Hey @onozaty 
I'm looking here, and i saw that the Redmine loses every controllers created on view customize when we open on mobile. 

Do you have a solution for this? 
I'm worry because I created with your help 20 controllers on view customize and when I opened on Safari iOS everything was gone! 😢

Tks man! 👍

**Comment by onozaty** [comment]
I expect it to work fine on mobile.
What kinds of things do not work?

If there are things that don't work, it may be due to differences in browsers.

**Comment by robertotsi** [comment]
Hi @onozaty I hid the link New Issue, based on date, but when I use the mobile the link appears. That was something I saw. However there may be more cases. 

I used this solution that I ask to you.

https://github.com/onozaty/redmine-view-customize-scripts/blob/master/hide_new_issue_link_after_date.js

Do you know if is possible to control roles and permissions from menu with JS?

Thanks again!

**Comment by onozaty** [comment]
> Hi @onozaty I hid the link New Issue, based on date, but when I use the mobile the link appears. That was something I saw. However there may be more cases.
> 

How did you displayed?
A screen capture will help us understand as well.

> I used this solution that I ask to you.
> 
> https://github.com/onozaty/redmine-view-customize-scripts/blob/master/hide_new_issue_link_after_date.js
> 
> Do you know if is possible to control roles and permissions from menu with JS?
> 

Roles can be referenced from `ViewCustomize.context`.

* https://github.com/onozaty/redmine-view-customize#viewcustomizecontext-javascript

Thanks

**Comment by robertotsi** [comment]
Hi @onozaty , an example that I had problem, was when I tried to hide the link new issue whit view customize. 

I used this solution [link](https://github.com/onozaty/redmine-view-customize-scripts/blob/master/hide_new_issue_link_after_date.js), that in default browser on computer worked perfectly. But when I opened in Safari, or Chrome in my Smartphone, the link was showing!

Look the print: 

![image](https://user-images.githubusercontent.com/79494144/114807623-1abd0480-9d7d-11eb-8a1e-d5ed364ad2b0.jpeg)

**Comment by onozaty** [comment]
Hi @robertotsi 

I also tried it and had no problem.

![image](https://user-images.githubusercontent.com/47337/114868557-01759000-9e31-11eb-88df-61653acbc4f5.png)

What happens if you reduce the window size in Chrome on your PC?
Will you have the same problem?

**Comment by robertotsi** [comment]
Hello @onozaty , when i reduce the window size in Chrome on my PC, the problem is not happens!

**Comment by onozaty** [comment]
Hi @robertotsi 

I haven't understood why it doesn't work on smartphones.

Can you try the following code to see what it looks like on a smartphone?

```js
$(function() {

    $("a.new-issue").hide();
});
```

This is because we want to isolate if the date decision is wrong.

**Comment by robertotsi** [comment]
> Hi @robertotsi
> 
> I haven't understood why it doesn't work on smartphones.
> 
> Can you try the following code to see what it looks like on a smartphone?
> 
> ```js
> $(function() {
> 
>     $("a.new-issue").hide();
> });
> ```
> 
> This is because we want to isolate if the date decision is wrong.

Hi @onozaty 

Worked perfectly without date.
But still, I thank you so much for your help and for discovered that problem.

**Comment by onozaty** [comment]
Is there a problem with hiding it regardless of the date?
If there is no problem, you can also write in CSS.

```css
/*
Insertion position: Head of all pages
Type: CSS
*/
a.new-issue {
  display: none;
}
```

For your reference.

**Comment by robertotsi** [comment]
tks
