### ISSUE TITLE
scope of application

### ISSUE THREAD

**Issue by lcasanova78** [onozaty/redmine-view-customize-scripts#46]
I want to apply a CSS only to the list of issues (/issues) but I don't want it to be applied neither in the details of an issue, nor its edition nor in new issues, how would be the expression to do that?

**Comment by onozaty** [comment]
Hi @lcasanova78 

Please try `/issues$` 

Thanks.

**Comment by lcasanova78** [comment]
It works! Thank you very much!

**Comment by lcasanova78** [comment]
I have a view customize that applies a css to many zones, I want to keep it that way but I don't want it to apply to a specific one.
If I set / it applies to everything, but I want to prevent it from applying to users.
How can I do it, I'm sorry but I don't have much knowledge about regular expressions.

Thank you very much
