### ISSUE TITLE
Add access counter at Redmine home page

### ISSUE THREAD

**Issue by Fuku0008** [onozaty/redmine-view-customize-scripts#47]
I want add access counter at Redmine home page.
and set the display area freely.

**Comment by onozaty** [comment]
@Fuku0008 

This cannot be done by View customize alone, because the counted results must be kept somewhere.

Thanks.

**Comment by Fuku0008** [comment]
Thanks for your reply.
So I have to find other way to do it.
Thanks again.

Fukunaga

2021年6月3日(木) 21:44 onozaty ***@***.***>:
