### ISSUE TITLE
Populate child / boolean field

### ISSUE THREAD

**Issue by pousterlus** [onozaty/redmine-view-customize-scripts#48]
Hello there,

Thanks for your work, your plugin is great.
I want to use it to automatically set a custom field "Child" to "Yes" when I hit the "Create subtask" button.

In your examples, I can see that there are some examples for radio buttons and select cases, but not for boolean values.
I'm trying this : 

```
$(function() {

  var addLink = $('#issue_tree a[href*="/issues/new"]')[0]; 

  var subtask = $('#issue_custom_field_values_11').val('Yes');
  addLink.href += '&issue%5Bissue_custom_field_values_11%5D=' + subtask;

})
```

... but it's not working.
Do you have an idea how to achieve that ?

Arigato gozaïmas :)

-- 
Léo.

**Comment by onozaty** [comment]
Hi @pousterlus 

The custom fields should be set as `issue[custom_field_values][11]`.
For boolean values, `0` is false and `1` is true.

Try the following.

```javascript
$(function() {

  var addLink = $('#issue_tree a[href*="/issues/new"]')[0]; 
  addLink.href += '&issue%5Bcustom_field_values%5D%5B11%5D=1';

})
```

Thanks.

**Comment by pousterlus** [comment]
The solution was easy, I don't know why I didn't try to insert the "1" directly instead of trying to variabilize it.
Thanks, that solved my problem.

-- 
Léo.
