### ISSUE TITLE
Identify Child issue / hide fields

### ISSUE THREAD

**Issue by pousterlus** [onozaty/redmine-view-customize-scripts#49]
Hello again,

I'm trying to hide 2 fields from an issue view but only if it's a subtask.
I tried to inspire myself from your examples, but I can't find how to identify that I'm viewing a child issue to populate the Path variable.

Do you have an idea ?
Thanks !

-- 
Léo.

**Comment by onozaty** [comment]
Hi @pousterlus 

It is not possible to determine from Path that it is a subtask.
The only way to determine this is to check the parent issue Id in JavaScript.

```javascript
$(function() {

  if ($('#issue_parent_issue_id').val() != '') {
    // has parent task?
    $('.cf_2.attribute').hide();
    $('#issue_custom_field_values_2').parent().hide();
  }

});
```

Thanks.

**Comment by pousterlus** [comment]
Ohayo @onozaty :)

Okay, got it.
Do I have to populate "Path pattern" here ?
And could you confirm me that I have to choose : "Bottom of issue detail" in Insertion position ?

Thanks,

-- 
Léo.

**Comment by onozaty** [comment]
konbanwa! @pousterlus 

> Do I have to populate "Path pattern" here ?

No, it is not necessary.
You can leave it blank.

> And could you confirm me that I have to choose : "Bottom of issue detail" in Insertion position ?

Sorry for the lack of explanation.
You need to choose "Bottom of issue detail".

Thanks.

**Comment by pousterlus** [comment]
@onozaty ^^

Thanks so much, I confirm everything's working great !
Oyasumi nasaï.

-- 
Léo.
