### ISSUE TITLE
How to add  related issues when I set some status such as rejected.

### ISSUE THREAD

**Issue by archonwang** [onozaty/redmine-view-customize-scripts#5]
Hi, @onozaty ，

I want to add related issues on popup window when I set the rejected status, Can javascirpt support to do it?
Thanks.

**Comment by onozaty** [comment]
Hi @archonwang 

Sorry, I did not understand the "add related issues on popup window".
Could you tell me a little more detail?

**Comment by archonwang** [comment]
@onozaty ,Thanks for your reply.  
I have not used the function at present,  I will close the issue.
