### ISSUE TITLE
Readonly / Disabled fields

### ISSUE THREAD

**Issue by pousterlus** [onozaty/redmine-view-customize-scripts#50]
Konbawa !

I hope you're fine.
I try to make a field not editable ("disable" attribute in html) if this is a subtask.
I know how to check if this is a subtask, but I don't know how to give a custom field the "disable" attribute.
I'm not an expert, but here's what I tried : 

```
$(function() {
  if ($('#issue_parent_issue_id').val() != '') { // if subtask
    $('.cf_1.attribute').setAttribute("disable");(); // set disable attribute
    $('#issue_custom_field_values_1').parent().setAttribute("disable"); // set disable attribute
  }
});
```
Doesn't work.
Can you tell me what I'm doing wrong ?

-- 
Léo.

**Comment by onozaty** [comment]
Hi @pousterlus 

To disable it `elm.prop('disabled', true)`

```js
$(function() {

  if ($('#issue_parent_issue_id').val() != '') {
    // has parent task?
    $('#issue_custom_field_values_1').prop('disabled', true);
  }

});
```

Oyasuminasai.

**Comment by pousterlus** [comment]
Sugoi @onozaty san :)
Mata ne !

-- 
Léo.

**Comment by pousterlus** [comment]
Additional small question : If I try to edit an existing subtask, this code is working.
But when I use the "create subtask" button, the new sub-issue creation form shows up and the field is still editable (I think this is because the parent id is filled but not saved yet).

Is there a way to workaround this ? (like maybe a check to see if the "parent issue id" is filled ?)
Thanks for your advice.

-- 
Léo.

**Comment by onozaty** [comment]
Hi @pousterlus 

It needs to be checked every time the input value of the parent_issue_id changes.
Try the following code.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/disable_if_parent_issue_is_set.js

Thanks.

**Comment by pousterlus** [comment]
Hi again,

Thanks for your help and your time, it's perfect for my needs.
See you,

-- 
Léo.
