### ISSUE TITLE
Redirect with view customize ?

### ISSUE THREAD

**Issue by pousterlus** [onozaty/redmine-view-customize-scripts#52]
Hello @onozaty :)

I hope you're great.
Small question : I have a "Sprint" tab in one project menu tabs. When I click on it, it leads to "https://***/sprint" URL.

Can I use your plugin to add some params at the end of the URL (for example "?query=11") in order to go to "https://***/sprint?query=11" when the tab is clicked ?

I can't find approaching examples in your examples database.

Thanks !

-- 
Léo.

**Comment by onozaty** [comment]
Hi @pousterlus 

I created a script to change the URL of the Issue tab.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/change_issue_default_query.js

I hope this helps.

Thanks.
