### ISSUE TITLE
Popup window message / Online warning 

### ISSUE THREAD

**Issue by konpega** [onozaty/redmine-view-customize-scripts#53]
I am looking for a pop-up warner which alerts the user that he/she is assigned to a new issue. When I saw the Popup Window Message Issue #31, I think that maybe it is possible to arrange this for my request?

**Comment by onozaty** [comment]
I don't think there is any way to detect on the screen that a user has been assigned a new Issue.
Therefore, it is unlikely to be possible with View customize.

I'm sorry I can't help you.

**Comment by konpega** [comment]
Thanks a lot.
