### ISSUE TITLE
View Customize Project

### ISSUE THREAD

**Issue by robertotsi** [onozaty/redmine-view-customize-scripts#54]
Hello @onozaty 

How can I do to recover name or identifier project from Viewcustomize?
I want to use the name or identfier project to do a controller.

ViewCustomize = { context: {"user":{"id":245,"login":"roberto.mendes","admin":true,"firstname":"Roberto","lastname":"Mendes","lastLoginOn":"2021-09-01T18:34:01Z","groups":[],"apiKey":"792e6814a022c151a8236b1d4449737a799514dc","customFields":[{"id":60,"name":"Área de Negócio","value":null}]},"project":{"identifier":"bni_baclog","name":"BNI","roles":[],"customFields":[]}} };

I tried to use that: 

If (Viewcustomize.context.project.name == 'BNI'){ expression here} but don't work. So, I don't know if my operator is ok.

Can You help me?

Tks

**Comment by onozaty** [comment]
`ViewCustomize.context.project.name` is correct.

Using the browser's DevTools is easy to try.

![image](https://user-images.githubusercontent.com/47337/131863768-84a12d61-ae5f-43d7-a49f-eda279573d73.png)

Thanks.

**Comment by robertotsi** [comment]
Thanks @onozaty for your kind help.
But I changed my code. Look my idea and tell me if is possible.

I would like to set a conditional custom field based on name or identifier project.
Do you think is this possible?

I was tried to adapt your code, but i'm lost.

I have this:

> ViewCustomize = { context: {"user":{"id":245,"login":"roberto.mendes","admin":true,"firstname":"Roberto","lastname":"Mendes","lastLoginOn":"2021-09-01T18:34:01Z","groups":[],"apiKey":"792e6814a022c151a8236b1d4449737a799514dc","customFields":[{"id":60,"name":"Área de Negócio","value":null}]},"project":{"identifier":"censo-basico","name":"Censo Básico","roles":[],"customFields":[]}} };

My issue_custom_field_values_58 have this values:

> 1.Backlog
> 2.Sprint
> 3.Codificando
> 4.Disponível para teste
> 5.Testando
> 6.Pronto
> 7.Homologando
> 1.A fazer
> 2.Em andamento
> 3.Aguardando Teste
> 4.Em Teste
> 5.Aguardando Homologação
> 6.Em Homologação
> 7.Feito

I would like to limit or to define the childField from my custom field based on name or identifier project.

**My Code:**

 ```js
//Controller - Identifier Project
$(function() {


  var parentFieldId = 'ViewCustomize.context.project.identifier'; //Identifier Project
  var childFieldId = 'issue_custom_field_values_58'; //ChildField

  // define conditions
  var isTarget = function(child, parent) {

    //Identifier Project censo-basico    
    if (parent.text()=='censo-basico') return child.text()=='1.A fazer' | child.text()=='2.Em andamento' | 
child.text()=='3.Aguardando Teste' | child.text()=='4.Em Teste' | child.text()=='5.Aguardando Homologação' | 
child.text()=='6.Em Homologação' | child.text()=='7.Feito';
   else return false;
  }

  var narrowChildField = function() {

    var parentSelected = $('#' + parentFieldId + ' > option:selected');

    $('#' + childFieldId + ' > option').each(function() {

      var child = $(this);

      if (isTarget(child, parentSelected)) {
         child.show();
      } else {	
        child.hide();
      }
    });

    var val = '';
    $('#' + childFieldId+' option:contains(' + val + ')').prop({selected: true});
  }

  narrowChildField();

  $('#all_attributes').change(function(e) {
    if (e.target.id == parentFieldId) {
       narrowChildField();
    }
  });

  var _replaceIssueFormWith = replaceIssueFormWith;
  replaceIssueFormWith = function(html){

    _replaceIssueFormWith(html);

    narrowChildField();
  };
});

**Comment by onozaty** [comment]
The `parentFieldId` corresponds to the ID in the HTML, so you cannot use `'ViewCustomize.context.project.identifier'` as an ID.

Since `ViewCustomize.context.project.identifier` is the value itself, you will have to look at where you are using `parentFieldId` and see if you can replace it with `ViewCustomize.context.project.identifier`.

**Comment by robertotsi** [comment]
Tks
