### ISSUE TITLE
Sub task

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#55]
How I can prevent added sub task only if status id =5??

And 

How I can give alarm msg and can't save issue if cfs[3] > cfs [4]

**Comment by onozaty** [comment]
I want to avoid writing code from scratch as much as possible. Because my time is also finite 😅
Would you please write the code first if possible?
I want to follow up on that.

Thanks.

**Comment by ashrafalzyoud** [comment]
If u can help plz

**Comment by onozaty** [comment]
This is not the place for code creation requests.
Also, I am not a free coder.

I would like to support you if you have any questions about how to write View customize, but what is it that you don't understand right now?

**Comment by onozaty** [comment]
For both questions, the following, which was asked a long time ago, may be helpful.

* https://github.com/onozaty/redmine-view-customize-scripts/issues/31

**Comment by ashrafalzyoud** [comment]
this different topic

**Comment by onozaty** [comment]
> this different topic

No, I think it would be helpful.
If you could give us a reference and then tell us a little more about what you don't understand, please.

Please note that this is a place to ask questions, not a place to request coding.
