### ISSUE TITLE
hiding link by role

### ISSUE THREAD

**Issue by delacosta456** [onozaty/redmine-view-customize-scripts#56]
hi
is it possible to hide links to specific roles ?

**Comment by onozaty** [comment]
You can get the role from `ViewCustomize.context`.

* https://github.com/onozaty/redmine-view-customize#viewcustomizecontext-javascript

For example, if you want to check that the roleId is 3, you can write the following.

```javascript
if (ViewCustomize.context.project.roles.some(function(role) { return role.id == 3 })) {
  // hide links
}
```

Thanks.

**Comment by delacosta456** [comment]
hi many thanks
