### ISSUE TITLE
if u can help??

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#58]
Purchase orders must not exceed the financial balance
Where the user can add several purchase orders so as not to exceed the financial balance.
And if the financial balance is exceeded, a warning message appears, and the purchase order balance must be changedt
TRAcker ORDERS 200 
 obalance cfs[1] -->float 
 orders cfs [2] --> float
like example:
balance = 1000$
order 1+order2 +order 3= total cfs[2]=total orders = 1200$=cfs[3]
if cfs[3]>cfs[1] 
give error massaage balance exceeded and cant save order

**Comment by onozaty** [comment]
Have you tried writing the code?
Please tell me more about what you don't understand.

As I mentioned elsewhere, please note that this is a place to ask questions, not a place to request coding.

**Comment by ashrafalzyoud** [comment]
a =  self.custom_field_value(1).to_f
b = self.custom_field_value(2).to_f
if (a >= b)
errors.add(":bass"error ")
end
how prevent user to added task

**Comment by ashrafalzyoud** [comment]
```
`$(function() {

  const order = $'#issue_custom_field_values_1');
  const remain = $'#issue_custom_field_values_2');

  if (order > remain) {
    $('#content').prepend ('<div class="ashraf1">  error msg</div>');
  } 
})`


```

**Comment by ashrafalzyoud** [comment]
@onozaty Thank you for your patience

**Comment by onozaty** [comment]
When will the warning message be displayed?
Is it during issue creation or saving?

**Comment by ashrafalzyoud** [comment]
Saving

**Comment by onozaty** [comment]
If you want to check the issue when it is created or saved, set up an event handler as in `$('#issue-form input[type="submit"]').on('click', function(event) {})`.
The conversion to float is done with `parseFloat`.

The image is as follows.

```javascript
$(function() {
  $('#issue-form input[type="submit"]').on('click', function(event) {

    const order = parseFloat($('#issue_custom_field_values_1').val());
    const remain = parseFloat($('#issue_custom_field_values_2').val());

    if (order > remain) {
      alert('error msg');
      return false;
    }
  });
});
```

Thanks.

**Comment by ashrafalzyoud** [comment]
Thank you for your cooperation and patience and your great plugin
its not work  while  cfs[2] float --> READ-ONLY
if im change the tybe of cfs[2]--> EDIT 
the code work, but user cant editing the value of CFS[2]
IF U CAN HELP???

**Comment by onozaty** [comment]
In the case of readonly, it should be retrieved from the displayed area.

You can get it at `$('.cf_2.attribute .value').text()` 

```javascript
const remain = parseFloat($('#issue_custom_field_values_2').val() || $('.cf_2.attribute .value').text());
```

Thanks.

**Comment by ashrafalzyoud** [comment]
you are great man thx alot
but i note after save the issue and then edit it the msg error appear and user cant edit the cfs[1]
1- how i can reload and save issue twice 
becuase the cfs[2] its computed custom field and need reload the value after insert value

thanx

**Comment by onozaty** [comment]
Are you using some kind of plugin to compute the value of the custom field?
If so, I guess you need to do the compute in View customize as well.

Thanks.

**Comment by ashrafalzyoud** [comment]
I'm use plugin https://www.redmine.org/plugins/computed_custom_field

And I'm calculate total order in this formula
Cfs[1]= 
project.issues.includes(:custom_values).where(tracker_id:34).to_a.sum {|issue|issue.custom_field_value(138).to_f}

**Comment by onozaty** [comment]
> I'm use plugin https://www.redmine.org/plugins/computed_custom_field
> 
> And I'm calculate total order in this formula Cfs[1]= project.issues.includes(:custom_values).where(tracker_id:34).to_a.sum {|issue|issue.custom_field_value(138).to_f}

I see that it includes other Issues.
This is not possible with View customize 😢

**Comment by ashrafalzyoud** [comment]
Okay thx brother 
But can u tell me how I can reload and save issue two times 
I'm try 
Self.reload 
Self.save
Or
Location.reload

When submit or create or edit issue

**Comment by onozaty** [comment]
When the screen is reloaded, the View customize script will be reloaded as well, so I don't think it is possible to do any processing after the reload.

> you are great man thx alot but i note after save the issue and then edit it the msg error appear and user cant edit the cfs[1] 1- how i can reload and save issue twice becuase the cfs[2] its computed custom field and need reload the value after insert value
> 

I don't understand why a reload is needed here.
At what point does the error message appear?
Also, do you know why the error message is displayed?

Please tell me more about it.

**Comment by ashrafalzyoud** [comment]
Example:
Balance = 1000$ = cfs[1]
The user can added many task [orders] but can't exceeded the balance,
Order 1 = 100$ remain =900$ ok
Order 2 = 200$ remain= 700$ ok
Order 3 = 400$ remain = 300$ ok
Order 4 = 500$ remain =-200$ not ok
Give error message until user order money < remain
-------------
Cfs [1]= balance =A
Cfs [2] = order= B
Cfs[3] = total orders=C
Cfs [4] = remain = balance - total orders=D
 Then I but if  (B>D)
Error msg
But the problem when add new order,
The total orders not work true in first time submitted 
I need editing then save
This mean mag error not appear in first time

**Comment by onozaty** [comment]
Thank you very much.
I now understand that the following is the cause.

> The total orders not work true in first time submitted

In the current script, if you enter the order in the first time submitted, will you always get an error?

**Comment by ashrafalzyoud** [comment]
Thx for you brother 
But how I can reload tow times
Like
Self.reload
Self.save
Location.reload
While creating or submitted or editing

**Comment by ashrafalzyoud** [comment]
Yes
Because the new order (value)
Not calculated in total order first time

**Comment by onozaty** [comment]
Since it is not possible to reload and continue the process in View customize, I would like to think if there is some other way to make the procedure easier.

I am sorry, but could you please tell me more about the current input procedure?
I would like to know which fields you are trying to enter at that time.
I would also like to know at what point I need to reload.

Thanks.

**Comment by ashrafalzyoud** [comment]
Self.custom.field.value(2) it's not calculated with total cfs[2] in first time when creating 
When I edit the issue and update 
The total cfs[2] correct

**Comment by onozaty** [comment]
> Self.custom.field.value(2) it's not calculated with total cfs[2] in first time when creating When I edit the issue and update The total cfs[2] correct

cfs[2] is order?
Did you enter cfs[2] when you created the issue?

I'm sorry, I don't really understand the procedure.

**Comment by ashrafalzyoud** [comment]
Tracker ORder
Cfs[2] the value of purchase 
It's enter when I created issue

**Comment by onozaty** [comment]
Thank you.
It's strange that even though the values are entered at the time of creation, they are not calculated until you edit and update them again.

I can't think of any way to solve this in View customize.

**Comment by ashrafalzyoud** [comment]
in View customize if u can resave agian 
i can or no?

thx alot

**Comment by onozaty** [comment]
> in View customize if u can resave agian i can or no?
> 

No.

Thanks.

**Comment by ashrafalzyoud** [comment]
```

<p>plz click to here to reculate </p>

<button onclick="myFunction()">recalcute</button>

<p id="demo"></p>

<script>
function myFunction() {
  location.hash = "DONE";
  var x = "PROCEDURE: " + location.hash;
  document.getElementById("demo").innerHTML = x;
}
</script>

</body>
</html>
```
if there any way  when the user click in button
this mean (edit and submit)

thx

**Comment by onozaty** [comment]
If you reload the page when you click the submit button, your input will be lost.
Also, I don't think there is a way to send after reloading.

So I don't think it can be done in View customize.

Thanks.
