### ISSUE TITLE
Select2 for custom field

### ISSUE THREAD

**Issue by lublasco** [onozaty/redmine-view-customize-scripts#59]
Hi,

I've seen I could convert the assignee selector in a select2 search field with this: https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0018.add_search_function_to_selectbox/example.md

How could I add the select2 box to a list custom field (id=X)?

Thank you in advance for your help!

**Comment by onozaty** [comment]
Thank you for your sponsorship.

It works by simply changing the element specified in `replaceSelectToAutocomplete`.
Can you please try it?

```javascript
  // replaceSelectToAutocomplete('#issue_assigned_to_id');
  replaceSelectToAutocomplete('#issue_custom_field_values_1');
```

Thanks

**Comment by lublasco** [comment]
You're welcome. This is a very useful plugin.

And thanks for the tip, it worked like a charm!
