### ISSUE TITLE
extend the issue status board function.

### ISSUE THREAD

**Issue by archonwang** [onozaty/redmine-view-customize-scripts#6]
@onozaty ,

I used an status_board function in my Redmine with JS. and I want to extend some funtion . for example, 
when I click the status id =6 , I want to set the issue_fixed_version_id is null automatically, and when I submit what I have modified , it would check  the issue_fixed_version_id is null when current issue_status_id is 6.

could you help me, please?

I add js to use the issue_status_board on issue details page. please add the js in your plugins .the code as follows,

```
// path: /issues/*
// type: javascript
// comments: Add an issue status board on issue details page on the right, so you can change status by one click.

$(document).ready(function() {
    $('body').prepend('<div id="changeStatus" style="background-color:#628DB6;color:white;position:fixed;z-index:9999;padding: 10px 30px 10px 0px;margin:25px;top:200px;right:10px;border: 2px solid;border-radius: 15px;"><ul></ul></div>');
    
    $("#issue_status_id option").each(function (elem) { 
        console.log($(this).attr('value') + $(this).html());  
        $('#changeStatus ul').append('<li class="status" data-value="' + $(this).attr('value') + '" style="cursor:pointer; font-weight:bold; line-height:1.5em">' + $(this).html() + '</li>');
    });
    
    $('.status').on("click", function () {
            showAndScrollTo("update", "notes");
        $('#issue_status_id').val($(this).data("value"));
    });
});
```

**Comment by onozaty** [comment]
Hi @archonwang 

> for example, when I click the status id =6 , I want to set the issue_fixed_version_id is null automatically, and when I submit what I have modified

I added the contents of example.

```javascript
// path: /issues/*
// type: javascript
// comments: Add an issue status board on issue details page on the right, so you can change status by one click.

$(document).ready(function() {
    $('body').prepend('<div id="changeStatus" style="background-color:#628DB6;color:white;position:fixed;z-index:9999;padding: 10px 30px 10px 0px;margin:25px;top:200px;right:10px;border: 2px solid;border-radius: 15px;"><ul></ul></div>');
    
    $("#issue_status_id option").each(function (elem) { 
        console.log($(this).attr('value') + $(this).html());  
        $('#changeStatus ul').append('<li class="status" data-value="' + $(this).attr('value') + '" style="cursor:pointer; font-weight:bold; line-height:1.5em">' + $(this).html() + '</li>');
    });
    
    $('.status').on("click", function () {
            showAndScrollTo("update", "notes");
        var statusId = $(this).data("value");
        $('#issue_status_id').val(statusId);

        if (statusId == '6') {
          $('#issue_fixed_version_id').val('');
        }
    });
});
```

**Comment by archonwang** [comment]
Hi, @onozaty ,
Thanks.

**Comment by archonwang** [comment]
@onozaty , 
I found it not worked well. when I click the status link to open the edit pannel and the fixed_version_id is not set to null. any solutions?

**Comment by onozaty** [comment]
Hi @archonwang 

In my environment(Firefox 50, Redmine 3.3.0), it works without problems.
Please tell me about your environment.

**Comment by archonwang** [comment]
I used chrome with redmine 3.3.1 and mysql
my environment is 

```
Environment:
  Redmine version                3.3.1.stable.16009
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
```

**Comment by onozaty** [comment]
I tried it with Redmine 3.3.1 and Chrome.
It worked without problems.

![animation](https://cloud.githubusercontent.com/assets/47337/21074179/dd878bd2-bf35-11e6-9ce9-c2680303c807.gif)

**Comment by archonwang** [comment]
Hi, @onozaty 
I tried it in my new environment and it worked well, so I check with chrome development tools and found that I have missed some js file, and I fixed it. 

the script worked, Thansk so much.
