### ISSUE TITLE
Сброс даты завершения при открытии задачи

### ISSUE THREAD

**Issue by maksnet2** [onozaty/redmine-view-customize-scripts#60]
Добрый день.
Мне нужно очистить поле даты завершения задачи при смене статуса из «закрыт»  в любой другой. В принципе это не сложно, но как посмотреть какой статус был до смены? Кажется я видел в каком-то скрипте, но сейчас не могу найти.

**Comment by onozaty** [comment]
There was no sample that checked the value before the change, so I wrote one.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0042.clear_due_date_when_status_changed_from_closed/example.md

Thanks.

**Comment by maksnet2** [comment]
Спасибо большое, сегодня-завтра проверю и отпишусь.

Скажите такой момент: в редмайне могут быть несколько статусов задач с галочкой "задача закрыта" (см. скриншот), можно ли проверять не ID конкретного статуса задачи, а по признаку, означающему, что задача закрыта?

![image](https://user-images.githubusercontent.com/19895894/144235139-a1d6090a-f160-4ed3-a100-988c30c69ded.png)

**Comment by onozaty** [comment]
> Скажите такой момент: в редмайне могут быть несколько статусов задач с галочкой "задача закрыта" (см. скриншот), можно ли проверять не ID конкретного статуса задачи, а по признаку, означающему, что задача закрыта?
> 
> ![image](https://user-images.githubusercontent.com/19895894/144235139-a1d6090a-f160-4ed3-a100-988c30c69ded.png)

This information is not present on the screen, so it is difficult for View customize to judge it.

**Comment by maksnet2** [comment]
> Этой информации нет на сервере, поэтому Посмотреть настроить сложно судить о ней.

Понял, жаль.

**Comment by maksnet2** [comment]
Скрипт работает, но есть маленький нюанс.:
- допустим сейчас задача в статусе "в работе" и выставлен срок завершения задачи (например послезавтра я должен еще решить)
- при смене статуса на "выполнен" (НЕ закрыта) я случайно выбираю статус "закрыта" - и все, дата сбрасывается, а не должна. 
 
 Нужно, чтобы дата завершения очищалась, только если сначала задача была сохранена в статусе закрыта (дата при этом никак не меняется), а потом снова открыта (при этом дата очищается).
Можно так в принципе?

**Comment by onozaty** [comment]
Changed the status to be compared with the status before editing.
I think this prevents it from being cleared if you accidentally select Close in the middle of the process.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0042.clear_due_date_when_status_changed_from_closed/example.md

**Comment by maksnet2** [comment]
Класс! Спасибо большое! Вроде все работает как надо. Ваш плагин и документация к нему супер!

Для истории: 
немного изменил плагин, чтобы проверял несколько статусов, которые имеют атрибут "задача закрыта" и чтобы не очищал дату при переходе между такими статусами.





```
$(function() {

  const stats = ['5','6','19','36']; // closed statuses
  const beforeIssueStatusId = $('#issue_status_id').val();

  $('#all_attributes').on('change', '#issue_status_id', function() {

    const afterIssueStatusId = $('#issue_status_id').val();
    if ((stats.includes(beforeIssueStatusId)) && (!stats.includes(afterIssueStatusId))) {
        $('#issue_due_date').val('');
    }
  });
});
```

**Comment by onozaty** [comment]
I'm glad I could help you 😄
