### ISSUE TITLE
empty value custom field

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#61]
how i can select empty value $0 or blank 

`div.issue .attribute .value {background-color: red}`

**Comment by onozaty** [comment]
Do you want to change the background of the issue input custom field?

Thanks.

**Comment by ashrafalzyoud** [comment]
Yes Friend

**Comment by onozaty** [comment]
It is not possible to change it every time the input value changes using css.
It needs to be done in JavaScript.

I've created an example below for you to try.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0043.change_style_according_to_input_value/example.md

**Comment by ashrafalzyoud** [comment]
how if all custom_field value dont targer one

**Comment by onozaty** [comment]
> how if all custom_field value dont targer one

Is it something that cannot be implemented based on this sample?
Can you please tell me more about what kind of case you are talking about?

**Comment by ashrafalzyoud** [comment]
U determine just custom field 1
If I have many custom field 
What I can do

**Comment by onozaty** [comment]
Changed the example.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0043.change_style_according_to_input_value/example.md

You can set it by calling the setup method for the field you want to set.

```javascript
  setup('#issue_custom_field_values_1');
  setup('#issue_custom_field_values_2');
  setup('#issue_custom_field_values_3');
```

This feels like a basic question about JavaScript, not about View customize.

Many of your previous inquiries have also been about how to write JavaScript.
Sometimes I feel like I'm working for free as a coder.

You may want to consider learning how to write JavaScript a little more or hiring an engineer.

Thanks.

**Comment by ashrafalzyoud** [comment]
Ok brother thx for u
