### ISSUE TITLE
Hide the administrator check box when another admin added user

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#62]
If user_id =2
Hide the administrator check box

I want this admin user just added normal users

**Comment by onozaty** [comment]
The following is a good reference for judging by user ID.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0035.hide_some_administrator_menus_for_specific_user/example.md

Thanks.

**Comment by ashrafalzyoud** [comment]
![admin](https://user-images.githubusercontent.com/50211455/148657973-700efea0-653c-4081-be84-ef094a6fc223.png)
i mean this check box
the aim for that prevent another admin to create new admin

**Comment by onozaty** [comment]
I wrote this because I thought that with the sample I just gave you, you could do it with what I have been telling you.

Do you mean you don't know how to disable the Administrator checkbox?

Thanks.

**Comment by ashrafalzyoud** [comment]
yes brother ,i want another admin cant added admin users just normal users

**Comment by onozaty** [comment]
> yes brother ,i want another admin cant added admin users just normal users

I thought it could be implemented well enough if you refer to the previous samples.

First of all, the judgment by user ID can be seen in the following sample.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0035.hide_some_administrator_menus_for_specific_user/example.md

The following is a condition other than user ID:1.

```javascript
if (ViewCustomize.context.user.id != 1) {
  // hide 
}
```

The administrator checkbox can be found in the browser's DevTool to see what ID is assigned to it.

![image](https://user-images.githubusercontent.com/47337/148852783-ab555e20-7670-406d-9716-528e93ee3d7a.png)

The ID is `user_admin`.
I think you can disable or hide this.

```
$('#user_admin').prop('disabled', true);
```

The whole thing will look like this.

```javascript
$(function() {
  if (ViewCustomize.context.user.id != 1) {
    $('#user_admin').prop('disabled', true);
  }
});
```

![image](https://user-images.githubusercontent.com/47337/148853625-fa001f72-8ccc-44de-8146-53a58f57dcda.png)
