### ISSUE TITLE
the information from the parent issue using from a child issue, 

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#66]
thx alot for your best plugin in redmine and thx for all your Ease of cooperation and quick response

how i can using the values from child to parent???
  ('#issue_custom_field_values_1');
  ('#issue_custom_field_values_2');
  ('#issue_custom_field_values_3');
like your example but the opposite side
[https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0023.when_create_child_use_parent_infomation/example.md](url)

**Comment by onozaty** [comment]
When would you like to use it?

When you edit a parent issue, do you want to get the custom field information of the child issue?
In that case, the child issue information is not on the screen, so you have to use Redmine's REST API. I don't recommend this because it will be difficult to implement.

**Comment by ashrafalzyoud** [comment]
> When you edit a parent issue, do you want to get the custom field information of the child issue?

yes
i dont let the user enter the value agian in parent task

**Comment by onozaty** [comment]
I wrote an example of using the REST API to get information on other Issues.
However, it is complicated, so I do not recommend it.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/tips/tips.md#using-the-rest-api-to-fetch-issue
