### ISSUE TITLE
Выполнение скрипта при сохранении задачи

### ISSUE THREAD

**Issue by maksnet2** [onozaty/redmine-view-customize-scripts#67]
Добрый день.

Мне нужно при сохранении задачи проверять определенное поле и выводить предупреждение - это достаточно легко сделать при использовании кнопки "принять!, скрипт ниже работает:

```
$(function() {
  $('#issue-form input[type="submit"]').on('click', function(event) {
    
    const checkbox = $('#helpdesk_is_send_mail');

    if (checkbox.prop('checked')) {
      if(confirm("Вы отправляете письмо. Уверены?")){        
        return true;   
      } else {
        return false;
      } 
    }
  });
});
```
Но это не работает, если я сохраняю задачу горячими клавишами "Ctrl + Enter" - задача сохраняется, но скрипт не отрабатывает и предупреждение не выводится.
Можно ли как-то решить этот вопрос? Есть какой-то более универсальный метод?

**Comment by onozaty** [comment]
The following may be helpful.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/1b627a15b1a1f8a988c286e2670c1cee6dd12075/tips/tips.md#process-when-creating-or-saving-an-issue

```javascript
$('#issue-form').on('submit', function() {

  if (!confirm('Are you sure?')) {
    // If you don't reset it, it won't be submitted the next time.
    this.dataset.submitted = '';
    // If it returns false, it will not be executed.
    return false;
  }
});
```

The point is to handle it with submit event.

Thanks.

**Comment by maksnet2** [comment]
А вот туда я и забыл заглянуть )))

У меня заработал вот так, иначе всегда сохранялось или всегда не сохранялось, независимо от нажатой кнопки:
<pre><code class="java">

$('#issue-form').on('submit', function() {

  if (confirm('Are you sure?')) {
    // If you don't reset it, it won't be submitted the next time.
    this.dataset.submitted = '';
    // If it returns false, it will not be executed.
    return true;
  } else {
    return false;
  }
});

</code></pre>

Далее уже добавил свои проверки - работает. Спасибо большое и удачи ))
