### ISSUE TITLE
Format attributes in request view mode

### ISSUE THREAD

**Issue by Daradaal** [onozaty/redmine-view-customize-scripts#68]
I need help with this formatting:
![Image (1) 0](https://user-images.githubusercontent.com/47509244/150677399-a2e974fd-0149-4faf-a76b-7c037ed9042c.png)

Indeed, my script works and displays my attributes as I wish, but when I switch to edit mode this formatting is reproduced in the edit form, which I don't want...:
![Image 2](https://user-images.githubusercontent.com/47509244/150677557-f6e3c0f0-2f46-4c24-8f44-64dfea71d87c.png)

**What can be done to prevent this from happening?**

Here is the current JS script:
```
$(function() {
  // Note: Change the ID according to the custom field you want to target.
  const Header1 = $("<p><h4>Information générale</h4></p>");
  const Field1 = $('.category.attribute');
  const Field2 = $('.cf_2.attribute');
  const Field3 = $('.cf_4.attribute');
  const Field4 = $('.cf_3.attribute');
  const Field5 = $('.cf_5.attribute');

  const secondAttributes = $('<div class="attributes">').append(
    $('<div class="splitcontent">')
       .append($('<div class="splitcontent">').append(Header1))
       .append($('<div class="splitcontentleft">').append(Field1))
       .append($('<div class="splitcontentleft">').append(Field2))
       .append($('<div class="splitcontentleft">').append(Field3))
       .append($('<div class="splitcontentleft">').append(Field4))
       .append($('<div class="splitcontentleft">').append(Field5))

);


  const description = $('.attributes');

  if (description.size() == 1) {
    $('.description').after(secondAttributes);
    $('div.issue div.attributes').before($("<hr style='height:8px'>"));
  } else {
    $('.attributes').after(secondAttributes);
    $('div.issue div.attributes').before($("<hr style='height:8px'>"));
  }
});
```

Thank you in advance for your assistance :)

**Comment by onozaty** [comment]
Does this mean that the input field needs to be moved as well?

For moving custom fields, the following may be helpful.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0027.move_custom_field_to_after_tracker/example.md

Thanks.

**Comment by Daradaal** [comment]
Thanks !
