### ISSUE TITLE
Двойное срабатывание скриптов.

### ISSUE THREAD

**Issue by maksnet2** [onozaty/redmine-view-customize-scripts#69]
Добрый день.
Есть несколько скриптов, выводящих предупреждения при сохранении задачи. Если при редактировании задачи я менял статус задачи - то скрипт срабатывает 2 раза и 2 раза выводит предупреждение. Если статус не менял, то все нормально, выводит 1 предупреждение.
Помогите, пожалуйста понять, почему так происходит?

Пример одного из скриптов:
```
$('#issue-form').on('submit', function() {

  const checkbox = $('#helpdesk_is_send_mail');

  if (checkbox.prop('checked')) {
    if (confirm('Вы отправляете письмо. Уверены?')) {
      // If you don't reset it, it won't be submitted the next time.
      this.dataset.submitted = '';
      // If it returns false, it will not be executed.
      return true;
    } else {
      return false;
    }
  }
});
```

**Comment by onozaty** [comment]
Is the "Insert Position" set to "Bottom of issue form"?
If it is "Bottom of issue form", it will be executed again when you change the status and replace the input form.

The submit button is outside the scope of replacement, so the event will be registered as a duplicate.

Could you please try changing the following?

* Path Pattern `/issues/`
* Insert Position `Head of all pages`

Thanks.

**Comment by maksnet2** [comment]
Да, было "Bottom of issue form"
> * Вставить позицию `Head of all pages`

Так вообще не выводит предупреждение.
А вот с  `Bottom of all pages` работает как надо. Еще раз спасибо огромное за ваш плагин и вашу помощь.
