### ISSUE TITLE
side bar

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#70]
[https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0004.toggle_sidebar/example.md](url)
can u check why this example not working in redmine4.2.3

**Comment by onozaty** [comment]
On my end, it works fine with 4.2.3.
It may be that some other plugin is affecting it.

![sidbar](https://user-images.githubusercontent.com/47337/152350599-5ce3a6c9-0a5b-4000-ba21-b1993ebc1747.gif)

Thanks.
