### ISSUE TITLE
How to Arrange Custom Fields in the New Issue Screen without Splitting into Left and Right.

### ISSUE THREAD

**Issue by bhetsko** [onozaty/redmine-view-customize-scripts#71]
Is there a way to place a Custom Field where the format is Long Text without the "splitcontent" as all of your examples include?   It seems like it should be simpler, but I am struggling.  Essentially I want to move a custom long text box to right after the description without splitting the screen into left and right.  Thanks in advance.

**Comment by onozaty** [comment]
I wrote a example.
Please refer to the following for more information.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0045.move_long_text_custom_field_to_after_description/example.md

Thanks.

**Comment by bhetsko** [comment]
Thank you so much for the quick response!  I was very close, just one syntactical mistake.  On my system, using the exact code you provided, with just "..._1" changed to "..._119", the Description input box still shrinks to a split screen size.  Any idea why?

![image](https://user-images.githubusercontent.com/46752326/152345024-2c4e49fe-70a5-47d5-9684-d11763fc86a0.png)

**Comment by onozaty** [comment]
Does this mean that if you run this code, the description will be cut in half?

Maybe there is some difference in the environment.
What version of Redmine are you running?

**Comment by bhetsko** [comment]
4.2.2   It appears to be have been sporadic and hasn't happened again since I restarted everything.  It must have been something stuck in memory.  Thank you so much again!

**Comment by onozaty** [comment]
I'm glad to hear it went well.
