### ISSUE TITLE
Refresh data ViewForm after submit Form with Request (API)

### ISSUE THREAD

**Issue by alphcom** [onozaty/redmine-view-customize-scripts#72]
I created a script that called a WebHook function (API) that met the days of the request fields.
Unfortunately when the submit function is finished, the info is not updated in the display view, how to do?

![ScriptAPI-Refresh](https://user-images.githubusercontent.com/39519200/152795108-665a7714-db16-4417-9636-cfcd284590d9.gif)

Script : 
```javascript
$(function () {
  $('#issue-form').submit(function () {
    const parentIssueId = ViewCustomize.context.issue.id;
    const StatutId = $('#issue_status_id').val();
    const IssueDemandeId = $('#issue_custom_field_values_10').val();

    if (StatutId !== '1' && IssueDemandeId !== null) {
      return $.ajax({
        type: 'POST',
        url:
          'https://XXXXXXXX.XXX',
        data: { issue: parentIssueId },
        dataType: 'html',
        success: function (data) {
          location.reload();
        },
      });
    }
  });
});

```

Thanks !

**Comment by onozaty** [comment]
Submit will refresh the screen, so you cannot refresh it afterwards.
I think the submit needs to be done after the API call succeeds.
However, I have no idea of a good way to submit after a successful API call...

Thanks.
