### ISSUE TITLE
administrator

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#73]
depend in the last example 
[https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0034.hide_delete_and_lock_buttons_for_specific_user/example.md](url)

u hide the buttom (delete,lock) but still the another admin can open the page for main admin user and maybe change her password
(/user/1/edit)

how i can hide also LOGIN name to another admin and cant open her page

**Comment by ashrafalzyoud** [comment]
`$('tr:has(a[href="/users/1/edit"])').hide();`

**Comment by ishikawa999** [comment]
How about the following code?
```js
$('td.username a').each(function(index, element) { $(element).replaceWith($(element).text())});
```

**Comment by ashrafalzyoud** [comment]
how i can prevent user_id 2 change her password

**Comment by ashrafalzyoud** [comment]
`<a class="icon icon-passwd" href="/my/password">Change password</a>` for all users and another admin
just only super admin user_id=1

**Comment by ishikawa999** [comment]
```js
$(function() {
  let allowUserIds = [1, 2]
  if (!allowUserIds.includes(ViewCustomize.context.user.id)) {
    $('#user_admin').prop('disabled', true);
    $('td.username a').each(function(index, element) { $(element).replaceWith($(element).text())});
  }
});
```

**Comment by ashrafalzyoud** [comment]
![Untitled](https://user-images.githubusercontent.com/50211455/153790155-22e7c86d-508d-471e-94d4-b569a1bb9a01.png)
i want hide change password for all users

**Comment by ishikawa999** [comment]
/my/account
```js
$(function() {
  $('a.icon-passwd').remove();
});
```

**Comment by ashrafalzyoud** [comment]
![Untitled1](https://user-images.githubusercontent.com/50211455/153791201-bc06c353-7102-4844-b79c-55cb82fbdba2.png)
still another admin,not super admin can open her account and change it
how i can hide `<div id="password_fields" style="">`

**Comment by onozaty** [comment]
Thank you for your support,  @ishikawa999 san.

Hi @ashrafalzyoud 
It can be hidden by `hide()` or `remove()` the target element.

```javascript
$(function() {
  $('#password_fields').hide();
});
```

Thanks

**Comment by ashrafalzyoud** [comment]
all code work when im open in my pc
but in my mobile not working

**Comment by ashrafalzyoud** [comment]
im hide home and help in top menu
![Untitled2](https://user-images.githubusercontent.com/50211455/154192139-22dbcc0f-c5fb-4a4b-a8f9-d8b26557d17a.png)
on mobile or resize pc to mobile
![Untitled1](https://user-images.githubusercontent.com/50211455/154192184-047c0274-87ff-48c8-868f-f8bc2b8ed2c7.png)
i think all code not work in mobile

**Comment by onozaty** [comment]
I think it's because the layout changes on mobile.
Please check with Chrome's DevTools or other tools.

![image](https://user-images.githubusercontent.com/47337/154376001-625fcf80-ad99-41e5-bed6-f6656f042566.png)

Just write a selector that specifies the target element.

```javascript
$('a.help').remove();
```

Thanks.

**Comment by onozaty** [comment]
> I think it's because the layout changes on mobile. Please check with Chrome's DevTools or other tools.
> 
> ![image](https://user-images.githubusercontent.com/47337/154376001-625fcf80-ad99-41e5-bed6-f6656f042566.png)
> 
> Just write a selector that specifies the target element.
> 
> ```js
> $('a.help').remove();
> ```
> 
> Thanks.

The `help` was the same selector on mobile and pc, how did you hide `help`?
