### ISSUE TITLE
How to give a sequential serial number depends on inheritance؟

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#74]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link id=Main-File rel=Main-File
href="file:///C:\Users\ASHRAF~1.ALZ\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\ASHRAF~1.ALZ\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

seial | subject | tracker
-- | -- | --
1-0-0-0 | TEST 1 | A
1-1-0-0 | TEST 2 -> SUBTASK FROM TEST 1 | B
1-1-1-0 | TEST 3 -> SUBTASK FROM TEST 2 | C
1-1-1-1 | TEST 4 -> SUBTASK FROM TEST 3 | D
  |   |  
2-0-0-0 | EXAMPLE 1 | A
2-1-0-0 | EXAMPLE 2 -> SUBTASK FROM EXAMPLE 1 | B
2-1-1-0 | EXAMPLE 3 -> SUBTASK FROM EXAMPLE 2 | C
2-1-1-1 | EXAMPLE 4 -> SUBTASK FROM EXAMPLE 3 | D
2-1-2-0 | EXAMPLE 5 -> SUBTASK FROM EXAMPLE 4 | C
2-1-2-1 | EXAMPLE 6 -> SUBTASK FROM EXAMPLE 5 | D

</body>

</html>

**Comment by onozaty** [comment]
Where will this serial number be displayed?

I think it would be difficult to achieve this in View customize because not all of the parent/child information exists, even in the Issue list.

Thanks.

**Comment by ashrafalzyoud** [comment]
> Where will this serial number be displayed?
>  in issue list cfs(1) and format text
> 
> 
> I think it would be difficult to achieve this in View customize because not all of the parent/child information exists, even in the Issue list. 
What information u want ?!
> 
> 
> 
> Thanks.

**Comment by onozaty** [comment]
> > Where will this serial number be displayed?
>  in issue list cfs(1) and format text

Do you mean using View customize to put values into custom fields?

> > I think it would be difficult to achieve this in View customize because not all of the parent/child information exists, even in the Issue list.
> What information u want ?!

View customize works based on the information displayed on the screen, etc.
In order to assign a serial number, we need information on all issues, but of course such information is not on the screen.
It is also not practical to retrieve this information via a REST API.

Therefore, it is difficult to achieve this.
