### ISSUE TITLE
I can't get boolean custom field and calculated custom field

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#75]
Hi,
Thank you for this plugin.
Now, I have a problem when I get values from custom fields.
Example:
_const medidaPlan= $('#issue_custom_field_values_139').val();_ 
**OK,** -> medidaPlan return the correct value. This custom field its a list field.
If the custom_field its a Boolean, return **'undefined**'.  How I can get the value in a variable. I hope to get a '0/1' or 'True/False'

If the custom field correspond to a calculated_custom_field, but the value its included in the database,  return **'undefined**' too.

How I can to get the value of a custom field of the project that correspond the issue?

Thank you in advance.
Regards

**Comment by onozaty** [comment]
Hi @jlsblasco 

In the case of a boolean, it can be obtained with the following code.

```javascript
// checked: 1, unchecked: undefined
const val = $('#issue_custom_field_values_1:checked').val();
```

```javascript
// checked: true, unchecked: false
const val = $('#issue_custom_field_values_1').prop('checked');
```

However, in the case of your code, I think it would return '1' instead of undefined.
Also check that the ID of the custom field you specify is correct.

Thanks.

**Comment by jlsblasco** [comment]
Thank you for you reponse.
But, I haven´t a good code. I test with diferent parameters. My code:
const val1 = $('#issue_custom_field_values_147:checked').val();
const val2 = $('#issue_custom_field_values_147').prop('checked');
const val3= $('#issue_custom_field_values_147').val();
const val4 = $('#issue_custom_field_values_147');

$('#content').prepend('<div class="warning">val1: '  +  val1 + ' - val2: ' + val2 + ' - val3: ' + val3 + ' - val4: ' + val4 +  '  -.</div>');

The code return:
val1: undefined - val2: undefined - val3: undefined - val4: [object Object] -.

Thank you in advance

**Comment by onozaty** [comment]
Looking at the results, I think the element `id="issue_custom_field_values_147"` may not exist.
Could you please check Chrome's DevTools or other tools to see what the element you want to retrieve looks like?

![image](https://user-images.githubusercontent.com/47337/159245076-fcf3dd31-4a90-49bb-96e5-48044d11e961.png)

Thanks.

**Comment by jlsblasco** [comment]
Hi again, this is a splitted message from chrome devtool. You can search '147':
"  <p><label><span>Imputable a Ampliación</span> <span class="required">*</span></label><span class="bool_cf check_box_group"><label><input type="radio" name="issue[custom_field_values][147]" value="1" /> Sí</label><label><input type="radio" name="issue[custom_field_values][147]" value="0" checked="checked" /> No</label></span></p>"

****** More messages:
Requisitos No Funcionales
" class="field-description">Documentos Adjuntos</span></label><span class="list_cf check_box_group"><label><input type="checkbox" name="issue[custom_field_values][4][]" value="Requisitos Funcionales" /> Requisitos Funcionales</label><label><input type="checkbox" name="issue[custom_field_values][4][]" value="Requisitos No Funcionales" /> Requisitos No Funcionales</label><input type="hidden" name="issue[custom_field_values][4][]" value="" /></span></p>
  <p><label><span title="lista de documentos entregados por el proveedor" class="field-description">Documentos Proveedor</span></label><span class="list_cf check_box_group"><label><input type="checkbox" name="issue[custom_field_values][22][]" value="Diseño y arquitectura" /> Diseño y arquitectura</label><label><input type="checkbox" name="issue[custom_field_values][22][]" value="Plan de Pruebas" /> Plan de Pruebas</label><label><input type="checkbox" name="issue[custom_field_values][22][]" value="Codigo Fuente" checked="checked" /> Codigo Fuente</label><label><input type="checkbox" name="issue[custom_field_values][22][]" value="Resultado del Plan de Pruebas" /> Resultado del Plan de Pruebas</label><label><input type="checkbox" name="issue[custom_field_values][22][]" value="Manual Usuario" /> Manual Usuario</label><label><input type="checkbox" name="issue[custom_field_values][22][]" value="Manual Operacion" /> Manual Operacion</label><label><input type="checkbox" name="issue[custom_field_values][22][]" value="Manual Administracion" /> Manual Administracion</label><label><input type="checkbox" name="issue[custom_field_values][22][]" value="Otros" /> Otros</label><input type="hidden" name="issue[custom_field_values][22][]" value="" /></span></p>
  <p><label for="issue_custom_field_values_137"><span>Anulacion ANS</span> <span class="required">*</span></label><span class="bool_cf"><input type="hidden" name="issue[custom_field_values][137]" value="0" /><input type="checkbox" name="issue[custom_field_values][137]" id="issue_custom_field_values_137" value="1" /></span></p>
  <p><label><span>Imputable a Ampliación</span> <span class="required">*</span></label><span class="bool_cf check_box_group"><label><input type="radio" name="issue[custom_field_values][147]" value="1" /> Sí</label><label><input type="radio" name="issue[custom_field_values][147]" value="0" checked="checked" /> No</label></span></p>
  <p><label for="issue_custom_field_values_139"><span title="Lista de Medidas" class="field-description">Medidas Plan de Digitalización</span> <span class="required">*</span></label><select name="issue[custom_field_values][139]" id="issue_custom_field_values_139" class="list_cf"><option value="">--- Por favor seleccione ---</option><option value="0. Presupuesto ordinario">0. Presupuesto ordinario</option>


Thank you again.

**Comment by jlsblasco** [comment]
Sorry the message its corrupted... I put images . The line is  the number 1313
![msg2](https://user-images.githubusercontent.com/50949839/159252075-ec959751-0eb7-43c8-9af2-89ea49940f91.PNG)
![msg3](https://user-images.githubusercontent.com/50949839/159252077-26e12e83-41e0-415d-9357-8569a641b9a8.PNG)
![msg4](https://user-images.githubusercontent.com/50949839/159252081-2fd78762-96ec-4a24-bef8-59eb0f34e5c8.PNG)
![msg1](https://user-images.githubusercontent.com/50949839/159252082-e19388d7-923a-414e-a062-a7b1c159cf77.PNG)

**Comment by onozaty** [comment]
Thank you very much.

Could you also give me a capture of the custom field setup screen?
I am wondering what the Format, etc. is.

Thanks.

**Comment by jlsblasco** [comment]
![image](https://user-images.githubusercontent.com/50949839/159257836-93e07eec-d0cd-45d8-af0a-f7634b533860.png)

In ENglish :exclusive radio buttons
regards

**Comment by onozaty** [comment]
With the radio button, it was necessary to do the following.

```javascript
const val = $('input[name="issue[custom_field_values][147]"]:checked').val();
```

Thanks.

**Comment by jlsblasco** [comment]
Thank you very much, Now I can get the value.
With a calculated field?
<div class="cf_72 attribute"><div class="label"><span title="campo calculado de proyecto" class="field-description">LOTE</span>:</div><div class="value">PA-RCP-NEDAES</div>
![image](https://user-images.githubusercontent.com/50949839/159446127-6f8f201c-2990-4b1b-acb8-dd20f1b391ed.png)

With this sintax, return 'undefined'
const lote = $('#issue_custom_field_values_72).val();

Any solution with calculated_fields?

A need to get a normal custom field correspond to the project of the task, ¿how I can to get it? 

Thank you for you support.

**Comment by jlsblasco** [comment]
![lote](https://user-images.githubusercontent.com/50949839/159446874-ea9cf876-8a4f-483b-b3db-f62cf5dd883a.PNG)

**Comment by onozaty** [comment]
I don't know how to get the value of calculated field, but you can use `ViewCustomize.context` to get the value of the custom field for project.

* https://github.com/onozaty/redmine-view-customize#viewcustomizecontext-javascript

```javascript
const field = ViewCustomize.context.project.customFields.find(x => x.id == 36);
const value = (field == undefined) ? undefined : field.value;
```

Thanks.

**Comment by jlsblasco** [comment]
Thank you for you support, it's very important for my project this plugin. Congrats.
