### ISSUE TITLE
problem with roles and permissions

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#78]
Hi again,
I have a unknow problem.
I have these lines:
*******************
const imputableAmpliacion = $('input[name="issue[custom_field_values][147]"]:checked').val();
const medidaPlan= $('#issue_custom_field_values_139').val();

const field = ViewCustomize.context.project.customFields.find(x => x.id == 36);
const lote = (field == undefined) ? undefined : field.value;
const field2 = ViewCustomize.context.project.customFields.find(x => x.id == 55);
const area = (field2 == undefined) ? undefined : field2.value;

const tipo_tarea = $('#issue_tracker_id').val();

$('#content').prepend('<div class="warning">Lote: ' + lote + ' Area: ' + area +' Media Plan:  ' + medidaPlan + '  Imputable Ampliacion:' + imputableAmpliacion + ' TIPO TAREA: ' + tipo_tarea +  '  -.</div>');

********************
When I execute a task with a user with _**Write**_ permission in the fields, return:
Lote: _**Lote 7: Aplicaciones Horizontale**_s Area: _**FUNAUT**_ Media Plan: _**0. Presupuesto ordinario**_ Imputable Ampliacion:_**0**_ TIPO TAREA: _**4**_ -.
OK , perfect.

When I execute the same task with a user with _**Read Only**_ permission in the fields, return:
Lote: _**Lote 7: Aplicaciones Horizontales**_ Area: _**FUNAUT**_ Media Plan: _**undefined**_ Imputable Ampliacion:_**undefined**_ TIPO TAREA: _**undefined**_ -.

Which it's the problem? the user have read permission, and the fields are in the screen but the code return 'undefined'.
The fields 'area' and 'lote' corresponding to a project custom fields, return ok in both.

Thank you in advance.
Regards

**Comment by jlsblasco** [comment]
Another question,
How to get the number of ROLE  of the user that view a task?
Thank you

**Comment by jlsblasco** [comment]
More information...
![image](https://user-images.githubusercontent.com/50949839/162190208-ae7d4ee0-c119-4107-b1a6-56ffcdbe04f4.png)

I need to get the id of the role.
This is an image from DevTool
I test with a 
const role= ViewCustomize.context.project.roles.id;
but return -> undefined

**Comment by onozaty** [comment]
> When I execute the same task with a user with _**Read Only**_ permission in the fields, return: Lote: _**Lote 7: Aplicaciones Horizontales**_ Area: _**FUNAUT**_ Media Plan: _**undefined**_ Imputable Ampliacion:_**undefined**_ TIPO TAREA: _**undefined**_ -.
> 
> Which it's the problem? the user have read permission, and the fields are in the screen but the code return 'undefined'. The fields 'area' and 'lote' corresponding to a project custom fields, return ok in both.
> 
> Thank you in advance. Regards

The value of the input form that exists in HTML is retrieved.
If it is read-only, the input form does not exist and cannot be retrieved.

There are other methods, such as retrieving the displayed string, but depending on the type of item, it may not be possible to get the same value as in the input form.

```javascript
const medidaPlan = $('.cf_139 .value').text()
```

Thanks.

**Comment by onozaty** [comment]
> More information... ![image](https://user-images.githubusercontent.com/50949839/162190208-ae7d4ee0-c119-4107-b1a6-56ffcdbe04f4.png)
> 
> I need to get the id of the role. This is an image from DevTool I test with a const role= ViewCustomize.context.project.roles.id; but return -> undefined

Roles are listed.
Can you please refer to the following code to check if you have a role?

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/tips/tips.md#check-the-roles

**Comment by jlsblasco** [comment]
Thank you for you quick response.
The solution:
const medidaPlan = $('.cf_139 .value').text()
its valid for me.

Thank you very much for the fantastic plugin.
