### ISSUE TITLE
get tracker return undefined

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#79]
Hi again,
I have a big problem when I get the value of tracker.
The core:
const tipo_tarea = $('#issue_tracker_id').val();
return the correct value only when 'admin' user. With other users return 'undefined'.

I test with code:
const tipo_tarea = $('.issue_tracker_id.value').text();

But its not valid.

Which its the correct code for take the value with diferent users and roles?

Thank you for the fantastic plugin.
Regards

**Comment by onozaty** [comment]
Hi @jlsblasco 

Is this the case when the tracker is operated by a user that cannot be changed?
It is the same factor as below, but I'll give it some thought to see if there is any way around it.

* #78 

Thanks.

**Comment by jlsblasco** [comment]
Hi again,
Yes, is the case when the tracker is operated by a user thar cannot  be changed.
The use its a first filter for generate advise with conditions, but if the user don't have access 'rw' over the field, the rest of the code is wrong.
If you have an new idea .......
thanks

**Comment by onozaty** [comment]
It will be assigned something like tracker-1 as an HTML class.

![image](https://user-images.githubusercontent.com/47337/164224523-981f59c3-f0b4-4398-881a-585ab17cfd63.png)

By using this, the value could be retrieved.

```javascript
$('div.issue').attr('class').match(/tracker-([0-9])+/)[1]
```

Thanks.

**Comment by jlsblasco** [comment]
Hi, its a very good solution for me.
Thank you very much for you support.
Regards
