### ISSUE TITLE
About View customize plugin script

### ISSUE THREAD

**Issue by lilyroselily** [onozaty/redmine-view-customize-scripts#8]
@onozaty 
hi,onozaty,i'm looking for the plugins that the assignee field can be displayed by group or role.
so,i find the webpage:http://blog.enjoyxstudy.com/entry/2015/08/10/000000 (Redmineで担当者を特定のルールでグループ化し、グループ毎に表示する(View customize plugin) )
but the following script webpage can't be opened:
Type、Code
Type:JavaScript として、下記スクリプトを登録します。

**Grouping assign user selectbox (Redmine view custo mize)**
so may u  please send the script to me by mail , thanks  a lot ^0^

**Comment by onozaty** [comment]
Hi @lilyroselily 

There is a script below, but can not you open it?
* https://gist.github.com/onozaty/52e04222efd0689c0dc4

This script is grouped by user name.
It can not be done with roles or groups.
This is because View customize only handles information that exists on the screen.

Regards

**Comment by lilyroselily** [comment]
thanks for the information,
now ,I use the plugin to resolve my request : alexbocharov/redmine_custom_view_assigned 
thank u again.
best regards :)
