### ISSUE TITLE
How to refresh data in form when modify issue and cancel.

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#80]
Hi,
I have a problem with the redmine forms in issue. The steps:
1* in a task , I put modify
2* I fill the fields with the selection, write in text field or other combinations that in the form exists.
3* cancel the modify
4* put modify again
5* the last modify include in the step 2 appears on the form ( the modify was cancelled in step 3), The values are cached.

I need to when put modify again (step 4) the values on the form correspond to the true values and not the last values included in the form. 
If I recharged the form with F5 between the step 3 and 4, the behavior its correct. 
It's possible to include in the header of the issues a 
<meta http-equiv="Pragma" content="no-cache"> <meta http-equiv="Expires" content="-1">

or

<% Response.CacheControl = "no-cache"; %> <% Response.AddHeader("Pragma", "no-cache"); %> <% Response.Expires = -1; %>

or other solution?

Thank you in advance

**Comment by jlsblasco** [comment]
Hi again, the possible solution can be  modify the cancel button behavior for a refresh the issue. ¿its possible?

**Comment by onozaty** [comment]
I think the cancel button is the way to reload.
I will try it here later.

Thanks.

**Comment by onozaty** [comment]
With the following code, I was able to reload with the cancel button.

```javascript
$(function() {

  const cancel = $('#issue-form input[type="submit"]').next();
  cancel.on('click', function() {
    location.href = location.href;
  });

});
```

Thanks.

**Comment by jlsblasco** [comment]
Ohhh... You are mi hero.
Now , when cancel, the task refresh an don't appear the old values in the form.
Thank, you an best regards
