### ISSUE TITLE
How to write in a custom field?

### ISSUE THREAD

**Issue by jlsblasco** [onozaty/redmine-view-customize-scripts#81]
Hi, I need to write in a custom field depending of the status.
Example:

$(function() {

const visible = $('#issue_status_id').val() == '9';

if (visible) {

$('#issue_custom_field_values_164').val('');
;
      }

});
**** the custom field its a text field , number 164, normaly this field have information, but when the statsu = 9  I need to change to ' '.
In the chrome debug the process say:
<input type="text" name="issue[custom_field_values][164]" id="issue_custom_field_values_164" value="escribo motivo 2 de 2 en uno" class="string_cf">
and I need to replace 
value="escribo motivo 2 de 2 en uno"
to 
vale = ""
its possible?

**Comment by onozaty** [comment]
Hi @jlsblasco 

I'm sorry.
I didn't quite understand what you wanted to solve.
Could you please explain in more detail?

Thanks

**Comment by jlsblasco** [comment]
Hi again,
I need to change the value of a cumtom field when the state of the task change to '9'.
the custom field its the number 164.
Regards

**Comment by onozaty** [comment]
I think the sample code you wrote will work fine.

```javascript
$(function() {
  const visible = $('#issue_status_id').val() == '9';
  if (visible) {
    $('#issue_custom_field_values_164').val('');
  }
});
```

Does this mean it is not working well?

**Comment by jlsblasco** [comment]
Hi, the process run ok and now I understand the process.
The process don't write in the database, only show the value in the custom field in the form.
For me its valid, because I can force to have 20 chracters in the field, and write a comment with less characters, and then the form send a message for fill the field with a message more long. 

Thank you for you very good support.

**Comment by jlsblasco** [comment]
Hi, I need you support again,
With:
1) const beforeIssueStatusId = $('#issue_status_id').val();
I take the value of the status id.
but
It's possible to take the value before change?
Example:
Now, the task its in the status 2.
Ejecute the sentence 1) and return the value '2' - OK.
Now, change to status 3
with the  1) sentence always take the value '3'. I need to take both values, actual status and before status. 
Its possible to taje the value of status before y after change  it.
Thank you in advance

**Comment by onozaty** [comment]
Please refer to the following for how to obtain the value before the change.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/tips/tips.md#check-the-value-before-the-change

Thanks.

**Comment by jlsblasco** [comment]
Hi again,
 The code:

$(function() {

const target = '#issue_status_id';
let prevValue = $(target).val();

$('#content').prepend('<div class="warning">**Before function** - old:  ' + prevValue + ' new:' + $(target).val() + ' -.</div>');

$('#all_attributes').on('change', target, function() {

 $('#content').prepend('<div class="warning">**After function** Estado old:  ' + prevValue + ' new:' + $(target).val() + ' -.</div>');  
 
 prevValue = $(target).val();
});

});
**********

I change ythe status of the task but always only send the **Before function** message, but never the **After function** message

Where is the error?
Regards

**Comment by onozaty** [comment]
I tried it and it seemed to work fine.

![20220615](https://user-images.githubusercontent.com/47337/173858621-8b5ad27d-02dd-4a8a-a165-f8030c5e9d5b.gif)

```javascript
$(function() {

  const target = '#issue_status_id';
  let prevValue = $(target).val();

  $('#content').prepend('Before function - old: ' + prevValue + ' new:' + $(target).val() + ' -.');
  $('#all_attributes').on('change', target, function() {

    $('#content').prepend('After function Estado old: ' + prevValue + ' new:' + $(target).val() + ' -.');
    prevValue = $(target).val();
  });

});
```

**Comment by jlsblasco** [comment]
sorry I test again and work perfectly.
Thank you so much for you support
