### ISSUE TITLE
how i can prevent user to add randomly subtask

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#82]
if parent tracker _id= 1 when i added subtask its must tracker id = 2
if parent tracker _id= 2 when i added subtask its must tracker id = 3
if parent tracker _id= 3 when i added subtask its must tracker id = 4

![173696534-9f18546f-dc16-4541-b454-066972a12469](https://user-images.githubusercontent.com/50211455/174972725-85aca7a6-ebc6-452d-87b4-ac9d5b66f800.png)

if the user added bill must be under company .... 
and error msg The invoice can only be added to the company tracker!

**Comment by onozaty** [comment]
To check by TrackerID of the parent Issue, you need to use the REST API to get information about the parent Issue.
An example of REST API is written below.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/tips/tips.md#using-the-rest-api-to-fetch-issue

However, the process is more complicated, so it is not recommended if you are not good at coding.

Thanks.
