### ISSUE TITLE
message hent depend in tracker ID

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#83]
CAN u give message hint to user depend in tracker ID
TRACKER_ID =1  MESSAGE HINT ( ABCD )
TRACKER_ID = 2 MESSAGE HINT ( EFRT)

**Comment by onozaty** [comment]
Below is a sample that changes the contents of the display according to the tracker.
Would you be able to help me with this?

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0003.set_default_value_by_tracker/example.md
* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0046.narrow_down_categories_according_to_tracker/example.md
