### ISSUE TITLE
how i can hide users in assignee

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#84]
how i can hide the users when im assignee just show groups for the user

**Comment by onozaty** [comment]
Sorry, can you be more specific about what you would like to do?

**Comment by ashrafalzyoud** [comment]
as u know ( assignee)  maybe users or groups 
users ( adam,mickle,....)
groups ( group 1,group2,group3,.....)

i want hide the users and show groups only

**Comment by ashrafalzyoud** [comment]
@onozaty

**Comment by ashrafalzyoud** [comment]
Here plz if u can help @onozaty

**Comment by onozaty** [comment]
Please wait as I have not yet been able to confirm this.

**Comment by onozaty** [comment]
Please refer to the following example.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0050.display_only_group_in_assignee/example.md

**Comment by ashrafalzyoud** [comment]
perfect man
realy your plugin its the basic function in redmine
thx for your support and help
how i can get the value group
im try thats code depend in status id
```
$(function() {

  if (!$('form').hasClass('new_issue')) {
    // Do not process on edit
    return;
  }

  // Estimated time, Assignee
  switch($('#issue_status_id').val()) {
    case '1':
      $('#issue_groups_to_id').val('49');
      break;

      break;
  }
});
```

**Comment by ashrafalzyoud** [comment]
How assigne to group id

**Comment by onozaty** [comment]
> How assigne to group id

Same as for users.

```javascript
$('#issue_assigned_to_id').val('49');
```

In Redmine, user IDs and group IDs are assigned in such a way that they do not overlap.
