### ISSUE TITLE
redmine_issue_dynamic_edit

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#85]
its there not compitable with this plugin
https://github.com/ilogeek/redmine_issue_dynamic_edit

**Comment by onozaty** [comment]
> its there not compitable with this plugin https://github.com/ilogeek/redmine_issue_dynamic_edit

Does it mean that some error occurs?

**Comment by ashrafalzyoud** [comment]
No any code excute 
Only when I'm open the issue and edit it 
Not compitable

**Comment by onozaty** [comment]
Sorry, I can't follow up to the special behavior by other plugins.
