### ISSUE TITLE
Set t value by status

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#86]
if new issue or edit issue 
im try this code but not work  depend in this example
https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0003.set_default_value_by_tracker/example.md
```

$(function() {

  switch($('#issue_status_id').val()) {
    case '1':
      $('#issue_assigned_to_id').val('49');
      break;

    case '2':
      $('#issue_assigned_to_id').val('46');
      break;

    case '3':
      $('#issue_assigned_to_id').val('9');
      break;
  }
});
```
```

**Comment by onozaty** [comment]
It doesn't look like a code that might have a problem.

Is the Insert Position correct?

**Comment by ashrafalzyoud** [comment]
Not work when edit or new issue
And can't make default value
U can test it

**Comment by onozaty** [comment]
Sorry, the above code works fine in my environment.
Therefore, the problem is not clear to me.

**Comment by ashrafalzyoud** [comment]
im try many times in this code
its work after im save issue 2 or 3 times
not when im editing issue direct
and im try with code 
**how i can choose the first option in mmy group while th**e `NEW ISSUE`
```
$(function() {

  if ($('form').hasClass('new_issue')) {
     $('#issue_assigned_to_id').val('1'); // how i can chose the first otion in my groups//
    return;
  }

  // edit issue
  switch($('#issue_tracker_id').val()) {
    case '1':
      $('#issue_assigned_to_id').val('2');
      break;

    case '2':
      $('#issue_assigned_to_id').val('3');
      break;

    case '3':
      $('#issue_assigned_to_id').val('4');
      break;
  }
});
```
i found many toipc  `Javascript-to-select-first-option-of-select-list`
```
selectTags = myForm.getElementsByTagName("select");

for(var i = 0; i < selectTags.length; i++) {
  selectTags[i].selectedIndex =0;
}  
```

```
function changeSelect(){
  document.getElementById("select1").value = document.getElementById("select1").getElementsByTagName('option')[0].value;
}; 
```
@onozaty

**Comment by onozaty** [comment]
It is working fine in my environment.

![86](https://user-images.githubusercontent.com/47337/182005744-e0a08755-8dad-4017-a599-83bd00c03a05.gif)

There may be a problem specific to your environment.
For example, other plug-ins are affecting it.

**Comment by ashrafalzyoud** [comment]
I'm using this plugin 

https://github.com/farend/redmine_searchable_selectbox

It's only plugin working in edit issue

**Comment by ashrafalzyoud** [comment]
`how i can choose the first option in my list group??
`
i need this function because i have 55 group and i put all im need in first option choose

**Comment by onozaty** [comment]
redmine_searchable_selectbox uses a library select2.
Therefore, the following is required.

* https://select2.org/programmatic-control/add-select-clear-items#selecting-options

```javascript
$('#issue_assigned_to_id').trigger('change');
```

Could you please give it a try?

**Comment by onozaty** [comment]
@ashrafalzyoud 

I feel that I am being rushed to respond by you.
However, I am not your coder.

I have taken the time to help you a lot, but mostly with technical stuff related to JavaScript, not View customize. And I have never been sponsored by you.

I would suggest you hire an engineer to take a look at your Redmine.

**Comment by ashrafalzyoud** [comment]
@onozaty 
Thank you for your constant, continuous and appreciated help from us, I am a senior officer in the Jordanian public security and here in my country there is no engineer who knows the language and fields of the program redmine.
I regret from you
 from my many requests, coveting your generosity and good dealings

**Comment by onozaty** [comment]
> @onozaty Thank you for your constant, continuous and appreciated help from us, I am a senior officer in the Jordanian public security and here in my country there is no engineer who knows the language and fields of the program redmine. I regret from you from my many requests, coveting your generosity and good dealings

I don't think it is necessary to know Redmine.
Any engineer with knowledge of web clients can help you.

**Comment by onozaty** [comment]
> `how i can choose the first option in my list group?? ` i need this function because i have 55 group and i put all im need in first option choose

```javascript
$('#issue_assigned_to_id').val($('#issue_assigned_to_id > optgroup > option:nth-child(1)').val());
```

**Comment by ashrafalzyoud** [comment]
thx alot for uuuuuuu
@onozaty
