### ISSUE TITLE
issue counter in my home

### ISSUE THREAD

**Issue by ashrafalzyoud** [onozaty/redmine-view-customize-scripts#87]
its nice idea if u can help
to issue counter depend in query show number in page like this pic
![6666666](https://user-images.githubusercontent.com/50211455/181134293-03a47a94-0064-4383-b7bf-d9e9960b4297.png)

**Comment by onozaty** [comment]
I don't think it is possible with View Customize.
This is because it is not possible to get the number information.

I think it is difficult unless it is made as a dedicated plugin.

Thanks.
