### ISSUE TITLE
How to use Custom fields enumerate

### ISSUE THREAD

**Issue by CharlyD85** [onozaty/redmine-view-customize-scripts#88]
I would like to get the text of a Custom filed witch is a enumerate type.
Using this code $('#issue_custom_field_values_xx').val() return me only the number of the enumerate choice but not the text linked to that number.

Do you have an idea?

**Comment by onozaty** [comment]
You can get the display name by doing the following.

```javascript
$('#issue_custom_field_values_1 > option:selected').text();
```

I have added the following as well.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/tips/tips.md#get-the-value-of-a-issue-field

Thanks.

**Comment by onozaty** [comment]
I think it has been resolved, so I will close it.
If it has not been resolved, please reopen it.
