### ISSUE TITLE
How can I Display custom field checkboxes in 4 columns, when the customfield_id=14?

### ISSUE THREAD

**Issue by cbmarchetti** [onozaty/redmine-view-customize-scripts#89]
Hi!
How can i do this?

#issue_custom_field_values_14  {
span.enumeration_cf.check_box_group {
  column-count: 4;
  -moz-column-count: 4;
  -webkit-column-count: 4;
}

**Comment by ishikawa999** [comment]
In my environment, I set the following and it worked.
<img width="457" alt="screenshot 2022-08-01 9 38 58" src="https://user-images.githubusercontent.com/14245262/182052813-937d8943-cc54-488a-9a85-a6e18597a538.png">

<img width="714" alt="screenshot 2022-08-01 9 40 51" src="https://user-images.githubusercontent.com/14245262/182052819-16be67ef-de63-428f-8c62-aaefd6f76fdc.png">

**Comment by cbmarchetti** [comment]
Sorry, the above code it's no working in my environment.

![image](https://user-images.githubusercontent.com/104323419/182064718-3063de21-36d0-4b54-9d1e-e05e244a7de1.png)

**Comment by ishikawa999** [comment]
It worked fine with Redmine 4.2.4.stable in my environment.
Is the Format of the custom field a List?
If it is a List, you will need to change the CSS as follows:
```css
span.list_cf.check_box_group.cf_14 {
  column-count: 4;
  -moz-column-count: 4;
  -webkit-column-count: 4;
}
```

**Comment by cbmarchetti** [comment]
the custom field is enumeration cf_82
![image](https://user-images.githubusercontent.com/104323419/182169254-c828515a-9165-492d-8770-ab8da370a7e6.png)


Test 1:
![image](https://user-images.githubusercontent.com/104323419/182168438-f1f0f5de-40ae-4a1b-8d50-9cad40d81451.png)
![image](https://user-images.githubusercontent.com/104323419/182168315-c6bbcac0-07c7-42ae-b4de-49fcfbe6b364.png)

Test 2:
![image](https://user-images.githubusercontent.com/104323419/182168640-4156a49e-d327-44d9-8673-8f2b305b9e02.png)
![image](https://user-images.githubusercontent.com/104323419/182168730-da2b45c2-9f97-4cce-9b26-45b74e196294.png)

**Comment by ishikawa999** [comment]
Umm, I don't know what caused this. I'm sorry I couldn't help you.

**Comment by onozaty** [comment]
It works fine in my environment.

```css
span.enumeration_cf.check_box_group.cf_5 {
  column-count: 4;
}
```

![image](https://user-images.githubusercontent.com/47337/182395408-25961592-5301-4344-bf4a-54b9d379c33c.png)

I don't see what the reason is for the style not being applied.

What is the class name when I look at it in the Browser's Developer Tool?

![image](https://user-images.githubusercontent.com/47337/182395893-902ebad3-a139-4260-88a8-303eac98e676.png)

**Comment by cbmarchetti** [comment]
Hi Onozaty,
Thanks for your help

![image](https://user-images.githubusercontent.com/104323419/182460548-e325aeec-a940-4525-9a69-477747592dcb.png)

**Comment by ishikawa999** [comment]
I see, the cf_#{id} class does not exist in different versions of Redmine.
The following code might work.

```	
$(function(){
  $("input[name='issue[custom_field_values][82][]']").first().closest('span.enumeration_cf.check_box_group').css("column-count", "4");
});
```
<img width="908" alt="screenshot 2022-08-03 8 45 43" src="https://user-images.githubusercontent.com/14245262/182495272-183f3f08-162d-4a4b-8932-70632418a49c.png">

**Comment by cbmarchetti** [comment]
I think that the code conflict with other plugins https://github.com/bap14/redmine_custom_field_hints
I uninstalled that plugin and now everything works ok
Thanks so much!!
best wishes
