### ISSUE TITLE
How can I Display "default value" in issue_custom_field_values.sql_cf?

### ISSUE THREAD

**Issue by cbmarchetti** [onozaty/redmine-view-customize-scripts#90]
Hi!
How can I do this?
$(function() {
 switch($('#issue_custom_field_values_125.sql_cf.cf_125').val()) {
    case '125':
		$('#issue_custom_field_values_125.sql_cf.cf_125').val(1); /*position first*/
      break; 
});

**Comment by onozaty** [comment]
I don't know what sql_cf is.
Is it a custom field when using some plugin?

A screen capture may help with understanding.

**Comment by cbmarchetti** [comment]
Yes, it's custom_field_sql plugin 

https://github.com/apsmir/custom_field_sql

![image](https://user-images.githubusercontent.com/104323419/183439404-8eac752e-4152-484f-b104-60e54695f30b.png)

![image](https://user-images.githubusercontent.com/104323419/183440161-fe7ebee4-f3b6-499f-94b8-d19ad07f04c5.png)

**Comment by onozaty** [comment]
Thank you very much.
It's a selectbox.

Can you tell me a little more about what you would like to do?
You want to display the default value, what is the default value in the previous screen capture?

**Comment by cbmarchetti** [comment]
In the select box (sql) the default value is always empty. 
I need the default value to be the first value in the list. 
My list has only one item, because it counts the issue's custom_values. I am using select box (sql) only to display a value (count).
![image](https://user-images.githubusercontent.com/104323419/183446782-9a068ed3-de19-4354-bbda-b873df5205de.png)

![image](https://user-images.githubusercontent.com/104323419/183446902-d5bffe76-ec4b-4723-83d0-1d55a74bf814.png)

**Comment by onozaty** [comment]
You would have to select the second item.
Try the code below.

```javascript
$('#issue_custom_field_values_125 > option:nth-child(2)').attr('selected', true);
```

One way to do this is to delete the first item.

```javascript
$('#issue_custom_field_values_125 > option:nth-child(1)').remove();
```

**Comment by cbmarchetti** [comment]
perfect!!!
![image](https://user-images.githubusercontent.com/104323419/183477314-717ef986-8dec-4449-946e-91610bbb1cea.png)
