### ISSUE TITLE
How can I Display "user" custom field checkboxes in 4 columns?

### ISSUE THREAD

**Issue by cbmarchetti** [onozaty/redmine-view-customize-scripts#92]
Hi!

I try:

> Path pattern : /person
> Path pattern : /people
> Insertion position: Bottom of issue form
> Insertion position: Bottom of all pages

![image](https://user-images.githubusercontent.com/104323419/183971230-42e394be-cd77-47cf-ac5c-8f84c56247a0.png)

![image](https://user-images.githubusercontent.com/104323419/183972721-375fb088-54ad-4e8f-9f45-288a944c4272.png)

![image](https://user-images.githubusercontent.com/104323419/183969143-cefc0de6-4415-411c-aee6-27c297d11101.png)

![image](https://user-images.githubusercontent.com/104323419/183968951-229da56b-b76f-45c1-b531-8ac553547983.png)

http://redmineup.com/pages/plugins/people

**Comment by onozaty** [comment]
Looking at the image, there appear to be several mistakes.
Could you please try changing them as follows.

* Path pattern : `/person` -> 
Even if it is inserted on all pages, it will have no effect if there is no corresponding element.
* Insertion position: `Bottom of issue form` -> `Head of all pages`
* Type : `JavaScript` -> `CSS`

Thanks.

**Comment by cbmarchetti** [comment]
Perfect!
Thk
