### ISSUE TITLE
チケット作成時の件名に自動採番するカスタムフィールドは使用できますか？

### ISSUE THREAD

**Issue by 88ya** [onozaty/redmine-view-customize-scripts#95]
チケット作成時に処理を行う
https://blog.enjoyxstudy.com/entry/2016/06/12/000000
を参考にチケット作成時の件名にカスタムフィールドの値を入れようとしているのですがうまくいきません。

うまくいかないのは、プラグインを入れて自動採番しているフィールドです。
テキスト形式のカスタムフィールドだと大丈夫でした。

挿入位置　チケット入力欄の下
種類　JavaScript

コード
    // 題名の先頭にカスタムフィールドの値を埋め込む
    var subject = $('#issue_custom_field_values_2').val() + ':' + $('#issue_subject').val();
    $('#issue_subject').val(subject);

  エンジニアではないので色々なサンプルを見ているのですがどうすればよいかわからず。
  そもそも、自動採番のフィールドが使用できるのかどうか教えていただけますでしょうか。
  よろしくお願いいたします。

**Comment by onozaty** [comment]
自動採番しているフィールドは、チケット作成時に画面に見えているものでしょうか。
画面に見えていない(作成時に採番される)ものだと、出来ないと思います。

**Comment by 88ya** [comment]
自動採番項目は、チケット作成時には見えていない項目です。
件名を変えることは諦めたいと思います。
ご教示いただきありがとうございました。
