### ISSUE TITLE
Hide the Add link (subtask ) according to the value of the status_id 

### ISSUE THREAD

**Issue by saifabood** [onozaty/redmine-view-customize-scripts#96]
thx for your amazing plugin
i need your help in this case 
before
![44](https://user-images.githubusercontent.com/113475410/190007971-28cfba39-40f4-405c-a73a-0729e749c31f.png)
after
![55](https://user-images.githubusercontent.com/113475410/190009964-14294156-fb1e-494e-91be-99b4306290ce.png)

**Comment by onozaty** [comment]
Try the following

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0051.hide_add_link_in_subtask_according_to_status/example.md

Change the `status-3` to the ID of the status you want to hide.

Thanks.

**Comment by saifabood** [comment]
thx its working
