### ISSUE TITLE
count selected checkbox

### ISSUE THREAD

**Issue by cbmarchetti** [onozaty/redmine-view-customize-scripts#97]
Hello, can you help me?
I need to count the selected checkbox

1) issue before save (count checkbox )
    Customfield_22 = "SELECT...("Básico")...) =1
    Customfield_23 = "SELECT...("Intermedio")...) = 2
    Customfield_24 = "SELECT...("Superior")...) = 1
    Customfield_25 = "SELECT...("Básico", "Intermedio","Superior")...) = 4

2) issue  modified
add 2 checkbox

3) issue after save - Incorrect
    Customfield_22 = 1
    Customfield_23 =  2
    Customfield_24 =  1
    Customfield_25 =  4

4) issue  modified - only view or reload
    Customfield_22 = 2
    Customfield_23 = 3
    Customfield_24 =  1
    Customfield_25 =  6

5) issue after save - correct
    Customfield_22 = 2
    Customfield_23 = 3
    Customfield_24 =  1
    Customfield_25 =  6
[Video_2022-09-19_153600_edit.zip](https://github.com/onozaty/redmine-view-customize-scripts/files/9601699/Video_2022-09-19_153600_edit.zip)

**Comment by onozaty** [comment]
You can count the number of checked checkboxes with the following code.
This is an example for a custom field ID of `1`.

```javascript
$('input[name="issue[custom_field_values][1][]"]:checked').size();
```

If you want to further refine the checkboxes by value, you can write the following.


```javascript
$('input[name="issue[custom_field_values][1][]"]:checked').filter(function(i, e) { return $(e).val() == "10"}).size();
````

Thanks.

**Comment by cbmarchetti** [comment]
Hi Onozaty!

is it possible to filter by **text**?

```javascript
$('input[name="issue[custom_field_values][1][]"]:checked').filter(function(i, e) { return $(e).val() == "10"}).size();
$('input[name="issue[custom_field_values][1][]"]:checked').filter(function(i, e) { return $(e).**text() == "Básico"**}).size();
$('input[name="issue[custom_field_values][1][]"]:checked').filter(function(i, e) { return $(e).**text() == " Básico"**}).size();
```

![image](https://user-images.githubusercontent.com/104323419/191874260-ed5e00cd-94a3-42e4-a275-cf1ea919a43c.png)


Thanks

**Comment by onozaty** [comment]
Please try the following

```javascript
$('input[name="issue[custom_field_values][1][]"]:checked').filter(function(i, e) { return $(e).parent().text().trim() == "Básico" }).size();
```

**Comment by cbmarchetti** [comment]
Thank you for your plugin & help!
