### ISSUE TITLE
Custom Fields - Edit

### ISSUE THREAD

**Issue by robertotsi** [onozaty/redmine-view-customize-scripts#98]
How to aply this example, when i need to edit a issue?
https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0007.link_custom_fields/example.md

When i edit a issue in my project, i lost informations from original issue.

**Comment by robertotsi** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/79494144/194952877-9cd045f1-57f1-4531-a519-9e3471f9865d.gif)

**Comment by onozaty** [comment]
In my environment, there was no such thing as being cleared during editing.
Confirmed with Redmine 5.0.0 and 4.2.2.

![98](https://user-images.githubusercontent.com/47337/195102236-6f6bf97d-bd2a-4b64-8238-c25c472d7dd8.gif)

It may be that some other setting or plugin is affecting it.

**Comment by robertotsi** [comment]
> In my environment, there was no such thing as being cleared during editing. Confirmed with Redmine 5.0.0 and 4.2.2.
> 
> ![98](https://user-images.githubusercontent.com/47337/195102236-6f6bf97d-bd2a-4b64-8238-c25c472d7dd8.gif)
> 
> It may be that some other setting or plugin is affecting it.

Can you share the code example from your gif?

**Comment by onozaty** [comment]
> Can you share the code example from your gif?

Same as the example below.

* https://github.com/onozaty/redmine-view-customize-scripts/blob/master/examples/0007.link_custom_fields/example.md

```javascript
$(function() {

  // Note: Change the ID according to the custom field you want to target.
  const parentFieldId = 'issue_custom_field_values_1';
  const childFieldId = 'issue_custom_field_values_2';

  const isTarget = function(child, parent) {
    if (child.val() === '') {
      // Unselect is always target
      return true;
    }

    // forward match
    return child.text().indexOf(parent.text()) == 0;
  }

  const narrowChildField = function() {

    const parentSelected = $('#' + parentFieldId + ' > option:selected');

    $('#' + childFieldId + ' > option').each(function() {

      const child = $(this);

      // Narrow down by match.
      // (In IE, option is not hidden by "display:none", so "disabled" it to make it unselectable.)
      if (isTarget(child, parentSelected)) {
        child.show();
        child.prop('disabled', false);
      } else {
        child.hide();
        this.selected = false;
        child.prop('disabled', true);
      }
    });
  }

  $('#' + parentFieldId).on('change', narrowChildField);

  narrowChildField();
});
```

**Comment by robertotsi** [comment]
tks my friend. you`re amazing.
