### ISSUE TITLE
Hint to the user to change the tracker when creating a sub-task

### ISSUE THREAD

**Issue by saifabood** [onozaty/redmine-view-customize-scripts#99]
by appear pop msg to the user OR change colour or background the page 
To give an idea to the user is now under any misleading

**Comment by onozaty** [comment]
I think you can determine if the query parameter has parent_issue_id to determine if it is a subtask addition or not.

```javascript
if (new URL(location).searchParams.get('issue[parent_issue_id]') != null) {
  $('#issue_tracker_id').parent().append($('<span style="color:red">Please change the Tracker.</span>'));
}
```

![99](https://user-images.githubusercontent.com/47337/196194877-46782fcb-8b89-4fe4-9a83-e1f0169c7051.gif)

Thanks.

**Comment by saifabood** [comment]
i like your idea about the hint, if u can change background_image or background-color when user change the tracker

**Comment by onozaty** [comment]
Does this mean that if the tracker is changed, the message will be cleared?

I feel like this is becoming a JavaScript or HTML question, not a question about View customize.
If you have some code that you have tried, it might be easier to advise if you share it with me.

**Comment by onozaty** [comment]
Does this mean that if the tracker is changed, the message will be cleared?

I feel like this is becoming a JavaScript or HTML question, not a question about View customize.
If you have some code that you have tried, it might be easier to advise if you share it with me.

In the first place, if the tracker is cleared when the sub task is created, is there no need for a hint?
